- Cargo.lock
- Cargo.toml
- docker-compose.yml
- src/main.rs
- static/login.html
- static/main.js
- static/me.html
CORS was a mess, not sure if its fully "secure" though
- feature: add cors
- formatting: add folders
- feat: added redis cache for sessions
- feat: Login Works!!!
> 8 Authenticate Routes

- src/main.rs
Not sure what good values are to have, but its good to have
this PR here
- feat: Added login deadline and visit deadline
> Added login and visit deadline into Auth

- Cargo.lock
- Cargo.toml
- migrations/2023-04-20-165322_create_messages/up.sql
- src/data/models.rs
- src/data/schema.rs
- src/handlers/message_handler.rs
- src/handlers/mod.rs
- src/handlers/topic_handler.rs
- src/main.rs
- src/operators/message_operator.rs
- src/operators/mod.rs
- src/operators/topic_operator.rs
- WIP: open ai route
- WIP: streaming openai data
- WIP: one last error w/ GPT completion
- feature: first draft of create message completion
- working completions route
- bugfix: sort order on messages
> 23 openai messsages routes

- src/actors/completion_websocket.rs
- src/handlers/message_handler.rs
This fetches topic information based on the topic id, if the topic id is not valid it retuns and empty array.
This is currently not blocking on database requests
> 35 set topictopic sets the new topic returns messages

- src/actors/completion_websocket.rs
Updated websocket to return error on missing required arguments,
> 37 return message if arguments are invalid

- src/actors/completion_websocket.rs
- src/handlers/message_handler.rs
- src/operators/message_operator.rs
Created new query for checking if a user owns a topic and added a check to see if a user owns a topic before fetching topic information
> 40 authenticate user on web socket connection

- docker-compose.yml
- migrations/2023-05-06-205756_create_stripe_customers/up.sql
- src/data/models.rs
- src/data/schema.rs
- src/handlers/auth_handler.rs
- src/handlers/invitation_handler.rs
- src/handlers/message_handler.rs
- src/handlers/mod.rs
- src/handlers/register_handler.rs
- src/handlers/stripe_handler.rs
- src/handlers/topic_handler.rs
- src/lib.rs
- src/operators/email_operator.rs
- src/operators/message_operator.rs
- src/operators/mod.rs
- src/operators/password_reset_operator.rs
- src/operators/stripe_customer_operator.rs
- src/operators/topic_operator.rs
- style: Fixed clippy errors
- refactor: Changed checkout session url to handle not having the user object
> Refactor stripe operators to make checkout sessions pre invite

- Cargo.lock
- Cargo.toml
- migrations/2023-05-06-205756_create_stripe_customers/up.sql
- migrations/2023-05-10-032820_create_user_plans_table/down.sql
- migrations/2023-05-10-032820_create_user_plans_table/up.sql
- src/data/models.rs
- src/data/schema.rs
- src/handlers/message_handler.rs
- src/handlers/register_handler.rs
- src/handlers/stripe_handler.rs
- src/operators/message_operator.rs
- src/operators/stripe_customer_operator.rs
- src/operators/topic_operator.rs
silver = 1000 messages
gold = 5000 messages
no plan = 20 messages
> feature: limit messages based on tier

- migrations/2023-05-10-032820_create_user_plans_table/up.sql
- src/data/models.rs
- src/data/schema.rs
- src/handlers/message_handler.rs
- src/handlers/stripe_handler.rs
- src/lib.rs
- src/operators/message_operator.rs
- src/operators/stripe_customer_operator.rs
Not sure if all the arms needed are present but the basic idea is here.
> 65 if succeeds stripe hits out webhook

- migrations/2023-05-10-032820_create_user_plans_table/up.sql
- src/data/models.rs
- src/data/schema.rs
- src/handlers/stripe_handler.rs
- src/lib.rs
- src/operators/stripe_customer_operator.rs
- feature: Get sub by user and remove cancel sub
> 58 feature downgradeupgrade or cancel subscription

- migrations/2023-05-10-032820_create_user_plans_table/up.sql
- src/data/models.rs
- src/data/schema.rs
- src/handlers/stripe_handler.rs
- src/lib.rs
- src/operators/stripe_customer_operator.rs
- feat: Update plan on stripe side
- feat: Update database on subscription update
> Update Plan subscriptions

- migrations/2023-05-15-061509_normal_chat/down.sql
- migrations/2023-05-15-061509_normal_chat/up.sql
- src/data/models.rs
- src/data/schema.rs
- src/handlers/topic_handler.rs
- src/operators/message_operator.rs
- Added normal_chat option to topics
- Feature: topic_handler gets the topic from the message
- feat: changes prompt message when in normal chat mode
> 78 regular chat

- src/handlers/card_handler.rs
- src/lib.rs
- src/operators/card_operator.rs
- bugfix: Properly encoded data with uuid and feat: Search route
- Feature: Added optional link to card route
- feature: added upvotes to create and search routes
- WIP vote route
- feat: Added upvote / downvote functionality
> 90 route for upvoting downvoting card

- src/handlers/card_handler.rs
- src/lib.rs
- src/operators/card_operator.rs
> 92 create get card operation

- src/handlers/card_handler.rs
- src/lib.rs
- src/operators/card_operator.rs
- bugfix: Properly encoded data with uuid and feat: Search route
- Feature: Added optional link to card route
- feature: added upvotes to create and search routes
- feature: added upvoting and downvoting routes
- feature: Get card route
- feat: Added pagination for searching cards
> 94 pagination on get card route

- src/handlers/card_handler.rs
- src/lib.rs
- src/operators/card_operator.rs
- feature: vote route removed and require auth on create
> 96 simplify backend only get content and link

- src/handlers/invitation_handler.rs
- src/handlers/password_reset_handler.rs
- src/operators/email_operator.rs
- src/operators/password_reset_operator.rs
- src/operators/stripe_customer_operator.rs
- feat: Email routes are based on the application they requested
> 98 have auth email return name based on origin

- src/handlers/card_handler.rs
- src/handlers/invitation_handler.rs
- src/handlers/password_reset_handler.rs
- src/lib.rs
- src/operators/card_operator.rs
- src/operators/email_operator.rs
- src/operators/stripe_customer_operator.rs
- bugfix: Fixed issue with search route expecting votes
> bugfix: fixed issue with search

- migrations/2023-05-27-192000_user_info/down.sql
- migrations/2023-05-27-192000_user_info/up.sql
- migrations/2023-05-27-213444_card_metadata/down.sql
- migrations/2023-05-27-213444_card_metadata/up.sql
- src/data/models.rs
- src/data/schema.rs
- src/handlers/auth_handler.rs
- src/handlers/card_handler.rs
- src/handlers/message_handler.rs
- src/handlers/mod.rs
- src/handlers/user_handler.rs
- src/handlers/vote_handler.rs
- src/lib.rs
- src/operators/card_operator.rs
- src/operators/message_operator.rs
- src/operators/mod.rs
- src/operators/topic_operator.rs
- src/operators/user_operator.rs
- src/operators/vote_operator.rs
- feature: Disallow similar cards
- migration: Added card_metadata and vote_metadata tables
- feat: Updated create_card and search_cards
- feat: get_card_by_id
> Refactor cards to use postgresql instead of qdrant

- Cargo.lock
- Cargo.toml
- Housekeeping: Minimized async-stripe features
> 117 optimize feature list async stripe to the minimum set

- src/handlers/card_handler.rs
- src/handlers/user_handler.rs
- src/operators/card_operator.rs
- src/operators/user_operator.rs
Added page counts to all paginated routes.
> Added total page count to paginated routes

- Cargo.lock
- Cargo.toml
Reverts arguflow/ai-editor#127
> Revert "Revert "117 optimize feature list async stripe to the minimum set""

- migrations/2023-06-06-122000_collection_bookmarks/down.sql
- migrations/2023-06-06-122000_collection_bookmarks/up.sql
- src/data/models.rs
- src/data/schema.rs
- src/handlers/collection_handler.rs
- src/lib.rs
- src/operators/collection_operator.rs
- feat: Migration to create new collection table
- feat: Create Collection Route
- feat: Getting all collections for a logged in user
- feat: Deleting collection by card collection uuid
- feat: Editing a card collection
- feat: Bookmarks table migration
- feat: Create bookmark
- feat: Delete bookmark
> 120 feature bookmarks

- LICENSE.txt
change to BSL v1.1 from GPL V3
/claim #434
> license: change to BSL v1.1

- server/src/lib.rs
> cleanup: in `lib.rs` common resources placed in their own `web::scope`

- .env.search
- .github/ISSUE_TEMPLATE/issue-template.md
- docker-compose.yml
- search/src/components/Atoms/NotificationPopover.tsx
- search/src/components/CardMetadataDisplay.tsx
- search/src/components/ScoreCard.tsx
- search/src/components/SearchForm.tsx
> feature: change filters popover copy and make it configurable #442

- .env.dist
- docker-compose.yml
- server/.env.dist
- server/src/operators/email_operator.rs
> feature: change no-reply@arguflow.gg addresses in email_operator.rs to use a .env email

- server/Cargo.lock
- server/Cargo.toml
- server/migrations/2023-09-18-033906_add-api-key-to-users/down.sql
- server/migrations/2023-09-18-033906_add-api-key-to-users/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/register_handler.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
- server/src/operators/card_operator.rs
- server/src/operators/email_operator.rs
- server/src/operators/user_operator.rs
> feature: api keys as an alternative auth mechanism

- .vscode/settings.json
- chat/.eslintrc.json
- search/.eslintrc.json
- search/package.json
- search/yarn.lock
> fix: developer experience: unify ts/js/tailwind config files between search and chat folders

- search/src/layouts/HomeLayout.astro
- search/src/layouts/SearchLayout.astro
- search/src/pages/create.astro
> bugfix: CSS not loading when clicking on logo

- .env.search
- README.md
- search/src/components/SearchForm.tsx
- server/src/handlers/card_handler.rs
> feature: typewriter and delete effect for SearchForm bar

- search/src/components/CardMetadataDisplay.tsx
- search/src/components/ScoreCard.tsx
- search/utils/apiTypes.ts
> feature: display arbitrary json metadata in frontmatter

- chat/src/components/ShowToast.tsx
- chat/src/root.tsx
fixes https://github.com/arguflow/vault-chat/issues/17
ps:- I've tested in the search page for better view.
success:-
error:-
> feature: toasts on important success and failure events

- .env.chat
- chat/src/components/Atoms/AfMessage.tsx
- chat/src/components/Forms/Survey.tsx
- chat/src/components/Layouts/MainLayout.tsx
- chat/src/components/Navbar/Navbar.tsx
- chat/src/components/Navbar/Sidebar.tsx
- chat/src/components/ScoreCard.tsx
- chat/src/routes/debate.tsx
- chat/src/types/messages.ts
- chat/src/types/topics.ts
- chat/src/utils/apiTypes.ts
- search/src/components/EditUserForm.tsx
- search/src/components/ScoreCard.tsx
- server/src/data/models.rs
- server/src/handlers/message_handler.rs
- server/src/handlers/topic_handler.rs
- server/src/operators/message_operator.rs
> feature: new chat system

- .env.chat
- chat/src/components/Navbar/Sidebar.tsx
- chat/src/routes/index.tsx
- docker-compose.yml
- search/src/components/RegisterOrUserProfile.tsx
> styling: add star button to chat and customizability for dataset, video, and search URL

- search/src/components/EditUserForm.tsx
Hello @skeptrunedev,
This marks my first contribution, and though I couldn't able to run the project locally, I'm confident that the changes I made are correct. However, if any issues arise due to my changes, I sincerely apologize and kindly request that you refrain from merging my pull request."
> Removed the forever spinning loading circle from search UI

- README.md
documentation: added sudo apt install command to README guide
> documentation: add sudo apt install command to README guide

- README.md
this PR is related to resolving the issue #532
> Updated the README discord shield to include discord online member

- search/src/components/CollectionPage.tsx
- search/src/components/ResultsPage.tsx
Bugfix for the issue https://github.com/arguflow/arguflow/issues/524.
Preventing Card expansion until both auth and card requests in client is finished.
> bugfix: card closing after client side request

- search/src/components/ScoreCard.tsx
- server/src/handlers/card_handler.rs
- server/src/operators/card_operator.rs
- server/src/operators/qdrant_operator.rs
> bugfix: filters should only apply when existing

- search/src/components/BookmarkPopover.tsx
- search/src/components/CollectionPage.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/ScoreCard.tsx
- search/src/components/ScoreCardArray.tsx
This PR fixes the card collection not popping up in other cards after creation.
Fixes: #522 
@skeptrunedev  
Please review this PR for the bugfix related to card collections. Your feedback is highly appreciated.
> bugfix: card collections should bubble up after creation

- .env.server
- docker-compose.yml
- search/src/components/CollectionPage.tsx
- search/src/components/CollectionUserPageView.tsx
- search/src/components/Footer.astro
- search/src/components/Notification.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/SingleCardPage.tsx
- search/src/components/UserCardDisplay.tsx
- search/src/pages/card/[cardId].astro
- search/src/pages/card/edit/[cardId].astro
- search/src/pages/collection/[collectionID].astro
- search/src/pages/index.astro
- search/src/pages/search.astro
- search/src/pages/upload.astro
- search/src/pages/user/[...id].astro
- server/src/handlers/auth_handler.rs
- server/src/handlers/card_handler.rs
- server/src/handlers/collection_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/user_handler.rs
- server/src/operators/collection_operator.rs
> feature: add env flag to require auth for all routes

- search/src/components/Atoms/Navbar.tsx
> bugfix: fix mobile ui with github star button

- README.md
- convenience.bat
Solves #545
Also, creates a convenience script for Windows for docker and updates the Linux local development docs to use NVM and install cargo-watch.
> documentation: update documentation to improve local development instructions

- server/migrations/2023-10-05-174630_indexes-on-fields/down.sql
- server/migrations/2023-10-05-174630_indexes-on-fields/up.sql
> feature: index on json

- search/src/components/SearchForm.tsx
- search/src/pages/collection/[collectionID].astro
- search/src/pages/index.astro
- search/src/pages/search.astro
> bugfix: case sensitive filters

- search/src/components/Atoms/ComboboxChecklist.tsx
> bugfix: always show add custom filter

- search/src/pages/collection/[collectionID].astro
- search/src/pages/search.astro
> bugfix: SSR filters

- .env.search
- docker-compose.yml
- search/README.md
- search/src/components/Footer.astro
- search/src/components/ResultsPage.tsx
- search/src/components/ScoreCard.tsx
- search/src/components/ScoreCardArray.tsx
- search/src/pages/card/[cardId].astro
- search/src/pages/card/edit/[cardId].astro
- search/src/pages/collection/[collectionID].astro
- search/src/pages/index.astro
- search/src/pages/search.astro
- search/src/pages/user/[...id].astro
- server/src/handlers/card_handler.rs
- server/src/handlers/collection_handler.rs
> cleanup: final tuning for dup prevention, env simplification, date range

- search/src/components/SearchForm.tsx
> feature: env flag lucky

- server/src/data/models.rs
- server/src/handlers/card_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/card_operator.rs
- server/src/operators/collection_operator.rs
- server/src/operators/user_operator.rs
> feature: add highlights to all searches and removed extranous model

- search/src/components/EditUserForm.tsx
- search/utils/apiTypes.ts
- server/src/handlers/card_handler.rs
- server/src/handlers/collection_handler.rs
- server/src/handlers/message_handler.rs
> feature: generate API Key + clippy lint

- chat/src/components/Layouts/MainLayout.tsx
- chat/src/components/ScoreCard.tsx
- chat/src/routes/auth/login.tsx
- chat/src/routes/auth/password/[id].tsx
- chat/src/routes/auth/password/reset.tsx
- chat/src/routes/auth/register/(register).tsx
- chat/src/routes/auth/register/[id].tsx
- chat/src/routes/chat.tsx
- chat/src/routes/index.tsx
- search/src/components/CollectionUserPageView.tsx
- search/src/components/LoginForm.tsx
- search/src/components/PasswordResetForm.tsx
- search/src/components/RegisterForm.tsx
- search/src/components/SetPasswordForm.tsx
- search/src/components/SetResetPasswordForm.tsx
> cleanup: change all api_host to apiHost + creds include for auth routes

- chat/src/components/ScoreCard.tsx
- search/src/components/CardMetadataDisplay.tsx
- search/src/components/ScoreCard.tsx
- search/src/components/ScoreCardArray.tsx
- search/src/components/SingleCardPage.tsx
- bugfix: show more not being disabled correctly
- bugfix: text color within card seems to be unstable
> bugfix: show more before client request finished happening, text color in card needs !important mod

- server/Cargo.lock
- server/Cargo.toml
- server/migrations/2023-10-12-202441_add-tracking-id-to-card_metadata/down.sql
- server/migrations/2023-10-12-202441_add-tracking-id-to-card_metadata/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/card_handler.rs
- server/src/operators/card_operator.rs
- server/src/operators/collection_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/user_operator.rs
@Scorpil I think this should be what you were looking for
> feature: add tracking_id to card such that you can prevent duplicates

- search/src/components/Atoms/AfMessage.tsx
- search/src/components/Atoms/FullScreenModal.tsx
- search/src/components/ChatPopup.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/ScoreCard.tsx
- search/utils/apiTypes.ts
- server/build.rs
- server/src/data/models.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/card_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/card_operator.rs
> generate off card

- server/src/handlers/card_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/card_operator.rs
> feature: add " " operator like google search

- search/src/components/SuggestedQueries.tsx
- search/src/pages/search.astro
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/card_operator.rs
> feature: suggested queries

- chat/src/root.tsx
- search/src/layouts/HomeLayout.astro
- search/src/layouts/SearchLayout.astro
- search/src/pages/card/[cardId].astro
- search/src/pages/collection/[collectionID].astro
This PR implements the dataset name with the title for both search and chat pages.
Fixes: #503 
@skeptrunedev
Please review this PR. Your feedback is highly appreciated.
> feature: include dataset name with the title name

- search/src/components/SearchForm.tsx
This pull request introduces the search history functionality for search. The search history is stored in local storage and displays the top 3 matches in the history list.
Fixes: #600 
@skeptrunedev
Please review this PR.  If you have any suggestions or feedback, please don't hesitate to share. Thank you!
> Implemented feature: search history

- server/src/operators/card_operator.rs
> bugfix: filters on full text search causing panic

- search/src/components/EditCardPageForm.tsx
- search/src/components/ScoreCard.tsx
- search/utils/apiTypes.ts
- server/src/handlers/card_handler.rs
- server/src/lib.rs
- server/src/operators/card_operator.rs
- server/src/operators/qdrant_operator.rs
> feature: add resource routes for tracking_id

- chat/src/components/Atoms/AfMessage.tsx
- chat/src/components/Layouts/MainLayout.tsx
- chat/src/components/ScoreCard.tsx
- search/src/components/Atoms/AfMessage.tsx
- search/src/components/Atoms/FullScreenModal.tsx
- search/src/components/BookmarkPopover.tsx
- search/src/components/ChatPopup.tsx
- search/src/components/CollectionPage.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/ScoreCard.tsx
- search/src/components/ScoreCardArray.tsx
- search/src/components/SingleCardPage.tsx
- server/src/handlers/card_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/card_operator.rs
- server/src/operators/message_operator.rs
> RAG with doc nums

- README.md
> fix: add correct links to readme

- .github/workflows/chat-tests.yml
- .github/workflows/rust-tests.yml
- .github/workflows/search-tests.yml
Disabled rust github action due to imagemagick7 being added, (required for compiling - breaking runner).
> devops: disabled rust gh actions

- CHANGE_LOG.md
- search/src/components/Atoms/ComboboxChecklist.tsx
> styling: slightly improved filters UI

- CHANGE_LOG.md
- chat/src/components/Atoms/AfMessage.tsx
- server/src/handlers/card_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/card_operator.rs
> feature: add negation operator

- search/src/components/SearchForm.tsx
- search/src/pages/index.astro
- search/yarn.lock
- server/server-python/update_qdrant.py
- server/src/errors.rs
- server/src/handlers/card_handler.rs
- server/src/handlers/collection_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/card_operator.rs
- server/src/operators/qdrant_operator.rs
> feature: qdrant filtering

- server/src/operators/file_operator.rs
> feature: create less threads on file upload route

- search/src/components/Atoms/PaginationController.tsx
Fixes issue with Collections pages not rendering properly
> bugfix: PaginationController to use URL object instead of string parsing

- server/src/lib.rs
> bugfix: change tokenizer for qdrant to fix quote search

- server/src/operators/search_operator.rs
This sucks, but for now it's still the best way. 
Qdrant has an issue where text filters can be either `keyword` or `substring` and there is not currently a known way to force `substring`. Due to that, it's still more reliable to use pg filters in front of Qdrant than native Qdrant filters. 
There is a gist [here](https://gist.github.com/skeptrunedev/3ede217aa78d6462c5c52c63d0318764) which contains a function for Qdrant filter we can migrate back to when the time comes that we can force substring.
> feature: use pg as front to qdrant for filters again (minor regression)

- server/src/handlers/card_handler.rs
- server/src/operators/card_operator.rs
> bugfix: fix updating collisions when root card is deleted

- search/src/components/TopCardsTable.tsx
- server/src/handlers/card_handler.rs
- server/src/operators/file_operator.rs
> feature: BYO embedding for card create

- server/migrations/2023-12-13-000805_add_invitation_table_back/down.sql
- server/migrations/2023-12-13-000805_add_invitation_table_back/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/mod.rs
- server/src/lib.rs
- server/src/operators/invitation_operator.rs
- server/src/operators/mod.rs
> feature: create org is no dataset is passed to the login route and inviations

- convenience.sh
- server/src/data/models.rs
- server/src/lib.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: partition qdrant by id rather than by collection

- server/Cargo.lock
- server/src/handlers/auth_handler.rs
- server/src/operators/stripe_operator.rs
> feature: default org name based off of email

- server/migrations/2023-12-16-191750_new_user_management_table/down.sql
- server/migrations/2023-12-16-191750_new_user_management_table/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/auth_handler.rs
- server/src/operators/search_operator.rs
- server/src/operators/user_operator.rs
> feature: user management table

- server/src/data/models.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/card_handler.rs
- server/src/handlers/collection_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/message_handler.rs
- server/src/handlers/organization_handler.rs
- server/src/handlers/stripe_handler.rs
- server/src/handlers/topic_handler.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
- server/src/operators/file_operator.rs
> feature: guard routes by perms

- embedding-server/embeddings.py
- server/src/data/models.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/card_handler.rs
- server/src/handlers/collection_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/card_operator.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/model_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: custom embedding sizes + make embed server openai compatible

- server/migrations/2023-12-19-213615_add-weight-to-card/down.sql
- server/migrations/2023-12-19-213615_add-weight-to-card/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/card_handler.rs
- server/src/operators/card_operator.rs
- server/src/operators/collection_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/search_operator.rs
- server/src/operators/user_operator.rs
> feature: weights for cards

- embedding-server/embeddings.py
- server/Cargo.lock
- server/Cargo.toml
- server/src/data/models.rs
- server/src/handlers/card_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/operators/card_operator.rs
- server/src/operators/search_operator.rs
> bugfix: update card route, timestamps, and embedding server

- server/migrations/2023-04-20-165322_create_messages/up.sql
- server/migrations/2023-08-07-071924_create-user-collection-count-table/up.sql
- server/migrations/2023-12-21-002039_create-card-metadata-count-table/down.sql
- server/migrations/2023-12-21-002039_create-card-metadata-count-table/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/card_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/card_operator.rs
- server/src/operators/organization_operator.rs
- server/src/operators/user_operator.rs
> feature: enforce plan limits

- keycloak/themes/arguflow/login/resources/css/styles.css
> feature: dark and light theming for login page

- server/migrations/2024-01-03-070225_count_table/down.sql
- server/migrations/2024-01-03-070225_count_table/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/organization_operator.rs
> feature: move to a plan usage table

- convenience.sh
- server/src/handlers/auth_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/stripe_handler.rs
> feature: added conditional to check for AF-Organization in guards

- server/migrations/2024-01-04-085522_update_file_size/down.sql
- server/migrations/2024-01-04-085522_update_file_size/up.sql
> bugfix: update_files_storage_counts function accounts for UPDATE case

- server/src/data/models.rs
- server/src/handlers/auth_handler.rs
- server/src/operators/user_operator.rs
> feature: orgs to slim-user

- search/src/components/SearchForm.tsx
- search/src/layouts/HomeLayout.astro
- server/migrations/2024-01-03-221426_set-default-org-usage-data/down.sql
- server/migrations/2024-01-05-185149_set-default-dataset-usage-data/down.sql
- server/migrations/2024-01-05-185149_set-default-dataset-usage-data/up.sql
- server/src/data/models.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/collection_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/organization_handler.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/organization_operator.rs
> feature: added usage metrics to dashboard

- .env.search
- search/src/components/ChatPopup.tsx
- search/src/components/RegisterOrUserProfile.tsx
- search/src/layouts/HomeLayout.astro
- search/src/layouts/SearchLayout.astro
- search/src/pages/chunk/[chunkId].astro
- search/src/pages/chunk/edit/[chunkId].astro
- search/src/pages/collection/[collectionID].astro
- search/src/pages/index.astro
- search/src/pages/search.astro
- search/src/pages/user/[...id].astro
- search/utils/apiTypes.ts
- server/src/handlers/organization_handler.rs
- server/src/handlers/stripe_handler.rs
- server/src/operators/organization_operator.rs
- server/src/operators/stripe_operator.rs
- server/src/operators/user_operator.rs
> feature: organization choosebox and pass stripe errors back to stripe

- server/src/handlers/stripe_handler.rs
> bugfix: invalidate org_with_plan_sub redis cache when sub is canceled

- search/src/components/RegisterOrUserProfile.tsx
- server/migrations/2024-01-09-235345_change_inv_field_name/down.sql
- server/migrations/2024-01-09-235345_change_inv_field_name/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/organization_handler.rs
- server/src/handlers/stripe_handler.rs
- server/src/lib.rs
- server/src/operators/invitation_operator.rs
- server/src/operators/organization_operator.rs
> feature: user management UI

- server/src/data/models.rs
- server/src/operators/dataset_operator.rs
> cleanup: removed server-config from get_datasets_from_organization

- convenience.sh
- server/Cargo.toml
- server/migrations/2024-01-11-202441_add_role_to_invitations/down.sql
- server/migrations/2024-01-11-202441_add_role_to_invitations/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/user_handler.rs
- server/src/operators/email_operator.rs
- server/src/operators/invitation_operator.rs
- server/src/operators/user_operator.rs
> feature: add role to invites

- docker-compose.yml
- server/Cargo.lock
- server/Cargo.toml
- server/Dockerfile.no-ocr
- server/Dockerfile.ocr
- server/src/handlers/file_handler.rs
I hope this will make the server docker image be much smaller
> feature: Smaller Dockerfile with no ocr

- server/src/handlers/dataset_handler.rs
> feature: invalidate cache on env update

- docker-compose.yml
- server/.dockerignore
- server/Dockerfile.no-ocr
- server/Dockerfile.ocr
- server/server-python/requirements.txt
arguflow/server:no-ocr is about 417MB now
> feature: even smaller docker files

- search/src/components/EditUserForm.tsx
- server/migrations/2024-01-18-234128_api_key_table/down.sql
- server/migrations/2024-01-18-234128_api_key_table/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
- server/src/operators/search_operator.rs
- server/src/operators/user_operator.rs
> feature: api key table

- server/src/handlers/auth_handler.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/topic_handler.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
> documentation: start adding descriptions to openapi spec

- server/Cargo.lock
- server/Cargo.toml
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
- setup.py
> feature: openrouter support

- server/src/af_middleware/auth_middleware.rs
> bugfix: fix bug with having TR-Organization and TR-Dataset in request header

- docker-compose.yml
> feature: add health checks to docker compose and isolate backend

- server/src/handlers/topic_handler.rs
> feature: be able to set your own name for topics

- search/src/components/BookmarkPopover.tsx
- search/src/components/CollectionPage.tsx
- search/src/components/CollectionUserPageView.tsx
- search/src/components/EditUserForm.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/UploadFile.tsx
- server/src/handlers/topic_handler.rs
- server/src/lib.rs
> feature: refactor get topics route to get topics for other users, bugfix: match search client with new api reqs

- server/migrations/2024-01-23-012420_move_notifications_to_datasets/down.sql
- server/migrations/2024-01-23-012420_move_notifications_to_datasets/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/notification_handler.rs
- server/src/operators/file_operator.rs
- server/src/operators/notification_operator.rs
> feature: moved notifications to be associated with datasets rather than users

- search/src/stores/datasetStore.ts
> feature: dataset in the url

- .gitignore
- server/migrations/2024-01-24-021641_remove_side_from_topic/down.sql
- server/migrations/2024-01-24-021641_remove_side_from_topic/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/message_handler.rs
- server/src/handlers/topic_handler.rs
- server/src/operators/message_operator.rs
> feature: remove side and normal chat from topics

- server/src/lib.rs
> cleanup: add version to redoc spec

- search/src/pages/Search.tsx
- server/src/handlers/chunk_handler.rs
- server/src/operators/search_operator.rs
> bugfix: fixed score when weight = 0

- server/Cargo.lock
- server/Cargo.toml
- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
> feature: changed OPENROUTER_API_KEY to LLM_API_KEY

- .vscode/settings.json
- embedding-server/embeddings.py
- search/src/components/CollectionPage.tsx
- search/src/components/ResultsPage.tsx
- tr-cli/requirements.txt
- tr-cli/trieve/__init__.py
- tr-cli/trieve/__main__.py
- tr-cli/trieve/api.py
- tr-cli/trieve/cli.py
- tr-cli/trieve/config.py
- tr-cli/trieve/db.py
> WIP: trieve cli

- server/migrations/2024-01-25-102937_api-key-roles/down.sql
- server/migrations/2024-01-25-102937_api-key-roles/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/user_handler.rs
- server/src/operators/user_operator.rs
> feature: added roles to api keys

- search/src/components/BookmarkPopover.tsx
- search/src/pages/Home.tsx
- search/src/pages/collection/ViewCollection.tsx
- search/src/stores/datasetStore.ts
- server/src/handlers/auth_handler.rs
- server/src/lib.rs
- tr-cli/trieve/cli.py
> feature: fix dataset id being null in url

- server/Dockerfile.no-ocr
> hotfix: dockerfile patch

- .gitignore
- server/src/data/models.rs
- tr-cli/trieve/api.py
- tr-cli/trieve/cli.py
> feature: added full access perm to api key

- server/src/operators/dataset_operator.rs
- tr-cli/trieve/__main__.py
> speedup: delete all at once rather than one at a time for datasets

- server/src/data/models.rs
- server/src/handlers/file_handler.rs
- server/src/operators/file_operator.rs
> feature: return signed s3 url rather than base64

- server/src/handlers/collection_handler.rs
- server/src/operators/collection_operator.rs
> feature: remove collisions from collections

- server/src/handlers/auth_handler.rs
> bugfix: fix logout route

- server/src/operators/model_operator.rs
> bugfix: remove any non alphanumeric and non whitespace

- server/src/operators/model_operator.rs
> bugfix: return 400 if docs are empty for cross encoder

- embedding-server/embeddings.py
- server/src/operators/model_operator.rs
> feature: patch embedding server if vector is empty or 1key/value

- server/migrations/2024-01-29-164440_tracking-id-unique-with-dataset/down.sql
- server/migrations/2024-01-29-164440_tracking-id-unique-with-dataset/up.sql
- server/src/data/schema.rs
> feature: tracking id unique per dataset

- server/src/operators/stripe_operator.rs
> feature: allow promo codes for stripe checkout

- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: move to qdrant filters

- embedding-server/embeddings.py
> feature: fix rerank bug

- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/search_operator.rs
- feature: collisions as envflag for create_chunk route
- feature: collisions as parameter at lowest level.
- feature: collision flag for everything else
> feature: collisions as a server env flag

- server/src/handlers/auth_handler.rs
> feature: open up health route

- search/utils/apiTypes.ts
- server/src/data/models.rs
- server/src/handlers/auth_handler.rs
> cleanup: remvoe github config param

- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/search_operator.rs
> feature: made highlights customizable and ability to turn them off

- server/src/data/models.rs
- server/src/handlers/user_handler.rs
- server/src/operators/user_operator.rs
> feature: only set api key role if its read only

- server/src/bin/ingestion-microservice.rs
> bugfix: ingestion microservice now runs on multiple threads

- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
> bugfix: fixed llm if base url is empty string and changed to openai

- server/src/bin/ingestion-microservice.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/operators/event_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
> feature: add events when a card is created or fails

- server/src/handlers/group_handler.rs
- server/src/operators/group_operator.rs
> feature: add option to delete chunks when deleting group

- server/migrations/2024-02-01-003109_fix_events_upload/down.sql
- server/migrations/2024-02-01-003109_fix_events_upload/up.sql
> bugfix: add sql for event count

- server/src/handlers/chunk_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
> feature: flag to delete chunks with files

- server/src/operators/stripe_operator.rs
> bugfix: fix stripe checkout bug

- search/src/components/EditChunkPageForm.tsx
- search/src/components/ScoreChunk.tsx
- search/src/pages/CreateChunk.tsx
- search/src/pages/chunk/ViewChunk.tsx
- search/src/pages/chunk/edit/EditChunk.tsx
- search/utils/apiTypes.ts
> bugfix: edit and view chunk pages

- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
> bugfix: fix streaming errors

- server/Cargo.lock
- server/Cargo.toml
- server/src/handlers/chunk_handler.rs
- server/src/handlers/file_handler.rs
- server/src/operators/file_operator.rs
- server/src/operators/search_operator.rs
> feature: added timing for server

- search/src/components/CreateNewDocChunkForm.tsx
- search/src/components/EditChunkPageForm.tsx
> bugfix: make weight inputs adjustable to tenths place

- search/utils/apiTypes.ts
- server/src/data/models.rs
- server/src/handlers/file_handler.rs
> feature: fixed openapi error with file_handler and feature: made file upload default to true

- server/src/handlers/chunk_handler.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
> cleanup: clippy errors

- server/src/handlers/file_handler.rs
> feature: use s3 for images rather than file sys

- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
> bugfix: create FileGroup on file upload

- server/src/data/models.rs
- server/src/operators/file_operator.rs
> feature: return accurate id for create file

- docker-compose.yml
- server/Dockerfile.ocr
> bugfix: OCR Dockerfile image fixed

- search/src/components/GroupPage.tsx
- search/src/components/ScoreChunk.tsx
> bugfix: make search capable of building

- server/migrations/2024-02-20-024527_add_event_count_trigger/down.sql
- server/migrations/2024-02-20-024527_add_event_count_trigger/up.sql
- server/src/bin/ingestion-microservice.rs
- server/src/handlers/event_handler.rs
- server/src/lib.rs
- server/src/operators/event_operator.rs
> feature: added support for event dashboard

- server/.dockerignore
- server/src/operators/file_operator.rs
> feature: pull s3 from instance profile

- .env.chat
- chat/src/components/ScoreChunk.tsx
- docker-compose.yml
> feature: make search UI url configuration in chat chunks

- chat/src/components/Layouts/MainLayout.tsx
- server/src/bin/ingestion-microservice.rs
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/message_handler.rs
- server/src/handlers/topic_handler.rs
- server/src/operators/model_operator.rs
> feature: Default model name to override in Dataset Configurations and refactor DatasetSettings Logic

- search/src/components/GroupPage.tsx
- search/src/pages/Search.tsx
Set hybrid search as the default type of search
> feature: hybrid as default on search ui

- search/src/components/DatasetSelectBox.tsx
- search/src/components/OrganizationSelectBox.tsx
- search/src/stores/datasetStore.ts
- server/src/handlers/invitation_handler.rs
- server/src/operators/user_operator.rs
> bugfix: memoized the dataset and org lists so that they are more stable

- search/src/components/ScoreChunk.tsx
- search/utils/apiTypes.ts
- server/src/data/models.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
> feature: added FILE_NAME_KEY to clientConfig and /get_signed_url/{file}

- .env.docker-compose
- README.md
- convenience.sh
- docker-compose.yml
Added profiles to docker-compose.yml
Now able to run `COMPOSE_PROFILES=dev docker compose up -d`
> feature: docker-compose profiles

- server/src/handlers/chunk_handler.rs
> bugfix: fix weight not being set on upload

- server/src/handlers/chunk_handler.rs
- server/src/handlers/organization_handler.rs
- server/src/operators/search_operator.rs
- server/src/operators/user_operator.rs
> bugfix: fix date biasing

- server/migrations/2024-02-28-060056_add-tracking-id-to-groups/down.sql
- server/migrations/2024-02-28-060056_add-tracking-id-to-groups/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
> feature: added tracking id to groups

- search/src/components/ScoreChunk.tsx
> feature: URI encode the path

- search/src/components/ScoreChunk.tsx
- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: add page sizing, score thresholds and group sizes

- server/src/lib.rs
> patch: fix redoc

- server/src/operators/model_operator.rs
- server/src/operators/search_operator.rs
> bugfix: make sure hybrid only returns `page_size` results

- server/src/bin/ingestion-microservice.rs
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/operators/qdrant_operator.rs
> feature: add server config to disable fulltext

- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
> bugfix: hotfix redoc and update

- search/src/components/EditChunkPageForm.tsx
> bugfix: edit chunk page

- server/src/handlers/chunk_handler.rs
- bugfix: edit chunk page
- documentation: specify what the defaults are for highlight_results and highlight_delimiters
> documentation: update request param docs for highlighting

- server/src/operators/model_operator.rs
- server/src/operators/search_operator.rs
> feature: only top 20 results get reranked for hybrid, bugfix: no more error on no results

- server/Cargo.lock
- server/Cargo.toml
- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/model_operator.rs
> feature: move to ureq for faster processing of embeddings

- server/src/operators/search_operator.rs
> bugfix: make extra results always be at the bottom

- server/src/bin/ingestion-microservice.rs
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/organization_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: add dataset config for collection name, qdrant url, and qdrant api key

- server/src/operators/search_operator.rs
> feature: range filters for all integer payloads

- server/src/bin/ingestion-microservice.rs
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: search-over-group-reccommendations

- server/src/operators/qdrant_operator.rs
> bugfix: make sure qdrant can still search even with no sparse

- .github/workflows/rust-tests.yml
> ops: CI action to clippy check ingestion pipeline

- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> bugfix: fix group recommend request

- server/src/bin/ingestion-microservice.rs
> feature: use core count for num_threads

- search/src/components/GroupPage.tsx
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: added filters for recommendations

- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: correct counts for the search

- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/search_operator.rs
> feature: add option to rerank or not

- server/src/operators/search_operator.rs
> bugfix: make dates sort in the correct order

- server/src/bin/ingestion-microservice.rs
> don't share redis connections across threads

- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/search_operator.rs
> bugfix: make weights be on by default

- server/src/operators/search_operator.rs
> bugfix: sort by hybrid score

- server/src/operators/search_operator.rs
> bugfix: assign cross-encoder score to the group_metadata

- server/src/operators/chunk_operator.rs
> optimization: remove transaction from insert_chunk_metadata_query

- server/migrations/2024-03-14-071944_remove-gin-indexes/down.sql
- server/migrations/2024-03-14-071944_remove-gin-indexes/up.sql
> feature: remove indexes

- server/src/bin/ingestion-microservice.rs
- server/src/operators/qdrant_operator.rs
> ops: add span over qdrant in ingestion service

- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
> cleanup: deprecate all tracking id routes

- server/src/bin/ingestion-microservice.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/qdrant_operator.rs
> feature: update group associations through the update chunk route

- server/src/handlers/auth_handler.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/event_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/message_handler.rs
- server/src/handlers/organization_handler.rs
- server/src/handlers/stripe_handler.rs
- server/src/handlers/topic_handler.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
- documentation: rev version and add full info object
- feature: remove cookie from securityaddon spec
> docs: remove cookie from security addon

- server/src/lib.rs
> doc: up doc version

- embedding-server/embeddings.py
> hotfix: embedding server stays compatible with TEI

- search/src/components/ChunkMetadataDisplay.tsx
- search/src/components/ImageModal.tsx
- search/src/components/ScoreChunk.tsx
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/event_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
> revert: keep old tracking id routes

- keycloak/Dockerfile
It just copies configs into keycloak to make use more succulent
> minor: prebake keycloak image with realm and theme

- server/src/errors.rs
- server/src/operators/qdrant_operator.rs
> visiblity: more logs when not able to send to qdrant

- server/src/operators/model_operator.rs
> bugfix: turn truncate on for sparse embeddings

- server/src/bin/ingestion-microservice.rs
- server/src/data/models.rs
> bugfix: make threshold value a whole number

- search/src/components/EditChunkPageForm.tsx
- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
> feature: fix update route to correct name

- server/Cargo.toml
> ops: optimize release builds and shrink Dockerimage size

- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/group_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> bugfix: query for group_tracking_ids before Filter

- search/src/components/ChunkMetadataDisplay.tsx
- search/src/components/ScoreChunk.tsx
- server/src/bin/ingestion-microservice.rs
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- cleanup: remove duplicated data from UploadIngestionMessage
- cleanup: remove duplicated data from UpdateIngestionMessage
> 1163 optimization remove duplicated data in ingestion redis messages

- server/src/handlers/group_handler.rs
- server/src/operators/group_operator.rs
- server/src/operators/search_operator.rs
> feature: return group_tracking_id for group based routes

- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/search_operator.rs
> feature: return only ids from the requests

- server/src/operators/search_operator.rs
> bugfix: correct error when fetching from qdrant

- .gitignore
- dashboard/src/components/NewDatasetModal.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
> bugfix: fix embedding model not being set correctly

- server/src/operators/chunk_operator.rs
> clarity: cleaner named chunk errors

- chat/src/components/Atoms/AfMessage.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetEvents.tsx
- server/migrations/2024-04-02-023522_add-index-to-events-table/down.sql
- server/migrations/2024-04-02-023522_add-index-to-events-table/up.sql
> feature: added indexes for the event type, feature: add loading spinner

- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
- server/src/operators/search_operator.rs
> feature: convert ISO strings to unix timestamp for filters

- server/src/af_middleware/auth_middleware.rs
- server/src/bin/ingestion-microservice.rs
- server/src/errors.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/message_handler.rs
- server/src/handlers/organization_handler.rs
- server/src/handlers/stripe_handler.rs
- server/src/handlers/topic_handler.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/email_operator.rs
- server/src/operators/event_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/invitation_operator.rs
- server/src/operators/message_operator.rs
- server/src/operators/model_operator.rs
- server/src/operators/organization_operator.rs
- server/src/operators/parse_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
- server/src/operators/stripe_operator.rs
- server/src/operators/topic_operator.rs
- server/src/operators/user_operator.rs
- **cleanup: remove DefaultError in favor of service error**
- **docs: rev api spec**
> cleanup: remove DefaultError in favor of ServiceError

- dashboard/src/components/InviteUserModal.tsx
- dashboard/src/components/ShowToasts.tsx
> feature: add toast on user invite

- dashboard/src/components/ApiKeyGenerateModal.tsx
- dashboard/src/components/DatasetOverview.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
- server/src/handlers/dataset_handler.rs
- server/src/handlers/topic_handler.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
> feature: make all delete have no req bodies

- server/src/handlers/chunk_handler.rs
- server/src/operators/search_operator.rs
> feature: use pg for metadata filtering as it has an index on metadata

- server/Cargo.lock
- server/Cargo.toml
- server/src/bin/ingestion-microservice.rs
> bugfix: graceful shutdown for ingestion microservice

- server/src/operators/qdrant_operator.rs
> visibility: print ids on failure

- dashboard/src/components/MultiSelect.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetEvents.tsx
- dashboard/yarn.lock
- server/src/data/models.rs
> feature: event filtering

- server/Dockerfile.no-ocr
> bugfix: fix no-ocr image

- .env.server
- server/src/lib.rs
> feature: Quantize Vectors env flag

- server/src/operators/model_operator.rs
- server/src/operators/user_operator.rs
> perf: remove reqwest client initaliziation

- dashboard/src/components/NewDatasetModal.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- dashboard/src/types/apiTypes.ts
- docker-compose.yml
- server/src/bin/ingestion-microservice.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: support for 3072 vectors

- server/migrations/2024-04-09-001819_add-metadata-and-tag-set-to-groups/down.sql
- server/migrations/2024-04-09-001819_add-metadata-and-tag-set-to-groups/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/search_operator.rs
> feature: group_metadata and group_tag_set for chunks

- server/src/operators/qdrant_operator.rs
- feature: add strategies to recommendations
- bugfix: qdrant best score strategy
> bugfix: best score strategy

- .vscode/launch.json
- convenience.sh
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/file_operator.rs
> bugfix: make group_tag_set work

- server/src/handlers/user_handler.rs
> doc: update openapi doc for api_key routes

- server/Cargo.lock
- server/Cargo.toml
- server/migrations/2024-04-11-052101_make-api-key-faster/down.sql
- server/migrations/2024-04-11-052101_make-api-key-faster/up.sql
- server/src/af_middleware/auth_middleware.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/message_handler.rs
- server/src/handlers/organization_handler.rs
- server/src/handlers/stripe_handler.rs
- server/src/handlers/topic_handler.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/organization_operator.rs
- server/src/operators/stripe_operator.rs
- server/src/operators/user_operator.rs
> feature: simply middleware and speed up api keys with blake3 hashing

- server/migrations/2024-04-11-062653_remove-org-name-constraint/down.sql
- server/migrations/2024-04-11-062653_remove-org-name-constraint/up.sql
- server/src/operators/organization_operator.rs
> cleanup: remove contstraint on org name uniqueness

- server/src/handlers/file_handler.rs
- server/src/lib.rs
> cleanup: remove file mime type

- search/src/components/UploadFile.tsx
> bugfix: remove file_mime_type from req in search frontend

- server/migrations/2024-04-11-072642_add-indexes-for-dataset/down.sql
- server/migrations/2024-04-11-072642_add-indexes-for-dataset/up.sql
- server/src/handlers/chunk_handler.rs
> speedup: add indexes to dataset and stripe sub

- server/Cargo.lock
- server/Cargo.toml
- server/src/handlers/auth_handler.rs
- server/src/lib.rs
- server/src/public/login.html
> feature: local login page

- .github/workflows/push-server.yml
> ops: seperate build caches for ocr and no-ocr

- server/src/handlers/file_handler.rs
- server/src/lib.rs
- server/src/operators/file_operator.rs
> feature: create chunks and groups with file tracking id

- server/Dockerfile.no-ocr
- server/Dockerfile.ocr
> bugfix: copy login.html into the docker build

- .github/workflows/chat-tests.yml
- .github/workflows/push-server.yml
- .github/workflows/rust-tests.yml
- .github/workflows/search-tests.yml
> feature: fix CI action from triggering docker push

- server/src/public/login.html
> feature: make local login more automatic

- .github/workflows/push-server.yml
> ops: change CI action name for file worker

- server/src/public/login.html
> feature: Auto Login from CLI

- server/src/bin/file-worker.rs
- server/src/bin/ingestion-worker.rs
- server/src/handlers/file_handler.rs
> feature: add thread num to workers

- server/src/handlers/file_handler.rs
> bugfix: fix tracing span

- server/src/lib.rs
> bugfix: fix sentry tracing

- server/src/bin/file-worker.rs
- server/src/operators/file_operator.rs
> feature: add errors for file upload

- server/migrations/2024-04-15-171749_tracking-id-for-datasets/down.sql
- server/migrations/2024-04-15-171749_tracking-id-for-datasets/up.sql
- server/src/af_middleware/auth_middleware.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/dataset_handler.rs
- server/src/lib.rs
- server/src/operators/dataset_operator.rs
> feature: dataset tracking id

- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/qdrant_operator.rs
> feature: full text recommendations

- .github/workflows/push-server.yml
- dashboard/src/pages/Dashboard/Dataset/DatasetEvents.tsx
- server/Cargo.toml
- server/Dockerfile.qdrant-worker
- server/src/bin/ingestion-worker.rs
- server/src/bin/qdrant-worker.rs
- server/src/data/models.rs
- server/src/handlers/event_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/qdrant_operator.rs
> feature: qdrant worker

- server/Cargo.lock
- server/Cargo.toml
- server/src/handlers/message_handler.rs
> feature: fixed bug in openai_dive to let openrouter be compatible for claude

- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- dashboard/src/types/apiTypes.ts
- search/src/components/ScoreChunk.tsx
- search/utils/apiTypes.ts
- server/src/data/models.rs
> feature: image metadata key

- .github/workflows/dashboard-tests.yml
> ops: dashboard CI actions

- search/src/components/ResultsPage.tsx
- search/src/components/SearchForm.tsx
- feature: re-run search query when mode changes
- feature: rerun search when group comes on + pagination for group search
> feature: rerun query when mode or group changes + add pagination controller to groups"

- monitoring_server/monitor.py
- monitoring_server/requirements.txt
- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/qdrant_operator.rs
> feature: pthon server with blocking route to see if tracking_ids exist

- server/src/bin/ingestion-worker.rs
> feature: sentry for ingest without manual instrumentation

- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
- bugfix: get suggested queries route + cleanup: remove model from request payload for messages
- cleanup: don't fetch extra fields for group recommendations on slim chunks
> cleanup: don't fetch extra fields for group recommendations when slim_chunks is true"

- server/src/af_middleware/auth_middleware.rs
- server/src/bin/file-worker.rs
- server/src/bin/ingestion-worker.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature/ops: sentry working for main server

- server/src/operators/model_operator.rs
> ops: sentry now adds embedding model and embedding server used

- .github/workflows/rust-tests.yml
> ops: cargo fmt action

- dashboard/src/components/MultiSelect.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetEvents.tsx
> feature: add new event types

- server/src/handlers/chunk_handler.rs
> feature: limit on bulk upload chunks

- dashboard/src/components/NewDatasetModal.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- dashboard/src/types/apiTypes.ts
- server/src/data/models.rs
> feature: add embedding query prefix to dashboard

- search/src/HomeSearch.tsx
- search/src/components/FilterModal.tsx
- search/src/components/GroupPage.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/SearchForm.tsx
- search/src/pages/Search.tsx
> feature: filters modal to handle allowing users to specify Qdrant filters

- .env.chat
- search/src/components/ChunkMetadataDisplay.tsx
- search/src/components/CreateNewDocChunkForm.tsx
- search/src/components/ScoreChunk.tsx
- search/utils/apiTypes.ts
- server/src/errors.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/organization_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/organization_operator.rs
- bugfix: search UI location display
- cleanup: properly return 404 responses for resource get routes
> cleanup: add 404 responses to proper routes

- server/src/operators/chunk_operator.rs
- server/src/operators/group_operator.rs
> visibility: remove extra 404 logs

- chat/src/components/ScoreChunk.tsx
- chat/src/utils/apiTypes.ts
- dashboard/src/components/OrganizationUsageOverview.tsx
- search/src/components/ChunkMetadataDisplay.tsx
- search/src/components/EditChunkPageForm.tsx
- search/src/components/ScoreChunk.tsx
- search/utils/apiTypes.ts
- server/migrations/2024-05-07-004631_tagset_to_array/down.sql
- server/migrations/2024-05-07-004631_tagset_to_array/up.sql
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: convert tag_set to an array

- search/src/components/ResultsPage.tsx
- server/src/lib.rs
> feature: make total chunk pages accurate

- server/migrations/2024-05-07-042417_remove-expiration-from-invitation/down.sql
- server/migrations/2024-05-07-042417_remove-expiration-from-invitation/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/operators/invitation_operator.rs
> feature: remove invitiation expiration

- server/src/handlers/message_handler.rs
> feature: better query generation using RAG

- dashboard/src/components/OrganizationUsageOverview.tsx
- search/src/components/Atoms/HomeNavbar.tsx
- search/src/components/Atoms/Navbar.tsx
- search/src/components/DatasetSelectBox.tsx
> feature: add dataset selector to search page

- docker-compose.yml
- search/src/HomeSearch.tsx
- search/src/components/Atoms/ConfirmModal.tsx
- search/src/components/BookmarkPopover.tsx
- search/src/components/EditChunkPageForm.tsx
- search/src/components/FilterModal.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/SearchForm.tsx
- search/src/components/ShowToasts.tsx
- search/src/layouts/HomeLayout.tsx
- search/src/layouts/SearchLayout.tsx
- server/Cargo.lock
- server/Cargo.toml
- server/src/bin/ingestion-worker.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
- feature: rev qdrant in docker-compose + cleanup: edit frontend component includes correct fields
- bugfix: group search pagination
- cleanup: UI fixes for filters such that they are easier to use
> bugfix: group search pagination, cleanup: UI for filters

- search/src/components/FilterModal.tsx
> bugfix: fix default values for the filter modal

- search/src/HomeSearch.tsx
- search/src/components/Atoms/HomeNavbar.tsx
- search/src/components/Atoms/Navbar.tsx
- search/src/components/DatasetSelectBox.tsx
- search/src/components/GroupPage.tsx
- search/src/components/OrganizationSelectBox.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/ScoreChunk.tsx
- search/src/components/ScoreChunkArray.tsx
- search/src/components/SearchForm.tsx
- search/src/components/UploadFile.tsx
- search/src/pages/Search.tsx
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/search_operator.rs
- feature: add options popover to search UI for all payload params
- bugfix: slim chunks no longer affect ranking
> feature: add options popover to SearchForm + bugfix: slim_chunks on hybrid search no longer affects ranking"

- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/search_operator.rs
> feature: able to tune date recency using req param

- server/src/bin/ingestion-worker.rs
- server/src/handlers/chunk_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
> bugfix: make chunk html optional again

- search/src/index.css
- server/src/operators/chunk_operator.rs
- server/src/operators/qdrant_operator.rs
> feature: highlighting improvements

- server/src/operators/chunk_operator.rs
> cleanup: remove log

- dashboard/src/types/apiTypes.ts
- server/src/lib.rs
- server/src/operators/model_operator.rs
> feature: jina-code support

- .github/workflows/push-frontends.yml
- .github/workflows/push-server.yml
> ops: tagged docker images

- search/src/components/ChunkMetadataDisplay.tsx
- search/src/components/Contexts/DatasetAndUserContext.tsx
- search/src/components/ScoreChunk.tsx
- search/src/components/SingleChunkPage.tsx
- search/utils/apiTypes.ts
> bugfix: fix related chunks, fix opening in new tab, fix history bug

- search/src/components/FilterModal.tsx
> feature: add filter field drop down

- server/src/operators/chunk_operator.rs
- server/src/operators/qdrant_operator.rs
> bugfix: increase timeouts on qdrant

- search/src/components/EditChunkPageForm.tsx
- search/src/components/FilterModal.tsx
- server/src/data/models.rs
- server/src/lib.rs
- server/src/operators/search_operator.rs
> feature: date range filters

- server/src/bin/ingestion-worker.rs
> enhancment: more retries on ingestion

- search/src/components/GroupPage.tsx
> bugfix: fix the way group name edit looks

- server/src/operators/qdrant_operator.rs
> remove index params

- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> bugfix: sort metadata for hybrid search

- server/src/operators/model_operator.rs
> bugfix: jina code embed and search with the correct env flag

- server/src/operators/search_operator.rs
> bugfix: fix group hybrid search ranking

- dashboard/src/components/NewDatasetModal.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
The dashboard UI was only displaying the chosen model based on the embeddingModel size. All the functionality was working odly enough though
> bugfix: dashboard frontend ui bug

- dashboard/src/pages/Dashboard/UserManagment.tsx
- server/src/af_middleware/auth_middleware.rs
- server/src/handlers/auth_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/organization_handler.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
- server/src/operators/organization_operator.rs
- server/src/operators/user_operator.rs
> feature: make users be seperate from the user_orgs

- server/src/data/models.rs
- server/src/operators/search_operator.rs
> bugfix: make must not filters work better

- server/src/data/models.rs
- server/src/handlers/group_handler.rs
- server/src/operators/group_operator.rs
- cleanup: update all deps
- bugfix: group update error
> bugfix: group update not using id issue

- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/search_operator.rs
> feature: made highlights max 5 words long, feature: highlight threshold

- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- dashboard/src/types/apiTypes.ts
- search/src/components/ScoreChunk.tsx
- search/utils/apiTypes.ts
- server/migrations/2024-05-16-173746_add-image-url-field/down.sql
- server/migrations/2024-05-16-173746_add-image-url-field/up.sql
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/search_operator.rs
> feature: image urls in pg

- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/search_operator.rs
> feature: add tag_weights as req param

- search/src/components/ResultsPage.tsx
- search/src/components/SearchForm.tsx
- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
- server/src/operators/search_operator.rs
> feature: autocomplete fulltext and semantic

- server/src/handlers/chunk_handler.rs
> docs: update chunk_metadata example json type

- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/search_operator.rs
> feature: add id filters

- search/src/components/Footer.tsx
> fix trieve github link

- .gitignore
- convenience.sh
- server/migrations/2024-05-17-172734_add-back-json-indexes/down.sql
- server/migrations/2024-05-17-172734_add-back-json-indexes/up.sql
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/search_operator.rs
> speedup: make metadata filtering faster

- .gitignore
- convenience.sh
- server/migrations/2024-05-17-172734_add-back-json-indexes/down.sql
- server/migrations/2024-05-17-172734_add-back-json-indexes/up.sql
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/search_operator.rs
> bugfix: remove tag_set

- server/src/data/models.rs
- server/src/operators/model_operator.rs
- server/src/operators/search_operator.rs
> feature: be able to specify a custom reranker

- embedding-server/main.py
- **feature: alternate solution for embeddings**
- **bugfix: make embedding server more openai compatible**
> bugfix: make backup server more openai compatible

- server/src/bin/ingestion-worker.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
> feature: add filter options to message creation

- search/src/components/GroupPage.tsx
- search/src/components/ResultsPage.tsx
- search/utils/apiTypes.ts
> feature: group recommendations UI

- chat/src/components/Layouts/MainLayout.tsx
> feat: multiple lines in chat with shift+enter

- search/src/components/GroupPage.tsx
> bugfix: fix group search

- chat/src/components/FilterModal.tsx
- chat/src/components/Layouts/MainLayout.tsx
- chat/src/index.css
> feat: filters for chat messages

- server/migrations/2024-05-23-184907_add-number-col/down.sql
- server/migrations/2024-05-23-184907_add-number-col/up.sql
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/search_operator.rs
> feature: add numeric column

- server/src/af_middleware/auth_middleware.rs
- server/src/handlers/organization_handler.rs
- server/src/lib.rs
- server/src/operators/user_operator.rs
> fix: confirm org membership in both header and params

- server/src/af_middleware/auth_middleware.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/stripe_handler.rs
- server/src/operators/invitation_operator.rs
> fix: verify organization ownership for datasets, files, invitations, stripe

- server/src/handlers/dataset_handler.rs
> fix: properly compare dataset header and path for deletion

- .env.docker-compose
- .env.example
- docker-compose.yml
- helm/charts/redis/values.yaml
- helm/templates/ingest-deployment.yaml
- helm/templates/server-deployment.yaml
- helm/values.yaml.tpl
- self-hosting.md
- terraform/aws/main.tf
- terraform/gcloud/main.tf
> docs: update self-hosting guide with docker-compose and gcp

- helm/charts/qdrant/values.yaml
- helm/templates/embeddings-deployment.yaml
- helm/templates/server-service.yaml
- terraform/aws/embedding.tf
- terraform/aws/main.tf
- terraform/gcloud/main.tf
> ops: add custom taint to qdrant nodes

- dashboard/src/components/PlansTable.tsx
> fix: remove extra 24/7 support checkmark

- search/src/components/CreateNewDocChunkForm.tsx
- search/src/components/EditChunkPageForm.tsx
- search/src/components/TinyEditor.tsx
- search/src/index.css
> fix: maintain tinymce between page navigation

- dashboard/src/types/apiTypes.ts
> bugfix: wrong embedding size for jina-code

- server/src/data/models.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
> feature: prefilter tag_set with pg

- .github/workflows/push-frontends.yml
- .github/workflows/push-server.yml
> feature: support arm64 docker images

- dashboard/src/components/Sidebar.tsx
Fixed target attribute on search and rag chat buttons to pop out in new tab.
> Search and RAG Chat buttons pop out in new tab.

- .github/workflows/push-frontends.yml
- .github/workflows/push-server.yml
> feature: remove arm images for OSX, docker builds take too long

- server/migrations/2024-06-06-042117_delete-chunk-metadata-tag-set/down.sql
- server/migrations/2024-06-06-042117_delete-chunk-metadata-tag-set/up.sql
- server/migrations/2024-06-11-022039_drop-dataset-tag-unique/down.sql
- server/migrations/2024-06-11-022039_drop-dataset-tag-unique/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/search_operator.rs
- **cleanup: remove verbose timings**
- **feature: TagSet Table creation**
- **wip: tagset logic**
> feature: tag_set logic

- server/migrations/2024-06-06-042117_delete-chunk-metadata-tag-set/down.sql
- server/migrations/2024-06-06-042117_delete-chunk-metadata-tag-set/up.sql
- server/migrations/2024-06-11-022039_drop-dataset-tag-unique/down.sql
- server/migrations/2024-06-11-022039_drop-dataset-tag-unique/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/search_operator.rs
Reverts devflowinc/trieve#1561
> Revert "feature: tag_set logic"

- dashboard/src/components/ApiKeyGenerateModal.tsx
- dashboard/src/components/BuildingSomething.tsx
- dashboard/src/components/CreateNewOrgModal.tsx
- dashboard/src/components/DatasetOverview.tsx
- dashboard/src/components/InviteUserModal.tsx
- dashboard/src/components/Navbar.tsx
- dashboard/src/components/NewDatasetModal.tsx
- dashboard/src/components/OrganizationUsageOverview.tsx
- dashboard/src/components/PlansTable.tsx
- dashboard/src/components/Sidebar.tsx
- dashboard/src/index.css
- dashboard/src/layouts/DashboardLayout.tsx
- dashboard/src/layouts/DatasetLayout.tsx
- dashboard/src/pages/Dashboard/Billing.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetEvents.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
- dashboard/src/pages/Dashboard/Overview.tsx
- dashboard/src/pages/Dashboard/Settings.tsx
- dashboard/src/pages/Dashboard/UserManagment.tsx
- dashboard/tailwind.config.cjs
- dashboard/vite.config.ts
> feature: various css fixups

- dashboard/yarn.lock
- search/src/HomeSearch.tsx
- search/src/components/GroupPage.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/SearchForm.tsx
- search/src/pages/Search.tsx
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/search_operator.rs
> bugfix: make hybrid score threshold work as expected

- server/src/handlers/dataset_handler.rs
- server/src/lib.rs
- server/src/operators/dataset_operator.rs
> bugfix: let users create datasets with old tracking ids after deleting old datasets

- dashboard/package.json
- dashboard/src/components/DatasetExampleModal.tsx
- dashboard/src/components/ShowToasts.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
- dashboard/yarn.lock
- search/src/HomeSearch.tsx
- search/src/components/GroupPage.tsx
- search/src/components/SearchForm.tsx
- search/src/pages/Search.tsx
- **feature: example dataset from the frontend**
- **bugfix: make sure state is restored on modal close**
https://github.com/devflowinc/trieve/assets/25559111/f8732cdb-232e-48d0-be39-790280db66b1
> feature: example dataset create in frontend

- dashboard/src/components/ApiKeyGenerateModal.tsx
- dashboard/src/components/ApiKeys.tsx
- dashboard/src/components/DatasetTabs.tsx
- dashboard/src/components/OrgTabs.tsx
- dashboard/src/index.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
- dashboard/src/pages/Dashboard/Overview.tsx
- dashboard/src/types/apiTypes.ts
- server/src/data/models.rs
- server/src/handlers/dataset_handler.rs
- server/src/handlers/user_handler.rs
- server/src/lib.rs
- server/src/operators/user_operator.rs
> feat: move api keys on the dashboard to new tab

- search/src/HomeSearch.tsx
- search/src/components/GroupPage.tsx
- search/src/components/ResultsPage.tsx
- search/src/components/SearchForm.tsx
- search/src/pages/Search.tsx
- server/Cargo.lock
- server/Cargo.toml
- server/src/data/models.rs
- server/src/errors.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/search_operator.rs
- **feature: add highlight context window**
- **bugfix: fix integer underflow**
- **bugfix: boundary issue with window**
- **wip: attempting to figure out highlights**
> feature: add support for highlight window

- dashboard/src/components/DatasetTabs.tsx
- dashboard/src/components/OrgTabs.tsx
- dashboard/src/contexts/DatasetContext.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
- server/migrations/2024-06-14-141224_soft-delete-organization/down.sql
- server/migrations/2024-06-14-141224_soft-delete-organization/up.sql
- server/src/bin/delete-worker.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/organization_handler.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/organization_operator.rs
- server/src/operators/user_operator.rs
> feature: soft delete organizations

- server/src/bin/delete-worker.rs
> bugfix: add back delete from redis when an org is deleted from pg

- server/src/operators/chunk_operator.rs
> bugfix: duplicate phrases causing nested <mark><b> tags in chunk_html

- server/src/data/models.rs
> feature: remove tagset prefilter

- server/src/operators/chunk_operator.rs
> bugifx: replace split_whitespace with split_inclusive

- server/Cargo.lock
- server/Cargo.toml
> bugfix: image build for ocr image with magick needs an earlier version

- server/src/data/models.rs
> bugfix: remove tag_set expect, instead just make it an empty list

- server/src/data/models.rs
> bugfix: remove all qdrant serialization unwraps

- dashboard/src/components/DatasetExampleModal.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
- server/src/handlers/dataset_handler.rs
- server/src/lib.rs
- server/src/operators/dataset_operator.rs
> feature: show chunk count on dataset start page

- dashboard/package.json
- dashboard/src/components/DatasetOverview.tsx
- dashboard/src/hooks/useDatasetPages.ts
- dashboard/src/pages/Dashboard/Overview.tsx
- dashboard/yarn.lock
- server/src/handlers/dataset_handler.rs
- server/src/lib.rs
- server/src/operators/dataset_operator.rs
> feature: dashboard dataset pagination

- dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
- dashboard/src/types/apiTypes.ts
- server/src/handlers/dataset_handler.rs
- server/src/operators/dataset_operator.rs
> feature: update dataset tracking id

- dashboard/src/components/DatasetOverview.tsx
- server/src/bin/delete-worker.rs
- server/src/handlers/dataset_handler.rs
- server/src/lib.rs
- server/src/operators/dataset_operator.rs
> feature: empty datasets

- chat/package.json
- chat/src/components/Atoms/AfMessage.tsx
- chat/src/components/ScoreChunk.tsx
- chat/src/utils/messageSizing.ts
- chat/yarn.lock
> feat: resizable width chat messages + min height for citations

- server/src/handlers/group_handler.rs
- server/src/operators/group_operator.rs
> cleanup: fix latency on groups for dataset query

- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
Added the `temperature`, `frequency_penalty`, `presence_penalty`, `stop_tokens` parameters to `generate_from_chunks` request.
> feature: add temperature, frequency_penalty, presence_penalty, stop_tokens to generate_from_chunks request

- dashboard/src/components/DatasetOverview.tsx
- dashboard/src/hooks/useDatasetPages.ts
> fix: fix "no datasets match search" when not searching

- .vscode/settings.json
> fix: vs code eslint

- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- search/src/components/CreateNewDocChunkForm.tsx
- search/src/components/EditChunkPageForm.tsx
- search/src/components/SearchForm.tsx
- search/src/components/UploadFile.tsx
> bugfix: number input

- dashboard/src/components/ApiKeyGenerateModal.tsx
- server/src/operators/search_operator.rs
> feature: make copy api key a button on dashboard

- server/src/operators/dataset_operator.rs
> feature: delete batch as env

- server/src/operators/model_operator.rs
> feature: parallelize cross encoder calls if page_size > 20

- search/src/components/ResultsPage.tsx
- search/src/components/SearchForm.tsx
- search/src/hooks/useSearch.ts
> feature: add group size to options

- search/src/components/ResultsPage.tsx
- search/src/components/SearchForm.tsx
- search/src/hooks/useSearch.ts
> feature: get total pages as false by default

- search/src/components/ScoreChunk.tsx
- search/src/components/SearchForm.tsx
- search/src/hooks/useSearch.ts
> bugfix: metadata values show up as [Object object]

- chat/src/components/Atoms/AfMessage.tsx
> fix: multi message chat

- analytics-site/package.json
- analytics-site/src/api/analytics.ts
- analytics-site/src/api/trends.ts
- analytics-site/src/components/PaginationButtons.tsx
- analytics-site/src/components/charts/HeadQueries.tsx
- analytics-site/src/components/charts/LowConfidenceQueries.tsx
- analytics-site/src/hooks/usePagination.ts
- analytics-site/src/pages/Home.tsx
- shared/types.ts
- yarn.lock
> feat: show head and unconfident queries 

- dashboard/src/components/DatasetOverview.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
> feature: add refresh button for chunk count

- dashboard/src/pages/Dashboard/Dataset/DatasetEvents.tsx
- server/src/bin/delete-worker.rs
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/event_operator.rs
> feat: clickhouse logs for delete queue

- .github/workflows/rust-tests.yml
- server/Cargo.toml
- server/src/bin/grupdate-worker.rs
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/handlers/group_handler.rs
- server/src/operators/group_operator.rs
- server/src/operators/qdrant_operator.rs
Still working on this, need help with the operator.
> feature: update grouped chunk tags

- server/src/af_middleware/auth_middleware.rs
> feat: more header formats for orgs, datasets, and api keys

- search/src/components/EditChunkPageForm.tsx
- search/src/components/SingleChunkPage.tsx
> feature: suggest to the user that the chunk may be in a different dataset

- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- dashboard/src/types/apiTypes.ts
- server/src/data/models.rs
- server/src/operators/qdrant_operator.rs
> feature: use exact: false and indexed_only: true with qdrant queries

- .github/workflows/push-clustering-script.yml
> ops: fix clustering-script Dockerfile

- server/Dockerfile.group-worker
> ops/bugfix: fix grupdate-worker Dockerfile

- search/src/components/OrgGroupPageView.tsx
- search/src/hooks/useDatasetServerConfig.ts
- search/src/utils/downloadFile.ts
- search/utils/apiTypes.ts
- server/src/bin/file-worker.rs
- server/src/handlers/file_handler.rs
- server/src/operators/file_operator.rs
- yarn.lock
Can't get the s3 link to work properly on local development. Need a look into that by someone who knows how that works.
> feat: download files on search website

- .github/workflows/push-server.yml
> ops: less server build actions, better cache control names

- .github/workflows/push-server.yml
> bugfix: fix invalid cache of Dockerfile builds

- .github/workflows/push-server.yml
- .github/workflows/rust-tests.yml
- helm/templates/pgworker-deployment.yaml
- helm/values.yaml.tpl
- server/Cargo.toml
- server/Dockerfile.pg-worker
- server/src/bin/ingestion-worker.rs
- server/src/bin/pg-worker.rs
- server/src/data/models.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/qdrant_operator.rs
> feature: pg bulk queue

- .github/workflows/analytics-tests.yml
- .github/workflows/chat-tests.yml
- .github/workflows/dashboard-tests.yml
- .github/workflows/push-frontends.yml
- .github/workflows/search-tests.yml
- analytics-site/.eslintignore
- analytics-site/package.json
- analytics-site/src/contexts/UserAuthContext.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetEvents.tsx
> feature: fix analytics CI and dataset events view

- server/Cargo.lock
- server/Cargo.toml
- server/src/handlers/metrics_handler.rs
- server/src/handlers/mod.rs
- server/src/lib.rs
- server/src/metrics/mod.rs
> feat: prometheus metrics endpoint

- server/src/bin/delete-worker.rs
- server/src/operators/dataset_operator.rs
> feature: add logging to delete worker

- .github/workflows/push-server.yml
- **bugfix: ignore arm for delete worker (CI is failing on this for some reason)**
> bugfix: fix deleteworker action

- analytics-site/.eslintrc.json
- analytics-site/src/api/analytics.ts
- analytics-site/src/components/charts/RpsGraph.tsx
- analytics-site/src/contexts/UserAuthContext.tsx
- analytics-site/src/pages/Home.tsx
- analytics-site/src/utils/formatDate.ts
- docker/clustering-script/get_clusters.py
- shared/types.ts
> bugfix: ensure that the correct search_type is being selected

- server/migrations/2024-07-02-205044_fix-total-chunk-count/down.sql
- server/migrations/2024-07-02-205044_fix-total-chunk-count/up.sql
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
> bugfix: make org chunk accurate

- server/src/handlers/chunk_handler.rs
- server/src/operators/message_operator.rs
> bugfix: log to clickhouse even if not streaming

- server/src/handlers/chunk_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/qdrant_operator.rs
> bugfix: block when deleting points from qdrant

- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/search_operator.rs
> cleanup: change location to location_bias

- analytics-site/src/api/analytics.ts
- analytics-site/src/components/charts/LowConfidenceQueries.tsx
- analytics-site/src/hooks/usePagination.ts
- server/src/handlers/analytics_handler.rs
- server/src/lib.rs
> feat: low confidence threshold on analytics

- search/src/components/CreateNewDocChunkForm.tsx
- search/src/components/EditChunkPageForm.tsx
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/model_operator.rs
- server/src/operators/search_operator.rs
slightly messy, I would just look at files changed
> feature: distance phrase

- dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- server/migrations/2024-07-03-200355_remove-collisions/down.sql
- server/migrations/2024-07-03-200355_remove-collisions/up.sql
- server/src/bin/ingestion-worker.rs
- server/src/bin/pg-worker.rs
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/file_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/qdrant_operator.rs
- server/src/operators/search_operator.rs
- shared/types.ts
> cleanup: remove collisions

- .github/workflows/push-server.yml
- .github/workflows/rust-tests.yml
- helm/templates/bulkingest-deployment.yaml
- helm/values.yaml.tpl
- server/Cargo.toml
- server/Dockerfile.bulk-ingest-worker
- server/src/bin/bulk-ingestion-worker.rs
> bugfix: move bulk pg_worker logic to seperate ingestion worker

- chat/src/components/contexts/UserContext.tsx
- dashboard/src/components/DatasetOverview.tsx
- dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
> feature: open search and RAG playground from dashboard

- server/src/handlers/metrics_handler.rs
> bugfix: metrics handler support for pgbulk queue, fix bearer auth bug

- analytics-site/src/components/charts/HeadQueries.tsx
- analytics-site/src/components/charts/LowConfidenceQueries.tsx
- analytics-site/src/components/charts/RagQueries.tsx
> styling: use tables for analytics site

- analytics-site/src/api/analytics.ts
- analytics-site/src/components/charts/NoResultQueries.tsx
- analytics-site/src/pages/Home.tsx
- server/src/handlers/analytics_handler.rs
- server/src/lib.rs
> feat: show queries with no results on analytics site

- server/src/bin/bulk-ingestion-worker.rs
- server/src/bin/delete-worker.rs
- server/src/bin/file-worker.rs
- server/src/bin/grupdate-worker.rs
- server/src/bin/ingestion-worker.rs
- server/src/bin/pg-worker.rs
- server/src/bin/sync-qdrant.rs
> enhancement: Lower DB load by reducing the number of connections per worker

- docker-compose.yml
fix: change KEYCLOAK_BASE_URL to KEYCLOAK_HOST. 
Caused a problem launching the application on self-hosting
> cleanup: update docker-compose.yml

- frontends/chat/src/components/Atoms/AfMessage.tsx
- frontends/yarn.lock
> bugfix: select and copy chat messages

- server/src/bin/delete-worker.rs
- server/src/bin/file-worker.rs
- server/src/bin/grupdate-worker.rs
- server/src/bin/ingestion-worker.rs
> feature: all worker failures go to dead letter queue

- .gitignore
- server/src/handlers/analytics_handler.rs
> feature: unique queries for each cluster

- .github/workflows/rust-tests.yml
> cicd: deny rust print statements

- frontends/analytics/src/components/trend-explorer/TrendExplorerCanvas.tsx
> feat: normalize cluster sizes on trend explorer

- .env.analytics
- .env.chat
- docker-compose.yml
- frontends/analytics/src/components/charts/LowConfidenceQueries.tsx
- frontends/analytics/src/pages/TrendExplorer.tsx
- frontends/shared/ui/FullscreenModal.tsx
- frontends/yarn.lock
Low confidence queries can now be opened in a new search window
> feature: link to search playground page for query

- server/Cargo.lock
- server/Cargo.toml
- server/src/bin/ingestion-worker.rs
- server/src/operators/qdrant_operator.rs
> feature: update to new qdrant client

- docker/clustering-script/get_clusters.py
- frontends/analytics/src/api/analytics.ts
- frontends/analytics/src/api/trends.ts
- frontends/analytics/src/utils/formatDate.ts
- frontends/shared/types.ts
- server/src/data/models.rs
- server/src/handlers/analytics_handler.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/analytics_operator.rs
- server/src/operators/clickhouse_operator.rs
- server/src/operators/mod.rs
- server/src/operators/search_operator.rs
> feature: recommendation analytics

- frontends/analytics/src/api/analytics.ts
> bugfix: fix head query request

- server/src/data/models.rs
> feature: apply name to the enum variants

- server/src/operators/analytics_operator.rs
> bugfix: make sure clustering query works with filters

- server/src/handlers/auth_handler.rs
> test: test auto merge

- docker/keycloak/themes/trieve/login/resources/css/styles.css
- docker/keycloak/themes/trieve/login/theme.properties
> styling: restyle keycloak login page

- server/Dockerfile.server
- server/ch_migrations/1720670538_add_centroids_to_clusters/down.sql
- server/ch_migrations/1720670538_add_centroids_to_clusters/up.sql
> bugfix: add clickhouse migrations to docker

- frontends/chat/src/components/Navbar/Navbar.tsx
- frontends/chat/src/components/Navbar/Sidebar.tsx
- frontends/chat/src/pages/chat.tsx
This PR allows users to edit topics in the chat UI's sidebar and navbar.
> feature: edit topics in chat UI

- .github/workflows/analytics-tests.yml
- .github/workflows/chat-tests.yml
- .github/workflows/dashboard-tests.yml
- .github/workflows/rust-tests.yml
- .github/workflows/search-tests.yml
> ops: bump actions/checkout to v4

- .gitignore
- server/src/bin/ingestion-worker.rs
- server/src/operators/model_operator.rs
> bugfix: empty string bug

- frontends/search/src/components/Atoms/Navbar.tsx
- frontends/search/src/components/BookmarkPopover.tsx
- frontends/search/src/components/GroupPage.tsx
- frontends/search/src/components/OrgGroupPageView.tsx
- server/src/handlers/message_handler.rs
- server/src/operators/group_operator.rs
- **bugfix: delete the group_id within Qdrant for relevant chunks when a group is deleted**
- **cleanup: properly keep track of dataset on links in navbar and org-groups and groups page**
> bugfix: delete the group_id within Qdrant for relevant chunks when a group is deleted

- frontends/dashboard/src/components/InviteUserModal.tsx
- frontends/dashboard/src/pages/Dashboard/UserManagment.tsx
Clears data input into `New User` form when closed.
> bugfix: clear `New User` modal content on close

- frontends/analytics/package.json
- frontends/analytics/src/components/FilterBar.tsx
- frontends/analytics/src/components/SimpleTimeRangeSelector.tsx
- frontends/analytics/src/components/charts/LatencyGraph.tsx
- frontends/analytics/src/components/charts/QueryCounts.tsx
- frontends/analytics/src/components/charts/RpsGraph.tsx
- frontends/analytics/src/types.d.ts
- frontends/analytics/src/utils/formatDate.ts
- frontends/shared/types.ts
- frontends/yarn.lock
> styling: sensible timestamp labels for analytics graphs

- server/migrations/2024-07-15-221313_scoped_api_keys/down.sql
- server/migrations/2024-07-15-221313_scoped_api_keys/up.sql
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/user_handler.rs
- server/src/middleware/auth_middleware.rs
- server/src/operators/user_operator.rs
> feature: scope api keys to certain routes

- server/src/middleware/auth_middleware.rs
> bugfix: ensure that api keys are actually elevated in perms

- frontends/analytics/src/api/analytics.ts
- frontends/analytics/src/components/charts/ChartCard.tsx
- frontends/analytics/src/components/charts/HeadQueries.tsx
- frontends/analytics/src/components/charts/LowConfidenceQueries.tsx
- frontends/analytics/src/components/charts/NoResultQueries.tsx
- frontends/analytics/src/components/charts/RagQueries.tsx
- frontends/analytics/src/components/charts/RagUsage.tsx
- frontends/analytics/src/pages/RagAnalyticsPage.tsx
- frontends/analytics/src/pages/SearchAnalyticsPage.tsx
- frontends/analytics/src/utils/formatDate.ts
- frontends/shared/types.ts
> feat: RAG analytics page

- frontends/search/src/index.css
> bugfix: ensure code tags dont go offscreen

- server/src/operators/organization_operator.rs
> bugfix: escape characters for server config

- server/src/operators/organization_operator.rs
> bugfix: dont remove `\`

- server/src/data/models.rs
> feat: hide qdrant point ids from responses

- frontends/analytics/src/components/charts/ChartCard.tsx
- frontends/analytics/src/components/charts/HeadQueries.tsx
- frontends/analytics/src/components/charts/LowConfidenceQueries.tsx
- frontends/analytics/src/components/charts/NoResultQueries.tsx
- frontends/analytics/src/components/charts/RagQueries.tsx
- frontends/analytics/src/components/charts/RagUsage.tsx
- frontends/analytics/src/pages/SearchAnalyticsPage.tsx
- frontends/search/src/components/Contexts/DatasetAndUserContext.tsx
- frontends/shared/package.json
- frontends/shared/tsconfig.json
- frontends/shared/ui/Table.tsx
- frontends/shared/ui/index.ts
- frontends/shared/utils/index.ts
- frontends/yarn.lock
> feat: redesign analytics tables with new component

- frontends/dashboard/src/components/DatasetOverview.tsx
- frontends/dashboard/src/contexts/DatasetContext.tsx
- frontends/dashboard/src/hooks/useDatasetPages.ts
- frontends/dashboard/src/index.tsx
- frontends/dashboard/src/pages/Dashboard/Overview.tsx
- frontends/shared/ui/Tooltip.tsx
… Clear) on the last column of the Datasets table in Dashboard > Overview
> feature: add titles or labels to the three buttons (Settings, Delete, Clear) on the last column of the Datasets table in Dashboard > Overview

- frontends/analytics/src/components/charts/LowConfidenceQueries.tsx
- frontends/analytics/src/components/charts/NoResultQueries.tsx
- frontends/shared/ui/FullscreenModal.tsx
- frontends/shared/ui/Table.tsx
> styling: make table clickability obvious

- frontends/analytics/src/layouts/TopBarLayout.tsx
> styling: fix sidebar height overflow

- server/src/bin/file-worker.rs
- server/src/middleware/auth_middleware.rs
- server/src/operators/dataset_operator.rs
> bugfix: require org ids when using dataset tracking ids in headers

- server/src/operators/qdrant_operator.rs
> bugfix: page is not taking effect for search_qdrant_query

- server/src/operators/chunk_operator.rs
> bugfix: don't panic if delete_chunks is true and no chunks in group

- frontends/analytics/src/components/FilterBar.tsx
- frontends/analytics/src/components/Sidebar.tsx
- frontends/analytics/src/pages/RagAnalyticsPage.tsx
- frontends/analytics/src/pages/SearchAnalyticsPage.tsx
- frontends/shared/package.json
- frontends/shared/tsconfig.json
- frontends/shared/ui/DateRangePicker.tsx
- frontends/shared/ui/datePickerStyles.css
- frontends/shared/ui/index.ts
- frontends/yarn.lock
> feat: date ranger picker for analytics

- .gitignore
- server/src/handlers/auth_handler.rs
> feature: print out keycloak error

- .gitignore
- server/src/lib.rs
> feature: remove compression

- .github/workflows/push-clustering-script.yml
- docker/collapse-query-script/collapse_queries.py
> ops: cleanup collapse query logs, add sha tag to clustering script

- .gitignore
- server/ch_migrations/1721754801_ctr_table/down.sql
- server/ch_migrations/1721754801_ctr_table/up.sql
- server/src/handlers/analytics_handler.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/analytics_operator.rs
- server/src/operators/search_operator.rs
> feature: add ability for users to submit CTR data

- frontends/search/src/components/ResultsPage.tsx
- frontends/search/src/components/SearchForm.tsx
- frontends/search/src/hooks/useSearch.ts
- server/src/data/models.rs
- server/src/operators/search_operator.rs
> feature: add prefetch query

- server/src/data/models.rs
- server/src/operators/search_operator.rs
> feature: update filters to have match_any and match_all

- frontends/dashboard/src/components/DatasetOverview.tsx
- frontends/dashboard/src/components/DatasetTabs.tsx
- frontends/dashboard/src/components/OrgTabs.tsx
- frontends/dashboard/src/components/PlansTable.tsx
- frontends/dashboard/src/contexts/UserContext.tsx
- frontends/dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- frontends/shared/types.ts
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/message_operator.rs
> feature: specify llm api key in dataset config

- .gitignore
- server/src/data/models.rs
- server/src/operators/chunk_operator.rs
> bugfix: remove all references of dataset config from ingestion message

- server/src/handlers/analytics_handler.rs
- server/src/operators/analytics_operator.rs
> cleanup: mispelling request_id

- frontends/dashboard/src/contexts/UserContext.tsx
- frontends/dashboard/src/layouts/DashboardLayout.tsx
Tested for - 
1. User has logged out and tries to open the page: redirects back to keycloak (no changes necessary)
2. User is logged in and opens page: spinner (enhancement)
3. User does not have required role: You do not have access screen (no change)
> enhancement: loading spinner for login

- server/src/operators/analytics_operator.rs
> bugfix: fix ctr filters

- server/src/operators/qdrant_operator.rs
> bugfix: fix score threshold

- server/src/data/models.rs
> bugfix: change naming of recommendation type

- frontends/dashboard/src/contexts/UserContext.tsx
> feature: show loading spinner while loading auth state

- frontends/dashboard/src/components/Sidebar.tsx
- frontends/dashboard/src/contexts/UserContext.tsx
- frontends/dashboard/src/index.tsx
- frontends/search/src/components/SearchForm.tsx
> feature: prevent flashing when switching orgs

- frontends/dashboard/src/components/Sidebar.tsx
- frontends/dashboard/src/pages/Home.tsx
> feature: link to groups, create chunk, upload file page from dashboard

- frontends/dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- frontends/dashboard/src/pages/Dashboard/Settings.tsx
> enhancement: cleanup dataset settings dashboard

- frontends/search/src/components/CreateNewDocChunkForm.tsx
- frontends/search/src/components/EditChunkPageForm.tsx
- server/src/bin/ingestion-worker.rs
- server/src/handlers/chunk_handler.rs
> cleanup: change boosts in search playground

- frontends/search/src/components/CreateNewDocChunkForm.tsx
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/model_operator.rs
> feature: specify alternate text to use for embedding

- helm/charts/postgresql/values.yaml
- helm/charts/qdrant/values.yaml
- helm/charts/redis/values.yaml
- helm/local-values.yaml
- helm/templates/analytics-deployment.yaml
- helm/templates/analytics-service.yaml
- helm/templates/chat-service.yaml
- helm/templates/dashboard-deployment.yaml
- helm/templates/dashboard-service.yaml
- helm/templates/deleteworker-deployment.yaml
- helm/templates/embeddings-deployment.yaml
- helm/templates/embeddings-service.yaml
- helm/templates/fileworker-deployment.yaml
- helm/templates/groupworker-deployment.yaml
- helm/templates/ingest-deployment.yaml
- helm/templates/ingress-aws.yaml
- helm/templates/ingress-gcloud.yaml
- helm/templates/ingress-local.yaml
- helm/templates/keycloak.yaml
- helm/templates/search-deployment.yaml
- helm/templates/search-service.yaml
- helm/templates/server-deployment.yaml
- helm/templates/server-service.yaml
- helm/templates/syncqdrant-deployment.yaml
- helm/templates/tika-deployment.yaml
- helm/templates/tika-service.yaml
- scripts/kind-with-registry.sh
- scripts/pull-and-push.sh
- self-hosting.md
Guide to deploy is mostly finished, tried to reproduce steps on differnet machine and got a 503 from the ingress controller, aside from that it is mostly finishedfrom the ingress controller, aside from that it is mostly finished
> feature: local kubernetes guide

- frontends/analytics/src/pages/TrendExplorer.tsx
> feat: add WIP info box for trend explorer

- frontends/analytics/src/components/charts/HeadQueries.tsx
- frontends/analytics/src/components/charts/LowConfidenceQueries.tsx
- frontends/analytics/src/components/charts/NoResultQueries.tsx
> styling: add icons to indicate clickable rows in analytics

- frontends/dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- frontends/shared/types.ts
- server/src/data/models.rs
- server/src/data/schema.rs
- server/src/handlers/dataset_handler.rs
- server/src/lib.rs
- server/src/operators/dataset_operator.rs
> feature: validate dataset configs

- frontends/shared/ui/SelectBox.tsx
> bugfix: fix the analytics dataset dropdown

- frontends/analytics/src/layouts/TopBarLayout.tsx
- frontends/analytics/src/pages/OverviewPage.tsx
- frontends/analytics/src/pages/RagAnalyticsPage.tsx
- frontends/analytics/src/pages/SearchAnalyticsPage.tsx
- frontends/analytics/src/pages/TrendExplorer.tsx
> styling: fix styling inconsistencies

- frontends/shared/ui/Tooltip.tsx
> enhancement: change tool tip color to soft-yellow

- frontends/dashboard/src/components/CreateNewOrgModal.tsx
> enhancement: reword create new organization modal description

- .github/ISSUE_TEMPLATE/issue-template.md
- CONTRIBUTING.md
- README.md
- frontends/analytics/src/components/Sidebar.tsx
- frontends/chat/src/components/Navbar/Navbar.tsx
- frontends/chat/src/pages/chat.tsx
- frontends/dashboard/src/components/BuildingSomething.tsx
- frontends/dashboard/src/components/InvoicesTable.tsx
- frontends/dashboard/src/components/Navbar.tsx
- frontends/dashboard/src/components/Sidebar.tsx
- frontends/dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- frontends/search/src/components/Contexts/DatasetAndUserContext.tsx
- frontends/search/src/components/Footer.tsx
- frontends/search/src/components/ImageModal.tsx
- frontends/search/src/components/UploadFile.tsx
- frontends/shared/ui/DateRangePicker.tsx
- **cleanup: update matrix room links**
- **cleanup: remove frontend console logs**
> cleanup: matrix room social links and errant console logs

- frontends/dashboard/src/components/DatasetOverview.tsx
- frontends/dashboard/src/components/Sidebar.tsx
- frontends/dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
- frontends/search/src/components/Atoms/Navbar.tsx
- frontends/search/src/components/UploadFile.tsx
- frontends/search/src/pages/Upload.tsx
> feature: upload multiple files or an entire folder on search playground

- server/src/bin/delete-worker.rs
- server/src/bin/file-worker.rs
- server/src/bin/grupdate-worker.rs
- server/src/bin/ingestion-worker.rs
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/analytics_operator.rs
- server/src/operators/clickhouse_operator.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/event_operator.rs
- server/src/operators/file_operator.rs
- server/src/operators/message_operator.rs
> feature: clickhouse service to batch events

- frontends/search/src/components/ResultsPage.tsx
- frontends/search/src/components/SearchForm.tsx
- frontends/search/src/hooks/useSearch.ts
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/message_handler.rs
- server/src/lib.rs
- server/src/operators/group_operator.rs
- server/src/operators/message_operator.rs
- server/src/operators/search_operator.rs
> feature: add multi query with weight to semantic search

- server/src/lib.rs
- server/src/operators/analytics_operator.rs
- server/src/operators/stripe_operator.rs
> bugfix: add back clickhouse client to app data

- frontends/analytics/src/contexts/OrgContext.tsx
> bugfix: go to right org after clicking the link in dashboard

- frontends/dashboard/index.html
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
> feature: mintlify widget, bugfix: better error on recommendations

- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/group_operator.rs
> bugfix: fix group delete

- frontends/analytics/src/api/tables.ts
- frontends/analytics/src/components/FilterBar.tsx
- frontends/analytics/src/components/PaginationButtons.tsx
- frontends/analytics/src/components/Sidebar.tsx
- frontends/analytics/src/components/charts/LatencyGraph.tsx
- frontends/analytics/src/components/charts/RAGUsageGraph.tsx
- frontends/analytics/src/components/charts/SearchUsageGraph.tsx
- frontends/analytics/src/index.tsx
- frontends/analytics/src/layouts/DataExplorerTabs.tsx
- frontends/analytics/src/pages/SearchAnalyticsPage.tsx
- frontends/analytics/src/pages/TrendExplorer.tsx
- frontends/analytics/src/pages/tablePages/RAGTablePage.tsx
- frontends/analytics/src/pages/tablePages/SearchTablePage.tsx
- frontends/analytics/src/utils/formatDate.ts
- frontends/shared/types.ts
- frontends/shared/ui/Table.tsx
- server/src/data/models.rs
- server/src/operators/clickhouse_operator.rs
> feature: analytics search table page

- server/src/operators/qdrant_operator.rs
> bugfix: fix score threshold error on qdrant

- server/ch_migrations/1722983788_remove_table_ttl/down.sql
- server/ch_migrations/1722983788_remove_table_ttl/up.sql
> feature: remove ttls for clickhouse table

- server/src/operators/clickhouse_operator.rs
> bugfix: incrementally commit search_queries

- server/src/bin/sync-qdrant.rs
- server/src/operators/chunk_operator.rs
> feature: add datasets its deleting from in sync script

- frontends/analytics/src/api/ctr.ts
- frontends/analytics/src/components/CTRInfoPanel.tsx
- frontends/analytics/src/components/charts/CTRSummary.tsx
- frontends/analytics/src/components/charts/QueryCounts.tsx
- frontends/analytics/src/hooks/useCTRNeedsSetup.ts
- frontends/analytics/src/pages/OverviewPage.tsx
> feat: move ctr summary and show banner when not setup

- frontends/dashboard/src/components/NewDatasetModal.tsx
- frontends/dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
- frontends/shared/types.ts
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/dataset_handler.rs
- server/src/lib.rs
- server/src/operators/chunk_operator.rs
- server/src/operators/dataset_operator.rs
- server/src/operators/group_operator.rs
- server/src/operators/qdrant_operator.rs
Add support for dot product, manhattan distance, and euclidean distance metrics as a new dataset setting
> feature: support more distance metrics

- docker/collapse-query-script/collapse_queries.py
- server/ch_migrations/1720668303_create_inital_tables/up.sql
- server/ch_migrations/1721414235_last_row_processed_for_collapse/up.sql
> cleanup: use replacing merge table

- frontends/dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
> feature: add clear dataset option to dataset settings page

- frontends/dashboard/src/components/Sidebar.tsx
> cleanup: fix sidebar overlap

- server/Cargo.lock
- server/Cargo.toml
- server/src/data/models.rs
- server/src/errors.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/message_handler.rs
- server/src/middleware/api_version.rs
- server/src/operators/message_operator.rs
> revert: revert all cargo dependencies

- server/src/operators/qdrant_operator.rs
> bugfix: update prefetch default for order by

- server/src/handlers/chunk_handler.rs
- server/src/operators/chunk_operator.rs
> feature: add quote negated words to count

- server/src/operators/chunk_operator.rs
- server/src/operators/search_operator.rs
> feat: debuggin memory leak in highlights code, adding a flag to never inline

- server/Cargo.toml
- server/src/operators/chunk_operator.rs
- server/src/operators/search_operator.rs
Added timing headers for highlight_chunks to measure perf on it (It was being bundled with the postgres span before).  and reverted the debug pr where we set debug = true.
The error seemed to be an underflow https://github.com/devflowinc/trieve/pull/2164/files#diff-bb28a6086cdf7de374c3cbf10a5271656a933be64adc38cfcfe414148b213ff1R1445-R1448 here
> bugfix: usize underfloat memory error, add timings to highlight_chunks

- docker/clustering-script/get_clusters.py
> cleanup: ensure clustering doesnt run on small datasets

- frontends/dashboard/src/layouts/DashboardLayout.tsx
- frontends/dashboard/src/layouts/DatasetLayout.tsx
> styling: fix dashboard sidebar overflow

- frontends/search/src/components/ResultsPage.tsx
- frontends/search/src/components/SearchForm.tsx
> bugfix: fix rerank query not persisting

- frontends/dashboard/src/components/Navbar.tsx
- frontends/dashboard/src/pages/Dashboard/Dataset/DatasetStart.tsx
- frontends/dashboard/src/pages/Dashboard/Overview.tsx
> feat: add consistent link to docs in dashboard

- frontends/search/src/components/ResultsPage.tsx
- frontends/search/src/components/ServerTimings.tsx
> feat: show server timings on search website

- clients/fetch-client/openapi.json
- clients/fetch-client/scripts/genClient.js
- clients/fetch-client/src/types.gen.ts
> fix: fix fetch client build script

- frontends/analytics/package.json
- frontends/analytics/src/api/analytics.ts
- frontends/analytics/src/components/SingleQueryInfo.tsx
- frontends/analytics/src/index.tsx
- frontends/analytics/src/layouts/DataExplorerTabs.tsx
- frontends/analytics/src/pages/SingleQueryPage.tsx
- frontends/analytics/src/pages/tablePages/SearchTablePage.tsx
- frontends/shared/types.ts
- frontends/shared/ui/FullscreenModal.tsx
- frontends/shared/ui/JSONMetadata.tsx
- frontends/shared/ui/index.ts
- yarn.lock
> feature: individal query view for analytics

- README.md
- self-hosting.md
> docs: improve self hosting guide for gcp

- server/ch_migrations/1723680843_add_user_ids/down.sql
- server/ch_migrations/1723680843_add_user_ids/up.sql
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/handlers/message_handler.rs
- server/src/operators/message_operator.rs
> feature: pass in user ids to identify distinct users

- server/src/data/models.rs
- server/src/operators/analytics_operator.rs
> feature: get rate of no clicks

- server/Cargo.lock
- server/Cargo.toml
> bugfix: bump chm to fix new line issue

- server/src/operators/qdrant_operator.rs
- **cleanup: add capture to failed to delete so we can debug**
- **cleanup: do nothing with Qdrant points delete if there are no points**
> cleanup: do nothing in delete qdrant points if there are no ids

- frontends/dashboard/src/components/Routes.ts
- server/src/handlers/analytics_handler.rs
This PR fixes the endpoint showed in the docs for the `get_recommendation_analytics` endpoint
> Fix docs for recommendation analytics

- server/src/operators/chunk_operator.rs
Use a hashmap at the begining of the request and make any groups and great the groups at the top of the batch.
> feature: use hashmap to limit rtt on reqeusts to get group tracking ids

- docker-compose.yml
- server/Cargo.lock
- server/Cargo.toml
> bugfix: make sure that empty queries dont get run

- clients/ts-sdk/package.json
- clients/ts-sdk/typedoc.json
> feat: various client fixes

- frontends/analytics/src/components/QueryStringDisplay.tsx
- frontends/analytics/src/components/SingleQueryInfo.tsx
- frontends/analytics/src/components/charts/HeadQueries.tsx
- frontends/analytics/src/components/charts/LowConfidenceQueries.tsx
- frontends/analytics/src/components/charts/NoResultQueries.tsx
- frontends/analytics/src/pages/TrendExplorer.tsx
- frontends/analytics/src/pages/tablePages/SearchTablePage.tsx
- yarn.lock
> feat: analytics multiquery display component

- server/src/handlers/message_handler.rs
> chore: update message_handler.rs

- server/src/data/models.rs
- server/src/handlers/analytics_handler.rs
- server/src/lib.rs
- server/src/operators/analytics_operator.rs
- server/src/operators/message_operator.rs
> feature: get top datasets from CH

- server/src/handlers/dataset_handler.rs
> observability: added clear_dataset transaction to sentry

- server/ch_migrations/1724365354_create_events_table/down.sql
- server/ch_migrations/1724365354_create_events_table/up.sql
- server/src/data/models.rs
- server/src/handlers/analytics_handler.rs
- server/src/lib.rs
- server/src/operators/analytics_operator.rs
> feature: generic events api

- frontends/search/src/components/SearchForm.tsx
> feat: group options in search playground

- frontends/dashboard/src/components/CreateNewOrgModal.tsx
- frontends/dashboard/src/contexts/UserContext.tsx
> fix: avoid infinite loop in usercontext

- .github/workflows/rust-tests.yml
- clients/ts-sdk/package.json
- frontends/analytics/package.json
- frontends/chat/package.json
- frontends/dashboard/package.json
- frontends/search/package.json
- package.json
- turbo.json
> feat: add typecheck scripts

- frontends/dashboard/src/components/DatasetOverview.tsx
- yarn.lock
> feature: copy dataset-id to clipboard

- clients/ts-sdk/package.json
- clients/ts-sdk/src/index.ts
- Extracts all types
- Bumps version
> cleanup: export types in SDK package

- frontends/search/src/components/ResultsPage.tsx
- frontends/search/src/components/SearchForm.tsx
- frontends/search/src/hooks/useSearch.ts
- server/src/data/models.rs
- server/src/handlers/chunk_handler.rs
- server/src/handlers/group_handler.rs
- server/src/lib.rs
- server/src/operators/model_operator.rs
- server/src/operators/search_operator.rs
- **feature: add scoring options req param to search chunks route**
- **feature: add scoring_options into the options popover on the search playground**
> feature: add req param for boosts on chunk/search route"

- frontends/search/src/components/ServerTimings.tsx
> styling: light mode server timings

- frontends/search/src/components/ChunkMetadataDisplay.tsx
- frontends/search/src/components/ScoreChunk.tsx
> fix: hide open recs icon when already viewing recs

- .github/workflows/workflow-release.yml
> ops: version release CI action

- README.md
Adds the missing env and fixes paths
> fix getting started docs

- README.md
Fixes windows
Adds rust for linux/mac
Adds link to tmux config
> bugfix: improve start services and add tmuxp to README local Dev guide

- release-please-config.json
> ci: add more commit flags to release please

- frontends/chat/src/pages/chat.tsx
- frontends/chat/src/pages/no-datasets-warning.tsx
> fix: no datasets warning for chat

- frontends/chat/src/pages/chat.tsx
> fix: dataset warning display for chat

- .github/workflows/release.yaml
- release-please-config.json
> ci: release-please to use proper token

- .github/workflows/release.yaml
- **ci: add version.txt for release-please**
- **ci: remove release-type from CI action**
- **ci: remove release-please token**
> ci: remove token from release-please action

- clients/search-component/README.md
- clients/search-component/package.json
- clients/search-component/src/TrieveModal/SearchMode.tsx
- clients/search-component/src/TrieveModal/icons.tsx
- clients/search-component/src/TrieveModal/index.css
- clients/search-component/src/TrieveModal/index.tsx
- clients/search-component/src/TrieveModal/item.tsx
- clients/search-component/src/utils/trieve.ts
- clients/search-component/tailwind.config.js
- yarn.lock
> fix: assorted fixes on component from signoz feedback

- frontends/chat/src/components/Atoms/AfMessage.tsx
- frontends/chat/src/components/ScoreChunk.tsx
> feature: add copy button to chat

- README.md
> content: update the README with more up to date information

- server/src/data/models.rs
- server/src/lib.rs
> fix: add get invitations to openapi spec

- server/src/handlers/group_handler.rs
- server/src/handlers/invitation_handler.rs
- server/src/handlers/stripe_handler.rs
- server/src/lib.rs
> fix: add delete invitation to openapi spec

- frontends/analytics/src/components/Sidebar.tsx
- frontends/search/src/components/Atoms/Navbar.tsx
> bugfix: links to dashboard from search and analytics SPA's post dash rewrite

- package.json
> fix: remove old-dashboard from monorepo

- .github/workflows/push-server.yml
- server/Dockerfile.crawl-cron-job
> bugfix: fix crawl worker docker push action

- .env.docker-compose
- server/src/operators/crawl_operator.rs
> feature: replace all https to http

- frontends/dashboard/src/api/createDataset.ts
- frontends/dashboard/src/components/NewDatasetModal.tsx
- frontends/dashboard/src/components/Sidebar.tsx
- frontends/shared/types.ts
- frontends/shared/ui/FullscreenModal.tsx
- server/src/bin/crawl-worker.rs
- server/src/data/models.rs
- server/src/lib.rs
- **cleanup: add tooltips and advanced options toggle to create dataset modal for ease of use**
- **feature: add scraping config as an option to setup when creating a dataset**
- **cleanup: apply light edits to scraper config for better defaults and link tracking plus empty chunk avoidance**
> feature: add scraping options to create dataset modal in dashboard

- frontends/dashboard/src/components/CopyButton.tsx
- frontends/dashboard/src/components/DatasetOverview.tsx
- frontends/dashboard/src/components/OrgName.tsx
- frontends/dashboard/src/pages/dataset/DatasetHomepage.tsx
- frontends/shared/ui/TanStackTable.tsx
> feature: copy ids in dashboards

- frontends/dashboard/src/components/DatasetOverview.tsx
- frontends/dashboard/src/components/MultiSelect.tsx
- frontends/dashboard/src/components/NewDatasetModal.tsx
- frontends/dashboard/src/components/Sidebar.tsx
- frontends/dashboard/src/layouts/NavbarDatasetSelector.tsx
- frontends/dashboard/src/layouts/NavbarLayout.tsx
- frontends/dashboard/src/layouts/NavbarOrganizationSelector.tsx
- frontends/dashboard/src/layouts/OrganizationLayout.tsx
> feature: refactor org selector and dataset selector display

- frontends/dashboard/src/components/NewDatasetModal.tsx
- frontends/dashboard/src/components/Sidebar.tsx
- frontends/dashboard/src/contexts/DatasetContext.tsx
- frontends/dashboard/src/index.tsx
- frontends/dashboard/src/layouts/NavbarOrganizationSelector.tsx
- frontends/dashboard/src/pages/dataset/DatasetHomepage.tsx
> cleanup: various dashboard improvements like dataset selector bugfixes and better text in create dataset modal for info

- frontends/dashboard/src/contexts/DatasetContext.tsx
> bugfix: find not a function for dataset memo

- frontends/dashboard/src/layouts/NavbarDatasetSelector.tsx
> bugfix: map not existing in NavbarDatasetSelector

- server/src/handlers/analytics_handler.rs
- server/src/operators/analytics_operator.rs
> bugfix: scope top datasets to organization

- README.md
- clients/ts-sdk/openapi.json
- clients/ts-sdk/src/types.gen.ts
- frontends/dashboard/src/components/DatasetOverview.tsx
- frontends/dashboard/src/components/OnboardingSteps.tsx
- server/src/handlers/analytics_handler.rs
- server/src/lib.rs
> feature: add onboarding checklist to dashboard

- frontends/dashboard/src/api/trieve.ts
> fix: more specific /api replacement on environment variable

- frontends/dashboard/src/layouts/NavbarDatasetSelector.tsx
- frontends/dashboard/src/layouts/NavbarOrganizationSelector.tsx
- frontends/shared/ui/SelectBox.tsx
> feat: fix org and dataset search

- frontends/dashboard/src/pages/orgs/OrgUserPage.tsx
> fix: working invite user modal

- clients/ts-sdk/package.json
- clients/ts-sdk/src/functions/chunks/index.ts
Updates the function for the autcomplete to use the V2
> fix: default autocomplete function to api version V2

- .env.docker-compose
- clients/search-component/package.json
- clients/ts-sdk/openapi.json
- clients/ts-sdk/package.json
- clients/ts-sdk/src/types.gen.ts
- frontends/dashboard/src/components/NewDatasetModal.tsx
- server/src/bin/crawl-worker.rs
- **cleanup: scraping trailing slashes + update: boost titles option in newdataset modal**
> cleanup: scraping trailing slashes
