Cargo.lock, Cargo.toml
Reverted because arguflow/vault is not yet ready for this.
=> Revert "117 optimize feature list async stripe to the minimum set"

search/src/components/BookmarkPopover.tsx, search/src/components/CollectionPage.tsx, search/src/components/CommunityBookmarkPopover.tsx, search/src/components/UserCardDisplay.tsx
- issue https://github.com/arguflow/arguflow/issues/560
- Rename collections to themes in UI for search
<br>
<br>
<br>
- BookmarkPopover.tsx (search/src/components/BookmarkPopover.tsx)
- CollectionPage.tsx (search/src/components/CollectionPage.tsx)
- CommunityBookmarkPopover.tsx (search/src/components/CommunityBookmarkPopover.tsx)
- UserCardDisplay.tsx (search/src/components/UserCardDisplay.tsx)
<br>
- @skeptrunedev
=> cleanup: rename collections to themes in UI

search/src/layouts/HomeLayout.astro, search/src/layouts/SearchLayout.astro
This PR updates the styling to ensure the scroll bar appears in dark colors when in dark mode.
Fixes: #544 
@skeptrunedev
Please review this PR for the styling related to scroll bar appearance. Your feedback is highly appreciated.
=> styling: make the scroll bar in dark mode be dark colors

docker-compose.yml
PR related to a docker update to allow inter-container links.  @densumesh 
In the future we can remove the port definitions from the docker images for the database, qdrant, etc.... they can be accessed via the link functionality.
=> feature: update docker-compose.yml with hardcoded container names

server/src/data/models.rs, server/src/handlers/chunk_handler.rs, server/src/handlers/collection_handler.rs, server/src/handlers/dataset_handler.rs, server/src/handlers/stripe_handler.rs, server/src/lib.rs
this makes it possible to generate a SDK for the API in python I think
attached the JSON gen of the spec at this stage
[openapi-v12.json](https://github.com/arguflow/arguflow/files/13996106/openapi-v12.json)
=> bugfix: gen'ed openAPI spec now works with openapi-python-client

docker-compose.yml, server/Cargo.toml, server/Dockerfile.no-ocr, server/Dockerfile.ocr, server/server-python/requirements.txt
Dockerfile.no-ocr is halved in size at 228MB and caches properly using
rust:1.75 instead of rust-nightly, hopefully will reduce the amount of full
builds
=> feature: super slim dockerfile

embedding-server/embeddings.py
The new model returns the wrong ndarray of float32's casted to floats and list
=> feature: cast result from embedding server

server/src/operators/search_operator.rs
=> bugfix: only use first result of group for cross-encoder

dashboard/Dockerfile, dashboard/package.json, dashboard/vite.config.ts, dashboard/yarn.lock
Add dashboard nginx container with runtime variable setting docker-entrypoint.
Add vite runtime env configuration plugin[vite-plugin-runtime-env](https://www.npmjs.com/package/vite-plugin-environment)
This allows us to do variable substitution in the index.html at runtime.
=> Dashboard Container

server/src/bin/ingestion-microservice.rs, server/src/data/models.rs, server/src/errors.rs, server/src/handlers/chunk_handler.rs, server/src/operators/chunk_operator.rs, server/src/operators/qdrant_operator.rs
Attempts at making the queue implementation more reliable. 
Main changes:
- Use blpoprpush to put chunks into a processing queue
- Remove chunks from processing queue after processing is completed
- If a chunk remains in the queue for a long time, that ingestion service died, and needs to be restarted
- Implement a retry mechanism 3 times
This only works for `create_chunk` 
- if the `upsert_by_tracking_id` is marked as true. It won't revert the write to pg if qdrant errors.
=> faeture: attempts at more reliable queue

server/src/operators/qdrant_operator.rs
Somewhat similar to https://github.com/devflowinc/trieve/pull/1185 but this time allowing for a group_size of 0 so that no content is returned also
=> feature: allow for group_size to be 0 for group_search and group reccomendations

dashboard/src/components/NewDatasetModal.tsx, dashboard/src/types/apiTypes.ts
- **feature: support for 3072 vectors**
- **bugfix: set embedding model name**
=> bugfix: set EMBEDDING_MODEL_NAME

server/migrations/2024-04-11-074046_add-indexes-for-api-key/down.sql, server/migrations/2024-04-11-074046_add-indexes-for-api-key/up.sql, server/src/af_middleware/auth_middleware.rs, server/src/operators/organization_operator.rs
=> speedup: add indexes on api key hash

.github/workflows/chat-tests.yml, .github/workflows/push-server.yml
- **feature: fix CI action from triggering docker push**
- **ops: set buildcache to a dedicated buildcache repo, make the Dockerhub look cleaner**
=> ops: set buildcache to a dedicated buildcache repo, make the Dockerhub look cleaner

.env.server
=> fix: remove SENTRY_URL from .env.server

.env.server, server/src/operators/model_operator.rs
JINA_CODE does not work in text embedding inference https://github.com/huggingface/text-embeddings-inference/issues/270 and the previous embedding server PR does not scale #1487. Just going to use JINA_CLOUD internally.
=> feature: support for custom JINA_CODE_API_KEY

docker-compose.yml
RUST_LOG has been added to the docker-compose.yml file, because without it the variable only works when the server is hosted on a local machine outside the docker
@skeptrunedev 
#1551
=> RUST_LOG has been added to the docker-compose.yml file

server/src/errors.rs, server/src/handlers/chunk_handler.rs, server/src/lib.rs
Improves the error message for JSON payload deserialization. 
Updated format for the JSON deserialization error message: 
`"{message":"Json deserialization error: *Type* : Data error in JSON | *Message* : Json deserialize error: data did not match any variant of untagged enum CreateChunkReqPayloadEnum | Ensure that the data in the JSON payload is valid and consistent with the expected schema."}`
=> feature: improved JSON deserialization error message output

search/src/components/SearchForm.tsx
Clicking on an input or button no longer closes the filters modal.
=> bugfix: filter modal closing when clicking on a non-interactive element

chat/src/components/ScoreChunk.tsx, chat/src/utils/apiTypes.ts, search/src/components/ChunkMetadataDisplay.tsx, search/src/components/CreateNewDocChunkForm.tsx, search/src/components/EditChunkPageForm.tsx, search/src/components/FilterModal.tsx, search/src/components/ScoreChunk.tsx, search/utils/apiTypes.ts, search/yarn.lock, server/src/operators/search_operator.rs
Implemented and tested `num_value` as a default filter on search UI.
- Can also parse apart lists for the `match` filter mode.
=> Added `num_value` as a default filter on search UI

.github/workflows/push-server.yml, search/src/components/ScoreChunk.tsx, server/Cargo.toml, server/Dockerfile.sync-qdrant, server/src/bin/pg-worker.rs, server/src/bin/sync-qdrant.rs, server/src/operators/chunk_operator.rs, server/src/operators/dataset_operator.rs, server/src/operators/qdrant_operator.rs
- **feature: add new sync-qdrant script + cleanup: explicitly ignore payload and vector in qdrant search + cleanup: fix delete worker logs**
- **feature: add sync-qdrant Dockerfile and yaml**
=> feature: add qdrant_sync script to cleanup search index and OLTP data

server/src/bin/ingestion-worker.rs, server/src/bin/pg-worker.rs, server/src/handlers/metrics_handler.rs, server/src/lib.rs
=> ops: reduce log spam by ignoring `/`, `/api/health` and `/metrics`. Bearer Auth only on `/metrics route`

frontends/chat/src/components/Atoms/AfMessage.tsx
Shift+Enter creates new lines rather than submitting the chat query when editing message.
=> bugfix: allow Shift+Enter to create new lines in the edit prompt textarea

server/src/bin/delete-worker.rs, server/src/bin/grupdate-worker.rs, server/src/bin/ingestion-worker.rs, server/src/data/models.rs, server/src/handlers/chunk_handler.rs, server/src/handlers/dataset_handler.rs, server/src/handlers/file_handler.rs, server/src/handlers/group_handler.rs, server/src/handlers/message_handler.rs, server/src/handlers/organization_handler.rs, server/src/handlers/topic_handler.rs, server/src/lib.rs, server/src/operators/chunk_operator.rs, server/src/operators/dataset_operator.rs, server/src/operators/file_operator.rs, server/src/operators/group_operator.rs, server/src/operators/message_operator.rs, server/src/operators/model_operator.rs, server/src/operators/organization_operator.rs, server/src/operators/qdrant_operator.rs, server/src/operators/search_operator.rs
Also ships some nice doc updates for the dataset configs so it's easier to understand what you can set for the dataset config. 
Since removing the `ClientConfiguration` the `server` prefix was no longer needed, so also dropped that throughout the code base. Will figure out a migration for the table and dataset create/update routes later.
=> feature: add route to organization for updating the ServerConfiguration of all datasets

frontends/search/src/components/GroupPage.tsx, frontends/search/src/components/ResultsPage.tsx, frontends/search/src/components/SearchForm.tsx, frontends/search/src/hooks/useSearch.ts, server/src/handlers/analytics_handler.rs, server/src/handlers/chunk_handler.rs, server/src/handlers/dataset_handler.rs, server/src/handlers/event_handler.rs, server/src/handlers/file_handler.rs, server/src/handlers/group_handler.rs, server/src/handlers/message_handler.rs, server/src/handlers/organization_handler.rs, server/src/handlers/topic_handler.rs, server/src/lib.rs, server/src/operators/search_operator.rs
- **cleanup: do not use quote negated terms by default**
- **documentation: add docs to the TR-Dataset headers to note that we accept tracking_id's as valid values**
=> cleanup: do not use quote and negated terms by default + documentation: add docs for TR-Dataset to specify a tracking_id can be used"

server/src/bin/ingestion-worker.rs, server/src/bin/queue-bm25-migration.rs, server/src/lib.rs
I thought excluding times was a good idea since we have a log sync solution with k9s, but k9s is not a good solution for logs with timestamps.
Adding back explicit timestamps for now
=> observerability: add timestamp logs back to workers

frontends/search/src/components/SearchForm.tsx
I consistently open the search UI and don't realize that there are filters when there are which makes me think search is broken when it is not. For this reason, I want to add this tooltip.
=> feature: add filters tooltip

frontends/analytics/tsconfig.json, frontends/chat/tsconfig.json, frontends/dashboard/tsconfig.json, frontends/search/tsconfig.json, frontends/shared/tsconfig.json
We need to disable no-unused-locals for typescript so that the _ prefix change for eslint makes sense
=> enhancement: disable no-unused-locals for ts

frontends/search/src/components/CreateNewDocChunkForm.tsx, frontends/search/src/components/EditChunkPageForm.tsx
- **bugfix: update ingestion message was borked by serde skip on serialize; now fixed**
- **cleanup: allow floats for boost factor**
=> cleanup: allow floats for boostFactor in create and update pages of search playground"

frontends/dashboard/src/components/Routes.ts, server/src/handlers/message_handler.rs
Api docs are currently wrong [here](https://docs.trieve.ai/api-reference/chunk/generate-suggested-queries), and it seems the open api json is also not updated [here](https://api.trieve.ai/api-docs/openapi.json) and this fixes the second part and the open API endpoint
cc @densumesh @skeptrunedev
=> docs: update api endpoint of query suggestions

server/src/handlers/chunk_handler.rs
When a struct is used in a payload, the docstring for that struct appears in the docs instead of the docstring for that key in the request payload. Due to this, the docs for distance phrase were off. This PR fixes that issue. There are other places in the docs where this same fix should eventually be applied.
=> cleanup: properly set docstrings for structs to match payloads for boost and distance phrase

server/src/handlers/file_handler.rs
These feature flags were not being used and causing clippy warnings
=> cleanup: remove unused feature flags in file_handler for ocr

frontends/dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx
This was using the old api method for deleting datasets, we have since deprecated the delete route with a json payload
=> bugfix: fix delete dataset in settings page

frontends/chat/src/components/ScoreChunk.tsx, frontends/chat/src/utils/apiTypes.ts, frontends/dashboard/src/components/DatasetOverview.tsx, frontends/dashboard/src/pages/Dashboard/Dataset/DatasetSettingsPage.tsx, frontends/search/src/components/BookmarkPopover.tsx, frontends/search/src/components/ChunkMetadataDisplay.tsx, frontends/search/src/components/GroupPage.tsx, frontends/search/src/components/ResultsPage.tsx, frontends/search/src/components/ScoreChunk.tsx, server/migrations/2024-08-02-173037_add-index-on-created_at/down.sql, server/migrations/2024-08-02-173037_add-index-on-created_at/up.sql, server/migrations/2024-08-02-174246_delete_pg_events_table/down.sql, server/migrations/2024-08-02-174246_delete_pg_events_table/up.sql, server/src/bin/delete-worker.rs, server/src/data/schema.rs, server/src/handlers/dataset_handler.rs, server/src/operators/dataset_operator.rs, server/src/operators/group_operator.rs
This PR modifies clear to remove all data including files and groups on clear then additionally not delete anything which is added to the dataset after the clear operation occurs.
=> feature: delete files and groups with clear route

server/src/operators/chunk_operator.rs
- cleanup: properly respect max num for highlight array
- cleanup: expand highlight on side when other window too short
- cleanup: prevent highlight panics and window bugs with incorrect potential query
=> cleanup: highlight system panics, extend one window side farther if other is short, fix bugs with incorrect potential query 

server/Cargo.toml
In an attempt to find the memory leak that is happneing in the current main branch add debug symbols to measure memory perf.
=> feature: enable debug symbols in production

docker-compose-cpu-embeddings.yml
update version image of TEI, because on Hetzner cloud server version 1.2 on CPU get crash
=> enhancement: bump TEI versions for docker-compose-cpu-embeddings.yml.

server/src/operators/chunk_operator.rs, server/src/operators/model_operator.rs
Saw this error happening on Hackernews. I suspect it happens when the phrase isn't present in the text.
=> feature: fix unwrap errors in bm25 boosts and get_point_ids_from_unified_chunk_ids

frontends/shared/types.ts
This fixes a typo that appears in the Create New Dataset modal:
=> cleanup: fix typo: Simularity => Similarity

frontends/chat/src/components/ScoreChunk.tsx, server/src/operators/words_operator.rs
=> fix: remove tooltip in chat to fix cutoff

frontends/search/src/components/ResultsPage.tsx, frontends/search/src/utils/apiTypes.ts
=> feature: show corrected query in search playground

frontends/analytics/src/components/Sidebar.tsx, frontends/shared/ui/Tooltip.tsx
=> feat: add more links to analytics sidebar

frontends/chat/src/components/Atoms/AfMessage.tsx, frontends/chat/src/components/Layouts/MainLayout.tsx
=> fix: wrap text in codeblocks to prevent layout glitch

server/src/handlers/auth_handler.rs, server/src/operators/typo_operator.rs
=> feature: fix casing issue and pull from redis in the foreground

clients/search-component/package.json, clients/search-component/scripts/build.js, clients/search-component/src/TrieveModal/index.css, clients/search-component/src/TrieveModal/item.tsx, clients/search-component/src/TrieveSearch/Item.tsx, clients/search-component/src/TrieveSearch/index.tsx, yarn.lock
- Adds better css scoping so we don't get overriden by the users CSS
- Bumps version
=> [Search Component] - CSS Scoping

frontends/chat/src/components/ScoreChunk.tsx
Allows for copying plain text and type `text/html`
=> fix: copy button in chat

frontends/search/src/components/CreateNewDocChunkForm.tsx, frontends/search/src/components/EditChunkPageForm.tsx
Fix typo in hover tooltip in Weight input field for creating and editing chunks in the dashboard.
=> cleanup: fix 2x typos of 'likeclickthrough'

frontends/analytics/src/components/charts/HeadQueries.tsx, frontends/analytics/src/components/charts/LatencyGraph.tsx, frontends/analytics/src/components/charts/LowConfidenceQueries.tsx, frontends/analytics/src/components/charts/NoResultQueries.tsx, frontends/analytics/src/components/charts/RAGUsageGraph.tsx, frontends/analytics/src/components/charts/SearchUsageGraph.tsx, frontends/analytics/src/hooks/data/useHeadQueries.ts, frontends/analytics/src/hooks/data/useLowConfidenceQueries.ts, frontends/analytics/src/hooks/data/useNoResultsQuery.ts, frontends/analytics/src/pages/SearchAnalyticsPage.tsx, frontends/analytics/src/pages/tablePages/SearchTablePage.tsx, frontends/analytics/src/utils/graphDatesFiller.ts, frontends/analytics/src/utils/searchType.ts, frontends/shared/ui/FullscreenModal.tsx, frontends/shared/ui/TanStackTable.tsx
=> feature: new tables on Search Analytics

frontends/dashboard/src/components/DatasetOverview.tsx, frontends/dashboard/src/pages/dataset/DatasetHomepage.tsx
Add refresh chunk count button to dataset start and dataset settings page.
Also fixed the copy dataset id button.
=> feature: add refresh chunk count button 

frontends/dashboard/src/components/DatasetOverview.tsx, frontends/dashboard/src/hooks/useDatasetPages.ts, server/src/bin/crawl-worker.rs, server/src/data/models.rs, server/src/handlers/chunk_handler.rs
- **feature: allow for boosting to be prevented when scraping**
- **bugfix: datasets in table not reloading when org selected changes**
=> feature: ignore title boosting w/ scrape + bugfix: datasets refreshing on org change in dashboard"

clients/search-component/src/TrieveModal/item.tsx, server/src/bin/crawl-worker.rs
- **feature: modify behavior to no longer use the title from metadata**
- **v0.0.5**
- **cleanup: scraper links to heading id or text fragment**
- **cleanup: simplify tracking_id hashing during scrape to just URL and heading**
=> cleanup: hashing for tracking_id in scrape + cleanup: scraper links to heading id or text fragment

server/src/operators/analytics_operator.rs
I suspect that rag queries are being collapsed and thus are non fetch-able, causing a 500 error on `/api/analytics/search`. This is an easy fix as we don't fully delete collapsed queries.
=> bugfix: don't filter duplicates when fetching search queries

frontends/dashboard/src/analytics/components/SingleQueryInfo/ResultCard.tsx, frontends/dashboard/src/analytics/components/SingleRagInfo/index.tsx, frontends/shared/types.ts
If #2511 does not fix the error, we  can default swap to rag_queries.results if there is no easy fix.
=> bugfix: use rag queries for results

frontends/dashboard/src/analytics/components/SingleRagInfo/index.tsx, server/src/operators/analytics_operator.rs
We apply a regex pattern to remove chunk_metadata and then add it back in after serialization finishes
=> feature: fix search_analytics from returning null when serde serialization fails

clients/ts-sdk/openapi.json, clients/ts-sdk/src/functions/topic/index.ts, clients/ts-sdk/src/types.gen.ts, frontends/chat/src/components/Navbar/Sidebar.tsx, server/src/handlers/topic_handler.rs, server/src/lib.rs, server/src/operators/message_operator.rs
Clone route is pretty simple surprisingly
=> feature: clone topic and message route

frontends/chat/src/components/Layouts/MainLayout.tsx, server/src/data/models.rs, server/src/handlers/chunk_handler.rs, server/src/lib.rs, server/src/operators/message_operator.rs
This adds a new set of parameters to LLMOptions:
```sh
llm_options: {
image_config: {
use_images: true,
images_per_chunk: 5
}
}
```
When enabled, the generation routes will send up to `images_per_chunk` image urls in `chunk_metadata.image_urls` to the llm.
Tested on openrouter with the following models:
- `openai/chatgpt-4o-latest` - Better reasoning but 10x slower (~10-15seconds)
- `qwen/qwen-2-vl-7b-instruct` - By far the fastest model, reasoning seems to be a little shy. (~2seconds)
=> feature: send last chunks image_urls into chat model

clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, frontends/chat/src/components/Layouts/MainLayout.tsx, frontends/dashboard/src/components/NewDatasetModal.tsx, frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx, frontends/dashboard/src/utils/validation.tsx, frontends/shared/ui/MultiStringInput.tsx, server/src/bin/crawl-worker.rs, server/src/data/models.rs, server/src/handlers/chunk_handler.rs, server/src/lib.rs, server/src/operators/crawl_operator.rs
- ingests all variants with `tracking_id` being `variant.id`
- places all variants in a `group` based on `product.id`
- applies `fulltext` and `semantic` boosts based on `variant_title`
I need help making the ts-errors go away. 🙏
Will rebase and squash commits after everything is confirmed to work.
Tested on:
- https://dudeperfect.store
- https://rugsusa.com
=> feat: shopify scraping

server/Cargo.lock, server/Cargo.toml, server/src/handlers/organization_handler.rs
Html injections could occur with organization name inserting arb html as the name. This has now been fixed.
=> bugfix: sanitize organization name to prevent html injections

clients/search-component/src/utils/hooks/useKeyboardNavigation.ts, server/Cargo.lock, server/Cargo.toml, server/src/data/models.rs, server/src/handlers/chunk_handler.rs, server/src/handlers/message_handler.rs, server/src/operators/message_operator.rs, server/src/operators/model_operator.rs
Bupmed openai_dive, they released a new version with a lot of breaking changes, but this doesn't unwrap when a request fails now it returns an error
When I migrated some parts of the code broke. Things left for PR to be ready for review
Test Ingestion
Test Search UI
Test ChatUI
etc.
=> bugfix: bump openai dive to a version that doesn't unwrap on requests

server/src/handlers/auth_handler.rs
Trieve expects `name` and `email` claims. Per [OpenID Connect specification][oidc], these are made available with `profile` and `email` scopes correspondingly.
[oidc]: https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims
=> fix: request `profile` and `email` scopes

server/src/handlers/auth_handler.rs
This parameter is not used by Trieve and is not a part of the [OpenID Connect spec][oidc], which makes Trieve break when used with OIDC providers that are not Keycloak.
[oidc]: https://openid.net/specs/openid-connect-core-1_0.html
=> fix: remove `session_state` parameter

clients/ts-sdk/openapi.json, clients/ts-sdk/package.json, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx, server/src/bin/crawl-worker.rs, server/src/data/models.rs, server/src/operators/crawl_operator.rs
- **v0.0.13**
- **feature: add the ability to remove strings from titles and content during crawl**
=> feature: add the ability to remove strings from titles and bodies during crawl

clients/trieve-fumadocs-adapter/package.json
`^0.0.14` does not match the most recent trieve-ts-sdk version `0.0.15` (since the leftmost non-0 number is different)
=> fix(fumadocs): move trieve-ts-sdk to peerDeps, loosen version range

file-chunker/server/Cargo.toml, file-chunker/server/src/operators/pdf_chunk.rs
=> feat: use pdla for chunking

server/src/handlers/auth_handler.rs, server/src/handlers/metrics_handler.rs, server/src/lib.rs, server/src/middleware/metrics_middleware.rs, server/src/middleware/mod.rs, server/src/middleware/timeout_middleware.rs
Adds error gauge for errors with the error type into prometheus scrape.
Example output:
```
tr_api_errors{error_code="303",method="GET",route="/api/auth"} 1
tr_api_errors{error_code="401",method="GET",route="/api/auth/me"} 1
tr_api_errors{error_code="401",method="GET",route="/metrics"} 1
```
=> feature: add errors into prometheus /metrics scrape

clients/ts-sdk/openapi.json, clients/ts-sdk/package.json, clients/ts-sdk/src/functions/datasets/datasets.test.ts, clients/ts-sdk/src/functions/datasets/index.ts, clients/ts-sdk/src/functions/index.ts, clients/ts-sdk/src/sdk.ts, clients/ts-sdk/src/types.gen.ts, server/src/data/models.rs, server/src/handlers/chunk_handler.rs, server/src/handlers/dataset_handler.rs, server/src/lib.rs, server/src/operators/chunk_operator.rs, server/src/operators/dataset_operator.rs
=> feature: add batch create dataset route

clients/ts-sdk/openapi.json, clients/ts-sdk/package.json, clients/ts-sdk/src/functions/chunks/index.ts, clients/ts-sdk/src/types.gen.ts, server/src/bin/crawl-worker.rs, server/src/handlers/chunk_handler.rs, server/src/lib.rs, server/src/operators/crawl_operator.rs
=> feature: expose custom html based splitter

.github/ISSUE_TEMPLATE/issue-template.md, .github/workflows/push-pdf2md-server.yml, .gitignore, pdf2md/.env.dist, pdf2md/cli/src/main.rs, pdf2md/docker-compose.yml, pdf2md/server/.env.dist, pdf2md/server/Cargo.lock, pdf2md/server/Cargo.toml, pdf2md/server/Dockerfile.chunk-worker, pdf2md/server/Dockerfile.pdf2md-server, pdf2md/server/Dockerfile.supervisor-worker, pdf2md/server/src/lib.rs, pdf2md/server/src/main.rs, pdf2md/server/src/operators/redis.rs, pdf2md/server/src/workers/chunk-worker.rs, pdf2md/server/src/workers/supervisor-worker.rs, server/Dockerfile.ingestion-worker
=> feature: docker setup for pdf2md

.env.server, pdf2md/server/src/lib.rs, pdf2md/server/src/operators/clickhouse.rs, pdf2md/server/src/operators/pdf_chunk.rs, pdf2md/server/src/workers/chunk-worker.rs, server/Cargo.toml, server/src/bin/file-worker.rs, server/src/handlers/file_handler.rs, server/src/operators/file_operator.rs
This supports the full end to end workflow of uploading a document, having it be chunked by pdf2md service, and having it be viewable in the Trieve Dashboard.
Currently only uses 1 chunk per page.
=> bugfix: use correct page count, feature: fileworker integration with Trieve

pdf2md/.env.dist, pdf2md/README.md, pdf2md/docker-compose-prod.yaml, pdf2md/docker-compose.yml, pdf2md/server/Dockerfile.chunk-worker, pdf2md/server/Dockerfile.pdf2md-server, pdf2md/server/Dockerfile.supervisor-worker, pdf2md/server/src/operators/clickhouse.rs, pdf2md/server/src/operators/pdf_chunk.rs, pdf2md/server/src/workers/chunk-worker.rs, pdf2md/server/src/workers/supervisor-worker.rs
- **chore: create seperate docker-compose.yml files for dev and prod**
- **bugfix: make Dockerfile.worker to install poppler**
- **feature: don't let workers run migrations**
- **docs: setup README with setup guide and hosting guide**
=> docs: docker compose guide with fixed docker containers

frontends/search/src/components/UploadFile.tsx, server/src/bin/file-worker.rs, server/src/handlers/file_handler.rs
=> feature: add flag to enable pdf2md

pdf2md/server/src/operators/s3.rs, pdf2md/server/src/templates/demo-ui.html, pdf2md/server/static/output.css, pdf2md/server/static/pdf2md.js
=> feature: cost, json toggle, copy button for pdf2md

clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, frontends/search/src/components/OrgGroupPageView.tsx, frontends/search/src/components/UploadFile.tsx, server/src/handlers/group_handler.rs, server/src/lib.rs, server/src/operators/group_operator.rs
=> feature: count chunks in group route and in UI

.env.server, server/src/handlers/chunk_handler.rs
=> feature: make BATCH_CHUNK_LIMIT an env to increase it past 120 for larger deployments

clients/ts-sdk/openapi.json, clients/ts-sdk/src/functions/index.ts, clients/ts-sdk/src/functions/organization/index.ts, clients/ts-sdk/src/functions/organization/organization.test.ts, clients/ts-sdk/src/functions/user/index.ts, clients/ts-sdk/src/functions/user/user.test.ts, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/components/ApiKeyGenerateModal.tsx, frontends/dashboard/src/components/ApiKeys.tsx, frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx, server/migrations/2024-11-21-215958_organization_api_key/down.sql, server/migrations/2024-11-21-215958_organization_api_key/up.sql, server/src/bin/crawl-worker.rs, server/src/data/models.rs, server/src/data/schema.rs, server/src/handlers/organization_handler.rs, server/src/handlers/user_handler.rs, server/src/lib.rs, server/src/middleware/auth_middleware.rs, server/src/operators/organization_operator.rs, server/src/operators/user_operator.rs
=> feature: scope api keys to orgs

.github/workflows/rust-tests.yml, server/src/bin/crawl-worker.rs, server/src/bin/ingestion-worker.rs, server/src/handlers/chunk_handler.rs, server/src/operators/chunk_operator.rs, server/src/operators/file_operator.rs, server/src/operators/webhook_operator.rs
Refactored the logic here to handle the error case and the updating dataset count's seperately
=> bugfix: revert failed inserts in qdrant_only mode

clients/ts-sdk/src/__tests__/constants.ts, clients/ts-sdk/src/functions/organization/organization.test.ts, server/migrations/2024-11-28-041452_add_on_delete_cascade_for_org_api_key/down.sql, server/migrations/2024-11-28-041452_add_on_delete_cascade_for_org_api_key/up.sql, server/src/data/models.rs, server/src/operators/organization_operator.rs, server/src/operators/search_operator.rs
=> feature: readd recency bias

frontends/dashboard/src/analytics/components/charts/Card.tsx, frontends/dashboard/src/analytics/pages/SearchAnalyticsPage.tsx
added an overflow to all cards but also made the specific table 2 cols wide since we added more data to it.
=> styling: fix overflowing analytics table

clients/ts-sdk/openapi.json, clients/ts-sdk/package.json, clients/ts-sdk/src/types.gen.ts, frontends/chat/src/components/FilterModal.tsx, frontends/chat/src/components/ScoreChunk.tsx, frontends/search/src/components/FilterModal.tsx, frontends/search/src/components/GroupPage.tsx, frontends/search/src/components/ResultsPage.tsx, frontends/search/src/utils/apiTypes.ts, server/src/data/models.rs, server/src/operators/search_operator.rs
- **feature: allow editing a group's tag_set and tracking_id via search playground**
- **cleanup: return 0 results when there are matching groups for a given set of tracking_id filters instead of erroring**
- **wip: backend done for boolean filter, need frontend**
- **wip: UI progress**
- **wip: UI progress**
=> feature: add support for boolean filters

clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/components/ApiKeys.tsx, frontends/dashboard/src/components/NewDatasetModal.tsx, frontends/dashboard/src/components/dataset-settings/GeneralSettings.tsx, frontends/dashboard/src/components/dataset-settings/LegacySettingsWrapper.tsx, frontends/dashboard/src/utils/serverEnvs.ts, frontends/shared/types.ts, server/src/data/models.rs, server/src/operators/model_operator.rs
=> feature: support for reranker api key and cohere rerank-v3.5

server/migrations/2024-12-05-201534_remove-chunk-counts-trigger/down.sql, server/migrations/2024-12-05-201534_remove-chunk-counts-trigger/up.sql, server/src/bin/ingestion-worker.rs, server/src/operators/chunk_operator.rs, server/src/operators/dataset_operator.rs
=> feature: remove postgresql trigger function for chunk counts

server/src/handlers/message_handler.rs, server/src/operators/message_operator.rs
- **cleanup: search-component copy now green + powered by trieve at bottom with empty tag row when no tags + ctrl+m to swap modes**
- **cleanup: remove expects for LLM completion calls**
=> cleanup: remove expects on LLM completion calls

.github/workflows/update-trieve-fern-adapter.yaml
I notice the `update-trieve-fern-adapter` workflow is not working as the `main` branch is branch protected. Instead of committing to `main`, this will create a new PR with the version bump.
=> fix: trieve-fern-adapter workflow

.github/workflows/update-trieve-fern-adapter.yaml
Currently, the trieve-fern-adapter workflow will create a PR to bump the package version. The merging of the bump version PR will result in the workflow to be triggered again. 
This PR will prevent the workflow to be triggered by merging the bump version PR. This completes the workflow.
=> chore: prevent trieve-fern-adapter workflow running when merging the bump pr

clients/search-component/example/src/routes/__root.tsx, clients/search-component/example/src/routes/index.lazy.tsx, clients/search-component/package.json, clients/search-component/src/TrieveModal/index.tsx, clients/search-component/src/utils/hooks/modal-context.tsx, clients/search-component/src/utils/hooks/setClickTriggers.ts, server/src/public/search-component-code.html
Current iteration of search component view with script tag
=> feature: convert public page to single install script tag

.vscode/launch.json, clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, docker-compose-firecrawl.yml, server/src/bin/crawl-worker.rs, server/src/data/models.rs, server/src/handlers/dataset_handler.rs, server/src/handlers/file_handler.rs, server/src/lib.rs, server/src/operators/crawl_operator.rs
- **feature: add hallucination detection to server**
- **wip: can't deserialize firecrawl response in crawl_operator from crawl-worker**
=> feature: add route to listen to firecrawl webhooks

frontends/dashboard/src/analytics/components/SingleRagInfo/index.tsx, frontends/dashboard/src/analytics/pages/tablePages/RAGAnalyticsPage.tsx, frontends/shared/types.ts, hallucination-detection/Cargo.lock, hallucination-detection/Cargo.toml, hallucination-detection/README.md, hallucination-detection/examples/rag_truth_test.rs, hallucination-detection/examples/vectara_test.rs, hallucination-detection/src/lib.rs, pdf2md/server/Cargo.lock, server/Cargo.lock, server/Cargo.toml, server/Dockerfile.server, server/build.rs, server/ch_migrations/1733613844_add_hallucination_score/down.sql, server/ch_migrations/1733613844_add_hallucination_score/up.sql, server/src/data/models.rs, server/src/handlers/chunk_handler.rs, server/src/handlers/message_handler.rs, server/src/lib.rs, server/src/operators/message_operator.rs
=> feature: add hallucination detection to server

server/src/operators/qdrant_operator.rs
=> bugfix: call group count for search_over_groups

frontends/search/src/components/UploadFile.tsx, pdf2md/server/src/models.rs, pdf2md/server/src/operators/clickhouse.rs, pdf2md/server/src/operators/pdf_chunk.rs, pdf2md/server/src/routes/jinja_templates.rs, server/src/bin/csv-jsonl-worker.rs, server/src/bin/file-worker.rs, server/src/handlers/file_handler.rs, server/src/lib.rs, server/src/operators/file_operator.rs
=> feature: incrementally add pages

clients/search-component/README.md, clients/search-component/example/src/routes/index.lazy.tsx, clients/search-component/package.json, clients/search-component/src/TrieveModal/Chat/AIInitalMessage.tsx, clients/search-component/src/TrieveModal/Chat/ChatMode.tsx, clients/search-component/src/TrieveModal/Search/DocsItem.tsx, clients/search-component/src/TrieveModal/Search/ProductGroupItem.tsx, clients/search-component/src/TrieveModal/Search/SearchMode.tsx, clients/search-component/src/TrieveModal/index.css, clients/search-component/src/TrieveModal/index.tsx, clients/search-component/src/utils/estimation.ts, clients/search-component/src/utils/hooks/modal-context.tsx, clients/search-component/src/utils/hooks/useKeyboardNavigation.ts, clients/search-component/src/utils/types.ts, clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx, server/src/data/models.rs, server/src/handlers/page_handler.rs, server/src/public/navbar.html, server/src/public/page.html, server/src/public/tabs.html, server/static/output.css
- **v0.2.20**
- **v0.2.21**
- **v0.2.22**
- **feature: add ability to specify a custom font on public page**
=> feature: allow for custom fonts on public page

frontends/dashboard/src/analytics/hooks/data/useDataExplorerRag.ts, frontends/dashboard/src/analytics/pages/tablePages/RAGAnalyticsPage.tsx, frontends/shared/types.ts, server/src/data/models.rs, server/src/operators/analytics_operator.rs, server/src/operators/message_operator.rs
=> feature: sort by top_score and hallucination_score for rag

clients/search-component/example/src/routes/ecommerce.tsx, clients/search-component/package.json, clients/search-component/src/TrieveModal/Chat/ChatMode.tsx, clients/search-component/src/TrieveModal/Search/ProductItem.tsx, clients/search-component/src/TrieveModal/Tags.tsx, clients/search-component/src/TrieveModal/index.css, clients/search-component/src/TrieveModal/index.tsx, clients/search-component/src/utils/hooks/chat-context.tsx, clients/ts-sdk/openapi.json, clients/ts-sdk/package.json, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx, pdf2md/CONTRIBUTING.md, server/src/data/models.rs, server/src/handlers/page_handler.rs, server/src/lib.rs, server/src/operators/qdrant_operator.rs, server/src/public/navbar.html, server/src/public/page.html, server/src/public/product.html, server/src/public/tabs.html, server/static/output.css
- **wip: single product view for demo page**
- **wip: finished skeleton for single product display**
- **wip: completed recs working with search over groups**
- **v0.2.23**
- **v0.2.24**
- **v0.2.25**
- **v0.0.44**
- **feature: fully working suggested questions for a single product**
=> feature: product view for demo page

server/src/public/navbar.html, server/src/public/page.html, server/src/public/tabs.html, server/static/output.css
=> bugfix: mobile tabs for demo page horizontally scroll now

clients/search-component/README.md, clients/search-component/package.json, clients/search-component/src/TrieveModal/Chat/AIInitalMessage.tsx, clients/search-component/src/TrieveModal/index.css, clients/ts-sdk/openapi.json, clients/ts-sdk/package.json, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx, server/src/data/models.rs, server/src/handlers/page_handler.rs, server/src/lib.rs, server/src/public/page.html, server/src/public/product.html, server/src/public/search-component-code.html, server/static/output.css
- **styling: mobile chat modal spacing issues**
- **v0.0.45**
- **v0.2.28**
- **cleanup: mobile styling fixes for chat component**
=> styling: mobile chat modal fixes

clients/search-component/README.md, clients/search-component/package.json, clients/search-component/scripts/watch.js
Main changes
The `example/` folder shows the example application for what rendering this would look like
Run the example, search-component, css, javascript and watcher for demos page
```sh
$clients/search-component yarn all
```
or to run each individually
Start the listener to update the search-component's css and javascript
```sh
$clients/search-component yarn
$clients/search-component yarn dev
```
----------------------------
```sh
cd clients/search-component/
yarn all
```
Set environment variable in `server/.env`
```sh
SEARCH_COMPONENT_URL="http://localhost:8000"
```
=> chore: refactor search component UX for running local dev with public page

clients/search-component/package.json, clients/search-component/src/TrieveModal/index.css, clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/hooks/usePublicPageSettings.tsx, frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx, server/src/data/models.rs, server/src/handlers/page_handler.rs, server/src/public/page.html, server/src/public/product.html, server/static/output.css
Testing links:
- https://player.vimeo.com/video/288344114
- https://www.youtube.com/embed/tgbNymZ7vqY
=> feature: add video embed to public page

clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/analytics/components/FilterBar.tsx, frontends/dashboard/src/analytics/components/charts/AnalyticsChart.tsx, frontends/dashboard/src/analytics/components/charts/LatencyGraph.tsx, frontends/dashboard/src/analytics/components/charts/RAGUsageGraph.tsx, frontends/dashboard/src/analytics/components/charts/SearchUsageGraph.tsx, frontends/dashboard/src/analytics/utils/formatDate.ts, frontends/dashboard/src/analytics/utils/graphDatesFiller.ts, frontends/shared/types.ts, frontends/shared/ui/DateRangePicker.tsx, server/src/data/models.rs, server/src/operators/analytics_operator.rs
=> feat: add all time view option for analytics

clients/mcp-server/README.md, clients/mcp-server/package.json, clients/mcp-server/src/index.ts
Fundamentally, the issue came down to I generated out a non-admin key for just one dataset, and didn't see any datasets, so this fixes that and handles the hierarchy. I imagine there's other rules and should get vitest going for this as well, but then someone additionally will need to make the MCP server testable (i.e. mock out the client and methods).
- Added support for specifying a single dataset ID via CLI args (`--dataset-id`) or environment variables (`TRIEVE_DATASET_ID`)
- When dataset ID is provided, the MCP server will only expose and operate on that specific dataset
- Updated documentation to reflect new dataset ID options
- Bumped version to 0.1.3
The changes have been tested with both CLI args and environment variables to ensure:
- Server properly initializes with dataset ID
- …
=> feat: add dataset ID support

clients/search-component/package.json, clients/search-component/src/TrieveModal/Chat/GroupChatImgCarousel.tsx, clients/search-component/src/utils/hooks/chat-context.tsx, clients/search-component/src/utils/hooks/useFollowupQuestions.ts, clients/search-component/src/utils/trieve.ts
Fixed removeNode error hopefully, was happening due to a race condition, hard to see if it got fixed fully.
Also now add a filter to `suggestedQueries` for group_id so follow up questions are based on the context. Example of questions, they do look better.
=> feature: suggestions are scoped to group_tracking_id, bugfix: removeNode racecondition fixed

clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, server/src/bin/csv-jsonl-worker.rs, server/src/bin/file-worker.rs, server/src/handlers/file_handler.rs
=> feat: create option to disable chunk splitting for files

clients/search-component/example/src/routes/index.lazy.tsx, clients/search-component/package.json, clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx, clients/search-component/src/TrieveModal/Chat/ChatMode.tsx, clients/search-component/src/TrieveModal/ImagePreview.tsx, clients/search-component/src/TrieveModal/Search/SearchMode.tsx, clients/search-component/src/TrieveModal/Search/UploadImage.tsx, clients/search-component/src/TrieveModal/index.css, clients/search-component/src/utils/hooks/chat-context.tsx, clients/search-component/src/utils/hooks/modal-context.tsx, clients/search-component/src/utils/trieve.ts, clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/components/Routes.ts, server/src/data/models.rs, server/src/handlers/chunk_handler.rs, server/src/handlers/message_handler.rs, server/src/operators/message_operator.rs, server/src/operators/search_operator.rs, server/src/public/product.html
=> feature: chat with image in the component

server/src/operators/message_operator.rs
=> bugfix: include image urls when they are provided

clients/search-component/src/TrieveModal/Chat/ChatMode.tsx, clients/search-component/src/TrieveModal/Search/UploadImage.tsx, clients/search-component/src/TrieveModal/index.css
=> bugfix: fix floating clear button, bugfix: fix margin bar too high issue, bugfix: fix numerical list padding

clients/search-component/package.json, clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx, clients/search-component/src/utils/hooks/modal-context.tsx, clients/search-component/src/utils/hooks/useFollowupQuestions.ts, clients/search-component/src/utils/hooks/useSuggestedQueries.ts, clients/search-component/src/utils/hooks/useSuggestedQuestions.ts, clients/search-component/src/utils/trieve.ts, clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx, server/src/data/models.rs, server/src/handlers/page_handler.rs, server/src/public/search-component-code.html
=> feature: fixed followup questions issues

clients/search-component/src/TrieveModal/index.css
=> bugfix: fix misc search comp issues

clients/search-component/package.json, clients/search-component/src/utils/hooks/chat-context.tsx, clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, server/src/handlers/chunk_handler.rs
=> feature: use images with rag over chunks

server/src/public/page.html, server/src/public/product.html, server/static/output.css
- **cleanup: fix inlineChat uses demo page productQuestions fix image recomendations**
- **cleanup: make popup non group**
=> cleanup: more demo page enhacements

clients/search-component/src/utils/hooks/useFollowupQuestions.ts, clients/search-component/src/utils/trieve.ts, server/src/handlers/message_handler.rs, server/src/public/product.html, server/static/output.css
=> feature: add more context to suggested questions

frontends/dashboard/src/hooks/usePublicPageSettings.tsx
This reverts commit 2a37a7d1914965f0a0eff09a00c3c1321008275c.
=> revert: autofill favicon public page icon from scrape settings

server/src/operators/search_operator.rs
If passed timer is not null we have traces for both the pg call, and the time spent highlighting. Should hopefully help to narrow down our search.
https://github.com/devflowinc/trieve/blob/382c69a84036738355793190914fb76dc109bad8/server/src/operators/search_operator.rs#L1477-L1483
https://github.com/devflowinc/trieve/blob/382c69a84036738355793190914fb76dc109bad8/server/src/operators/search_operator.rs#L1577-L1579
=> feature: fine tune tracing on fetch from postgres

clients/search-component/src/TrieveModal/Chat/Carousel.tsx, clients/search-component/src/TrieveModal/icons.tsx, clients/search-component/src/TrieveModal/index.css
=> cleanup: use fa-chevron arrows + remove arrows on mobile

server/src/operators/chunk_operator.rs, server/src/operators/search_operator.rs
We had an edge case that when `query` gets very large, the comparison operator we use when evaluating the optimal highlight window gets way too large. Most minimal fix without many side effects is to only use this sort operation when the `query` is <= 20 words.
Additionally this moves highlight functionality into its on `web::block` so that it operates on a non receiving thread.
=>  bugfix: call highlight_chunks in a web::block, fix ineffecient comparision operation

frontends/search/src/components/SearchForm.tsx
=> bugfix: fix must_not and should filters on search playground

server/migrations/2025-01-24-084100_modify_organization_usage_counts_to_statement_level/down.sql, server/migrations/2025-01-24-084100_modify_organization_usage_counts_to_statement_level/up.sql
Migrates `organization_usage_counts` triggers from row level queries to statement level queries. Row level need to acquire a lock on the full table which can very easily cause a deadlock since so many different inserts trigger it.
Things tested to be working:
=> bugfix: migrate organization usage counts to be statement level

frontends/dashboard/src/analytics/components/SingleRagInfo/index.tsx
=> fix: only show rag output in chat playground

clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx, clients/search-component/src/TrieveModal/FloatingSearchIcon.tsx, clients/search-component/src/utils/hooks/modal-context.tsx
There's no easy way to remove onClick listeners in react without messing up the dom tree. also re-enable the ability to view
=> feature(component): add props to disable the search icon and enable inlineCarousel

server/src/operators/file_operator.rs, server/src/operators/parse_operator.rs
Convert the defaults `split_delimiters` to route through the same logical path
=> bugfix: use the correct default for the file upload route

.vscode/settings.json, clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, docker/clickhouse/embed.py, frontends/dashboard/src/analytics/api/analytics.ts, frontends/dashboard/src/analytics/components/charts/RagMetrics.tsx, frontends/dashboard/src/analytics/components/charts/SearchMetrics.tsx, frontends/dashboard/src/analytics/pages/AnalyticsOverviewPage.tsx, frontends/shared/types.ts, server/src/data/models.rs, server/src/handlers/analytics_handler.rs, server/src/lib.rs, server/src/operators/analytics_operator.rs, server/src/operators/clickhouse_operator.rs, server/src/operators/dittofeed_operator.rs, server/src/operators/message_operator.rs
=> feature: add aggregate rating stats

.github/workflows/push-server.yml, server/Cargo.toml, server/Dockerfile.backfill-qdrant-from-pg, server/src/bin/backfill-qdrant-from-pg.rs, server/src/bin/crawl-worker.rs, server/src/bin/csv-jsonl-worker.rs, server/src/bin/etl-worker.rs, server/src/bin/ingestion-worker.rs, server/src/data/models.rs, server/src/handlers/chunk_handler.rs, server/src/operators/chunk_operator.rs, server/src/operators/crawl_operator.rs, server/src/operators/file_operator.rs, server/src/operators/webhook_operator.rs
Testing:
- ingest some data
- delete a qdrant collection
- run `cargo run --bin two-sync`
- run ingestion workers
Qdrant collection should be fully ingested
=> feature: new qdrant migration stratedgy 

clients/trieve-shopify-extension/app/processors/getProducts.ts
Split `variantTitle` by " / " in order to extract all the variant titles. Should help for more accurate filtering.
=> feature(shopify): split variant name by spaces

clients/ts-sdk/openapi.json, server/src/handlers/group_handler.rs, server/src/lib.rs, server/src/operators/group_operator.rs
Added request param flag for `use_cursor`. If set to `true`. `/api/dataset/groups` will return with a `next_cursor` parameter.
This should be passed into the next request as `cursor`.
See examples below
Request:
```
httpget $"https://api.trieve.ai/api/dataset/groups/($dataset_id)?use_cursor=true"
```
Response:
```
{
"groups": [
{
"id": "00308933-2044-4e6a-b2a3-79f22d0293ac",
"dataset_id": "82d6a576-1c98-4186-a3f2-25300452cf5c",
"name": "8872437383420",
"description": "",
"tracking_id": "8872437383420",
"tag_set": [],
"metadata": {},
"file_id": null,
"created_at": "2025-02-14T23:51:06.641160",
"updated_at": "2025-02-14T23:51:06.641160"
},
...
],
"total_pages": 18,
"next_cursor": "120a60f7-5f23-4a14-ba7f-80136ecc1ec4"
}
```
`next_cursor` is: `120a60f7-5f23-4a14-ba7f-80136ecc1ec4`
Adding …
=> feature(server): add `use_cursor` option for scroll through dataset groups on `/api/dataset/groups`

clients/trieve-shopify-extension/app/components/analytics/AdvancedTableComponent.tsx, clients/trieve-shopify-extension/app/components/analytics/AnalyticsChart.tsx, clients/trieve-shopify-extension/app/components/analytics/FilterBar.tsx, clients/trieve-shopify-extension/app/components/analytics/chat/AllChatsTable.tsx, clients/trieve-shopify-extension/app/routes/app._dashboard.component.tsx, clients/trieve-shopify-extension/app/routes/app.tsx, clients/trieve-shopify-extension/app/utils/formatting.ts, clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, server/src/data/models.rs, server/src/handlers/analytics_handler.rs, server/src/operators/analytics_operator.rs
=> cleanup: various shopify fixes

server/src/data/models.rs
Recently we adjusted plans to be in kb. The only thing that wasn't updated was the hard coded file-storage parameter here
=> feat(server): increase file_storage for free plans to also be in kb

README.md, frontends/search/src/components/SearchForm.tsx
1. Implemented a 1.2-second debounce on the Search input to optimize performance when the AIMon reranker is selected, reducing redundant query executions during rapid user input.
2. Updated the README.md, to build the front-end before configuring services via `tmux`
According to my testing, `frontends` and `ts-sdk` need to be built before they can be set via `tmux`
=> refactor: added 1.2s debounce to Search when AIMon reranker is selected.

clients/search-component/package.json, clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx, clients/search-component/src/utils/hooks/chat-context.tsx, clients/trieve-shopify-extension/app/components/analytics/chat/ChatEventsFilter.tsx, clients/trieve-shopify-extension/app/queries/analytics/chat.ts, clients/trieve-shopify-extension/app/routes/app._dashboard.chats.tsx, clients/trieve-shopify-extension/app/routes/app._dashboard.chatview.$topic.tsx, clients/trieve-shopify-extension/package.json, clients/trieve-shopify-extension/yarn.lock, clients/ts-sdk/openapi.json, clients/ts-sdk/package.json, clients/ts-sdk/src/types.gen.ts, server/src/data/models.rs, server/src/lib.rs, server/src/operators/analytics_operator.rs
- **feature: filter by `event_name`, instead of `event_type`. remove `prodct_view` join due to it removing data in the join**
- **bugfix: only display the product that was clicked if it was in the position matches**
=> feature: filter by event_name instead of event_type. bugfix for displaying the item clicked

clients/trieve-shopify-extension/app/queries/onboarding.ts, clients/trieve-shopify-extension/package.json, clients/trieve-shopify-extension/shopify.app.toml.dist, clients/trieve-shopify-extension/yarn.lock, server/ch_migrations/1744254191_create-rag-queries-monthly-counts/down.sql, server/ch_migrations/1744254191_create-rag-queries-monthly-counts/up.sql, server/migrations/2025-04-10-010747_add-component-loads-limit-into-stripe-plans/down.sql, server/migrations/2025-04-10-010747_add-component-loads-limit-into-stripe-plans/up.sql, server/src/data/models.rs, server/src/data/schema.rs, server/src/handlers/organization_handler.rs, server/src/operators/dittofeed_operator.rs, server/src/operators/organization_operator.rs, server/src/operators/payment_operator.rs
- **feat(server): add component loads limit to stripe plans and update related models**
- **feat(server): add current month's message count to organization usage metrics and create related database view**
End result is that pulling organization usage is much faster (due to parallelization) and the monthly messages come out of the mv. 
Response sample: 
```json
{
"search_tokens": 210,
"message_tokens": 24612,
"dataset_count": 1,
"user_count": 1,
"file_storage": 0,
"message_count": 17,
"search_count": 41,
"chunk_count": 70,
"bytes_ingested": 363208,
"tokens_ingested": 8317,
"ocr_pages_ingested": 0,
"website_pages_scraped": 0,
"events_ingested": 58,
"current_months_message_count": 17
}
```
=> feature: track monthly message usage for Shopify billing

clients/trieve-shopify-extension/app/components/analytics/AdvancedTableComponent.tsx, clients/trieve-shopify-extension/app/components/analytics/chat/ChatEventsFilter.tsx, clients/trieve-shopify-extension/app/routes/app._dashboard.chats.tsx, clients/trieve-shopify-extension/package.json, clients/trieve-shopify-extension/yarn.lock, clients/ts-sdk/openapi.json, clients/ts-sdk/src/types.gen.ts, server/src/data/models.rs, server/src/operators/analytics_operator.rs
- fixed a bug caused by the `event_name` enum not serializing to the proper string
- refactored query to be a list of all events that occurred.
=> bugfix: convert event_name string to the proper name for queries and refactored query to be a list of all events

clients/trieve-shopify-extension/app/components/analytics/BasicTableComponent.tsx
Adds an empty state for the main page tables. 
Makes things more polished especially for the user's first ever view of the dashboard. 
BEFORE: 
AFTER:
=> styling: empty state for dashboard homepage title

.github/workflows/push-server.yml, server/Cargo.toml, server/Dockerfile.clone-qdrant-from-offset, server/src/bin/clone-qdrant-from-offset.rs
This script is similar to `clone-qdrant`, but instead it adds a postgres filter for updated_at. For live cloneing without having to disable ingestion. 
Since this uses postgres as the primary scroll key, A uuid range can also be provided if it needs to be parallelized.
=> feature: clone qdrant from offset script

clients/ts-sdk/openapi.json, clients/ts-sdk/package.json, clients/ts-sdk/src/types.gen.ts, server/src/handlers/message_handler.rs, yarn.lock
- **bugfix(server): openapi spec def for edit image**
- **feat(ts-sdk): release v0.0.95**
=> bugfix(server): openapi spec for edit image

server/src/handlers/organization_handler.rs, server/src/operators/organization_operator.rs
**Example Request:** 
```
curl --request POST \
--url http://localhost:8090/api/organization/update_dataset_configs \
--header 'Authorization: tr-******************************' \
--header 'Content-Type: application/json' \
--header 'TR-Organization: ******************************' \
--data '{
"organization_id": "******************************",
"from_configuration": {
"LLM_DEFAULT_MODEL": "gpt-4o-mini"
},
"to_configuration": {
"LLM_DEFAULT_MODEL": "gpt-4o",
"SYSTEM_PROMPT": "You are a helpful assistant"
}
}'
```
=> refactor: modify update all dataset configurations to match on existing types

server/src/handlers/organization_handler.rs
The ability to create organization api keys should only be allowed for Admin users
or greater. This is a security feature to prevent generating arbitrary keys from an unscoped
read-only user api key.
=> sec: bump permission on creating an `organization_api_key`
