devflowinc/trieve

clients/search-component/package.json
clients/search-component/src/TrieveModal/index.css

Related: https://github.com/devflowinc/signoz-web/issues/6

feat: add CSS variables for colors

---

clients/search-component/README.md
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/hooks/useKeyboardNavigation.ts

Adds the ability to pass the key combination that opens the modal as a prop
Related https://github.com/devflowinc/signoz-web/issues/7

feat: allow user to choose the key combination that opens the modal

---

.github/workflows/push-server.yml
server/Dockerfile.dittofeed-sync-worker
server/src/bin/dittofeed-sync-worker.rs
server/src/data/models.rs
server/src/handlers/dataset_handler.rs
server/src/operators/analytics_operator.rs
server/src/operators/dataset_operator.rs
server/src/operators/dittofeed_operator.rs
server/src/operators/mod.rs
server/src/operators/user_operator.rs

feature: ditto scraper

---

server/src/bin/dittofeed-sync-worker.rs

bugfix: log if identity call fails

---

server/src/operators/crawl_operator.rs

bugfix: get heading correctly for firecrawl

---

server/src/data/models.rs
server/src/operators/analytics_operator.rs

bugfix: include llm response on RAG analytics routes and fix docs

---

frontends/analytics/src/components/charts/RagQueries.tsx
frontends/shared/types.ts
frontends/shared/ui/JSONMetadata.tsx

feature: add llm response to frontend

---

clients/search-component/package.json
frontends/shared/ui/TanStackTable.tsx

- **v0.0.8**
- **styling: max-w-2xl-full removal for tanstacktable component**

styling: max-w-2xl-full removal for tanstacktable component"

---

clients/search-component/src/TrieveModal/item.tsx

bugfix: fix scroll behavior on search-component

---

server/src/operators/qdrant_operator.rs
server/src/operators/search_operator.rs

- **bugfix: inconsistent page size for hybrid group search**
- **bugfix: get total pages for group search**

bugfix: group search issues for get_total_pages and hybrid page size

---

clients/search-component/example/src/App.tsx
clients/search-component/package.json
clients/search-component/src/TrieveModal/SearchMode.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/TrieveSearch/Item.tsx
clients/search-component/src/TrieveSearch/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/hooks/useSuggestedQueries.ts
clients/search-component/src/utils/trieve.ts
yarn.lock

closes https://github.com/devflowinc/trieve/issues/2358

feature: add filter by tag to search component

---

clients/search-component/src/TrieveModal/ChatMode.tsx
yarn.lock

bugfix: concat user messages in search component

---

frontends/dashboard/src/analytics/components/charts/RagQueries.tsx

bugfix: ensure that when clicking on llm response, it shows the right one

---

frontends/dashboard/src/analytics/api/ctr.ts
frontends/dashboard/src/analytics/components/charts/CTRSearchQueries.tsx
frontends/dashboard/src/analytics/hooks/data/useCTRSearchQueries.ts
frontends/dashboard/src/analytics/pages/SearchAnalyticsPage.tsx
frontends/dashboard/src/components/Sidebar.tsx
frontends/shared/types.ts
frontends/shared/ui/JsonInput.tsx
server/src/data/models.rs
server/src/operators/analytics_operator.rs

feature: add ctr data to analytics page

---

frontends/dashboard/src/components/ApiKeys.tsx

feature: add api name to api keys table

---

server/src/bin/dittofeed-sync-worker.rs

feature: don't kill process if dittofeed fails

---

frontends/dashboard/src/analytics/layouts/DataExplorerTabs.tsx

bugfix: fix data explorer links

---

server/src/data/models.rs
server/src/handlers/event_handler.rs

bugfix: remove unused event types

---

frontends/config/tailwind-preset.cjs
frontends/dashboard/src/analytics/components/FilterBar.tsx
frontends/dashboard/src/analytics/pages/SearchAnalyticsPage.tsx
frontends/dashboard/src/components/DatasetOverview.tsx
frontends/dashboard/src/components/GettingStartedDocsLinks.tsx
frontends/dashboard/src/layouts/DatasetSidebarLayout.tsx
frontends/dashboard/src/layouts/NavbarLayout.tsx
frontends/shared/ui/TanStackTable.tsx

Small layout fixes to make it better on mobile, nothting that takes too much effort

feat: dashboard mobile layout

---

frontends/dashboard/src/api/trieve.ts
frontends/dashboard/src/components/DatasetOverview.tsx
frontends/dashboard/src/components/dataset-settings/TrackingIdUpdater.tsx
frontends/dashboard/src/contexts/DatasetContext.tsx
frontends/dashboard/src/contexts/UserContext.tsx
frontends/dashboard/src/pages/dataset/DatasetHomepage.tsx
server/src/operators/dataset_operator.rs

feat: set tracking ids for datasets

---

frontends/dashboard/src/components/DatasetOverview.tsx
frontends/dashboard/src/components/OnboardingSteps.tsx
frontends/dashboard/src/pages/orgs/OrganizationHomepage.tsx

Couldn't identify root issue so I just moved the usageQuery prop to be inside the component which fixed it.

fix: layout shift from onboarding steps

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/ChatMessage.tsx
clients/search-component/src/TrieveModal/ChatMode.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/useChat.ts
clients/search-component/tailwind.config.js

UI still needs fix for auto scroll to work properly. Will need to be fixed in another PR.

feature: mobile view for search component

---

server/src/operators/chunk_operator.rs

bugfix: skip highlighting text when only 1 character needs highlights

---

frontends/dashboard/src/analytics/components/charts/CTRSearchQueries.tsx
frontends/dashboard/src/analytics/components/charts/CTRSummary.tsx
frontends/dashboard/src/analytics/components/charts/HeadQueries.tsx
frontends/dashboard/src/analytics/hooks/data/useCTRSearchQueries.ts
frontends/dashboard/src/analytics/hooks/data/useCTRSummary.tsx
frontends/dashboard/src/analytics/hooks/data/useHeadQueries.ts
frontends/dashboard/src/components/DatasetOverview.tsx
frontends/search/src/components/Atoms/Navbar.tsx
frontends/search/src/components/GroupPage.tsx
frontends/shared/ui/Pagination.tsx
frontends/shared/ui/TanStackTable.tsx

- Adds CSV export to CTR search queries
- Moves some more data fetching to hooks
- fixes top border on the table footer
related https://github.com/devflowinc/trieve/issues/2427

feat: add final CSV exports

---

server/src/bin/crawl-worker.rs
server/src/data/models.rs

feat: add dataset event types for crawl success/fail

---

frontends/dashboard/src/components/CodeExamples.tsx
frontends/dashboard/src/components/DatasetOverview.tsx
frontends/dashboard/src/utils/createCodeSnippets.tsx
frontends/search/src/components/Atoms/Navbar.tsx
frontends/search/src/components/GroupPage.tsx

closes https://github.com/devflowinc/trieve/issues/2456

feat: add TS instructions tab to get started code

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/ch_migrations/1727745063_add-rag-ratings/down.sql
server/ch_migrations/1727745063_add-rag-ratings/up.sql
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/handlers/chunk_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs
server/src/operators/message_operator.rs

feature: add rate rag route

---

.github/workflows/update-search-component.yaml
clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/AIInitalMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/index.css

Did a few minor style fixes and added a CI action to release on trigger.
I haven't made it auto release yet just in case it breaks and its annoying..

bugfix: resolve className conflict on .footer + ci: attempt for an auto release action

---

frontends/dashboard/src/components/CodeExamples.tsx

feature: add npm install command for trieve-ts-sdk in getting started tab

---

server/src/data/models.rs

bugfix: prevent unwrap error on analytics

---

clients/ts-sdk/package.json
clients/ts-sdk/src/functions/analytics/analytics.test.ts
clients/ts-sdk/src/functions/analytics/index.ts

Adds three new functions to SDK
When testing the last one I kept getting unauthorized, is there a specific API keyy type I need?

feat: add new alaytics functions to sdk

---

clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/utils/hooks/chat-context.tsx

Shows stop generating component in place of the clar chat while the AI is generating content
closes https://github.com/devflowinc/trieve/issues/2468

feature: Add stop generating button to chat component

---

clients/search-component/README.md

Thinking we can make a few hacktober issues around the search-component. Making a quickstart guide here

docs: created quickstart development for search-component in readme

---

.github/workflows/update-search-component.yaml
clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/trieve.ts

feature: clear chat history in search component

---

clients/search-component/src/TrieveModal/index.css

https://github.com/user-attachments/assets/a16fa0fd-b4ff-4aac-a13b-abd93747658b
hacky solution but it works.

styling: patch cut off chat messages

---

server/src/operators/message_operator.rs

feature: pass query id as a header on all rag messages

---

server/src/operators/message_operator.rs

feat: prefix TR-QueryID as X-TR-QueryID

---

server/src/lib.rs

bugfix: remove allowed_header prefix and set cors to allow any header

---

server/src/handlers/chunk_handler.rs

- **feat: add TR-QueryID to **ALL** llm response routes**
- **feature: generate off chunks pass TR QueryID**

feature: generate off chunks pass TR QueryID

---

frontends/dashboard/src/components/DatasetOverview.tsx
frontends/dashboard/src/hooks/useDatasetPages.ts

feature: add delete and clean dataset buttons to dashboard

---

frontends/dashboard/src/components/ApiKeyGenerateModal.tsx
frontends/dashboard/src/components/CodeExamples.tsx
frontends/dashboard/src/components/Codeblock.tsx
frontends/dashboard/src/pages/dataset/DatasetHomepage.tsx
frontends/dashboard/src/utils/createCodeSnippets.tsx

https://github.com/user-attachments/assets/99abca03-31a5-4350-9300-6a1a7b6d7753

feature: make request examples better

---

server/src/operators/dittofeed_operator.rs

feature: add track events for users

---

docker/collapse-query-script/collapse_queries.py

bugfix: dont collapse rag queries

---

server/src/handlers/auth_handler.rs
server/src/handlers/dataset_handler.rs
server/src/operators/dittofeed_operator.rs

feature: send to dittofeed on new user

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/analytics/api/analytics.ts
frontends/dashboard/src/analytics/api/tables.ts
frontends/dashboard/src/analytics/components/RecommendationsFilterBar.tsx
frontends/dashboard/src/analytics/components/SingleQueryInfo/index.tsx
frontends/dashboard/src/analytics/components/SingleRagInfo/index.tsx
frontends/dashboard/src/analytics/components/SingleRecommendationInfo/index.tsx
frontends/dashboard/src/analytics/hooks/data/useDataExplorerRecommendations.ts
frontends/dashboard/src/analytics/layouts/DataExplorerTabs.tsx
frontends/dashboard/src/analytics/pages/SingleRecommendationQueryPage.tsx
frontends/dashboard/src/analytics/pages/tablePages/RAGTablePage.tsx
frontends/dashboard/src/analytics/pages/tablePages/RecommendationsTablePage.tsx
frontends/dashboard/src/index.tsx
frontends/shared/types.ts
frontends/shared/ui/TanStackTable.tsx
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/operators/analytics_operator.rs
server/src/operators/user_operator.rs

feature: recommendations explorer

---

frontends/dashboard/src/analytics/components/SingleQueryInfo/ResultCard.tsx
frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx
frontends/dashboard/src/pages/dataset/DatasetHomepage.tsx

fix: metadata not showing in results

---

frontends/dashboard/src/analytics/components/RagAnalyticsGraphs.tsx
frontends/dashboard/src/analytics/components/charts/CTRSummary.tsx
frontends/dashboard/src/analytics/components/charts/NoResultQueries.tsx
frontends/dashboard/src/analytics/components/charts/QueryCounts.tsx
frontends/dashboard/src/analytics/components/charts/RAGUsageGraph.tsx
frontends/dashboard/src/analytics/components/charts/SearchUsageGraph.tsx
frontends/dashboard/src/analytics/pages/SearchAnalyticsPage.tsx
frontends/dashboard/src/analytics/pages/tablePages/RAGAnalyticsPage.tsx
frontends/dashboard/src/analytics/pages/tablePages/RecommendationsTablePage.tsx
frontends/dashboard/src/analytics/pages/tablePages/SearchTable.tsx
frontends/dashboard/src/components/Sidebar.tsx
frontends/dashboard/src/index.tsx
frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx
frontends/shared/ui/DateRangePicker.tsx
frontends/shared/ui/TanStackTable.tsx
server/src/data/models.rs

feat: move search analytics to data explorer

---

frontends/dashboard/src/analytics/pages/SearchAnalyticsPage.tsx
frontends/dashboard/src/analytics/pages/tablePages/RAGAnalyticsPage.tsx

cleanup: moved the graphs above the tables in data explorer

---

server/src/handlers/dataset_handler.rs
server/src/operators/dittofeed_operator.rs

- **bugfix: navbar not showing up on search playground**
- **cleanup: do not error creating dataset is ditto req fails**

cleanup: do not error on dataset create if ditto fails

---

frontends/dashboard/src/analytics/components/SingleQueryInfo/DataSquare.tsx
frontends/dashboard/src/analytics/components/SingleRagInfo/index.tsx
frontends/dashboard/src/analytics/pages/SearchAnalyticsPage.tsx
frontends/dashboard/src/analytics/pages/tablePages/RAGAnalyticsPage.tsx

cleanup: make tables first in analytics tabs

---

frontends/search/src/components/ScoreChunk.tsx
server/src/operators/crawl_operator.rs

cleanup: put scrape config so scrape triggers on update

---

clients/search-component/src/TrieveModal/Search/item.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/useSuggestedQueries.ts

feature: style openapi req verbs

---

server/src/handlers/metrics_handler.rs

chore: update metrics_handler.rs

---

frontends/search/src/components/Atoms/AfMessage.tsx
frontends/search/src/components/CTRPopup.tsx
frontends/search/src/components/ChatPopup.tsx
frontends/search/src/components/ChunkMetadataDisplay.tsx
frontends/search/src/components/GroupPage.tsx
frontends/search/src/components/ResultsPage.tsx
frontends/search/src/components/ScoreChunk.tsx
frontends/search/src/components/SingleChunkPage.tsx
frontends/search/src/hooks/useCtrAnalytics.ts
frontends/search/src/utils/cls.ts

closes https://github.com/devflowinc/trieve/issues/2460

feature: button on search playground UI to "register a click"

---

frontends/chat/package.json
frontends/chat/src/components/Atoms/AfMessage.tsx
frontends/chat/src/components/Atoms/MessageVoting.tsx
frontends/chat/src/components/Layouts/MainLayout.tsx
frontends/chat/src/types/messages.ts
frontends/dashboard/src/analytics/components/SingleRagInfo/index.tsx
frontends/dashboard/src/analytics/pages/tablePages/RAGAnalyticsPage.tsx
server/src/data/models.rs
server/src/handlers/message_handler.rs
server/src/operators/message_operator.rs
yarn.lock

feat: show votes on chat SPA and analytics dashboard

---

clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx

feature: add prices and images to ecomm chat

---

frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx

feat: add group products checkmark to crawl settings

---

clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx

feature: prevent switching modes

---

server/src/operators/model_operator.rs

Requests were getting stalled out and causing the server to not respond to health checks under heavy search load.

bugfix: create embeddings on non receiving thread

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/functions/analytics/index.ts
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/analytics/api/analytics.ts
frontends/dashboard/src/analytics/api/tables.ts
frontends/dashboard/src/analytics/components/EventFilterBar.tsx
frontends/dashboard/src/analytics/components/SingleEventInfo/index.tsx
frontends/dashboard/src/analytics/components/SingleRagInfo/index.tsx
frontends/dashboard/src/analytics/hooks/data/useDataExplorerEvents.ts
frontends/dashboard/src/analytics/layouts/DataExplorerTabs.tsx
frontends/dashboard/src/analytics/pages/SingleEventQueryPage.tsx
frontends/dashboard/src/analytics/pages/tablePages/EventsTablePage.tsx
frontends/dashboard/src/components/Sidebar.tsx
frontends/dashboard/src/index.tsx
frontends/shared/types.ts
frontends/shared/ui/TanStackTable.tsx
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: event data explorer

---

frontends/chat/src/components/Layouts/MainLayout.tsx
frontends/dashboard/src/components/NewDatasetModal.tsx
server/src/data/models.rs
server/src/handlers/group_handler.rs
server/src/handlers/message_handler.rs
server/src/operators/message_operator.rs

feature: allow rag to use group search w/ a size of 1

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/functions/events/index.ts
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/analytics/hooks/data/useDataExplorerSearch.ts
frontends/dashboard/src/analytics/pages/tablePages/EventsTablePage.tsx
frontends/dashboard/src/components/Sidebar.tsx
frontends/dashboard/src/pages/dataset/Events.tsx
frontends/shared/types.ts
frontends/shared/ui/Pagination.tsx
frontends/shared/ui/TanStackTable.tsx
server/src/data/models.rs
server/src/handlers/chunk_handler.rs
server/src/handlers/event_handler.rs
server/src/handlers/group_handler.rs
server/src/lib.rs
server/src/operators/event_operator.rs
server/src/operators/message_operator.rs

feature: get all event types + bugfix: escape quotes properly for analytics

---

frontends/dashboard/src/analytics/components/SingleEventInfo/index.tsx
frontends/dashboard/src/analytics/components/SingleQueryInfo/DataSquare.tsx
frontends/shared/types.ts
server/ch_migrations/1729022689_add_request_type/down.sql
server/ch_migrations/1729022689_add_request_type/up.sql
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: link custom events to actual events

---

frontends/dashboard/src/analytics/components/SingleQueryInfo/ResultCard.tsx
frontends/dashboard/src/analytics/components/SingleQueryInfo/index.tsx
frontends/shared/types.ts

bugfix: fix viewing group search results in query details

---

README.md

There is spelling mistake of (assistance) in readme file .

corrected the typos error in readme file

---

clients/docusaurus-theme-search/package.json
clients/docusaurus-theme-search/yarn.lock
clients/search-component/package.json
clients/search-component/src/TrieveModal/index.css

feature: use correct color theming for search component

---

clients/docusaurus-theme-search/example/docusaurus.config.js
clients/docusaurus-theme-search/example/package.json
clients/docusaurus-theme-search/example/yarn.lock
clients/docusaurus-theme-search/package.json
clients/docusaurus-theme-search/yarn.lock
clients/search-component/README.md
clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/package.json
clients/search-component/src/TrieveModal/OpenModalButton.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/modal-context.tsx

Add new parameter for `responsive` to shrink the component down to just a search button.

feature: responsive search modal button have a responsive flag to shrink

---

server/src/bin/crawl-worker.rs

bugfix: fix crawl duplicates from www vs non www

---

clients/docusaurus-theme-search/example/docusaurus.config.js
clients/docusaurus-theme-search/example/package.json
clients/docusaurus-theme-search/package.json
clients/docusaurus-theme-search/yarn.lock
clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/package.json
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/hooks/useSuggestedQueries.ts

Add parameter for `debounceMs`

feature: debounce parameter for modal

---

clients/docusaurus-theme-search/LICENSE
clients/docusaurus-theme-search/package.json
clients/search-component/LICENSE
clients/search-component/package.json

chore: add LICENSE for components in package.json and in folder

---

frontends/dashboard/src/components/CodeExamples.tsx
frontends/dashboard/src/utils/createCodeSnippets.tsx

feat: add search component example code

---

server/.gitignore
server/ch_migrations/1724365354_create_events_table/down.sql
server/ch_migrations/chm.toml
server/src/operators/analytics_operator.rs
server/src/operators/clickhouse_operator.rs
server/src/operators/dataset_operator.rs
server/src/operators/event_operator.rs

Some code tried to use `default.*` tables even when `CLICKHOUSE_DB` is different.

fix(clickhouse): do not force `default` database

---

clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/Search/item.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts
clients/search-component/src/utils/types.ts
docker-compose-firecrawl.yml
frontends/dashboard/src/components/Routes.ts
server/src/bin/crawl-worker.rs

feature: group search in component

---

server/src/operators/message_operator.rs

feature: send json blobs to llm for better parsing

---

clients/docusaurus-theme-search/example/yarn.lock
clients/docusaurus-theme-search/package.json
clients/docusaurus-theme-search/src/theme/SearchBar/index.jsx
clients/docusaurus-theme-search/yarn.lock
clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/OpenModalButton.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/useKeyboardNavigation.ts
clients/search-component/src/utils/hooks/useSuggestedQueries.ts
yarn.lock

Lazy Load search component to reduce total page size.

feature: lazy load search component

---

server/src/handlers/mod.rs
server/src/handlers/webhook_handler.rs
server/src/lib.rs
server/src/operators/mod.rs
server/src/operators/webhook_operator.rs

feat: builder.io content sync

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
docker-compose-firecrawl.yml
frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx
server/src/data/models.rs
server/src/handlers/dataset_handler.rs

- **cleanup: require non star include URL for external URLs**
- **cleanup: remove max depth as a crawl option field**

cleanup: remove max depth as a crawl option field

---

server/src/bin/crawl-worker.rs

bugfix: remove trailing slahes from URLs when processing a crawl

---

frontends/dashboard/src/pages/OrgSelect.tsx

prevents a softlock when you delete your only org

feat: new org modal in org select page

---

clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/package.json
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts
clients/search-component/src/utils/types.ts
clients/ts-sdk/package.json

- **v0.0.52**
- **v0.0.14**
- **cleanup: allow user to opt out of autocomplete search mode**

feature add search component prop to avoid using autocomplete

---

clients/search-component/src/TrieveModal/index.css

- **v0.0.52**
- **v0.0.14**
- **cleanup: fix floating effect below bottom nav on search-component**

cleanup: floating pb on search component

---

frontends/dashboard/src/analytics/components/SingleQueryInfo/ResultCard.tsx

fix: metadata in result card nested too deeply

---

clients/search-component/src/utils/hooks/modal-context.tsx

feature: add open and onOpenChange as params for search component

---

server/src/bin/delete-worker.rs
server/src/handlers/chunk_handler.rs
server/src/handlers/message_handler.rs
server/src/lib.rs
server/src/operators/chunk_operator.rs
server/src/operators/dataset_operator.rs
server/src/operators/qdrant_operator.rs

```bash
curl --request DELETE \
--url http://localhost:8090/api/chunk \
--header 'Authorization: admin' \
--header 'Content-Type: application/json' \
--header 'TR-Dataset: 502240bb-4a39-487e-b6cd-32b4ff0d6d6c' \
--header 'User-Agent: insomnia/9.3.3' \
--data '{
"filter": {
"must": [
{
"field": "tag_set",
"match": [
"Type: Stitched"
]
}
]
}
}'
```

feature: bulk delete chunks

---

frontends/chat/package.json
frontends/dashboard/src/components/ApiKeys.tsx
frontends/dashboard/src/components/NewDatasetModal.tsx
frontends/dashboard/src/components/dataset-settings/GeneralSettings.tsx
frontends/dashboard/src/components/dataset-settings/LLMSettings.tsx
frontends/dashboard/src/components/dataset-settings/LegacySettingsWrapper.tsx
frontends/dashboard/src/index.css
frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
frontends/search/src/components/BookmarkPopover.tsx
frontends/search/src/components/CTRPopup.tsx
frontends/search/src/components/ScoreChunk.tsx
frontends/search/src/components/SearchForm.tsx
frontends/search/src/index.css
frontends/shared/ui/SelectBox.tsx
frontends/shared/ui/Tooltip.tsx

Changes tooltip to automatically position itself in the window to not get cut off. 
Fade in animation and optional delay. 
Uses solid portal so its always on top of things

feat: better tooltip component

---

frontends/dashboard/src/components/dataset-settings/GeneralSettings.tsx
frontends/dashboard/src/components/dataset-settings/LLMSettings.tsx

enhancement: move documents to include for rag setting to llm settings

---

frontends/dashboard/src/components/dataset-settings/LegacySettingsWrapper.tsx
frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx

cleanup: ensure save button for dataset settings is visible

---

frontends/chat/src/components/Layouts/MainLayout.tsx

- **cleanup: tell the user how to change more params for RAG in the dashboard**

cleanup: document how to change system prompt and other RAG settings in dashboard

---

clients/search-component/package.json
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts

- **bugfix: default params for search component**

bugfix: default params for search component

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/analytics/utils/schemas/autocomplete.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
frontends/shared/ui/JsonInput.tsx
server/src/handlers/page_handler.rs
server/src/lib.rs
server/src/public/page.html

fix: multistring input for default questions on public page

---

server/src/handlers/auth_handler.rs

ops: clarify auto scaling email

---

server/src/handlers/page_handler.rs
server/src/public/page.html

feat: public page back button

---

frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

styling: use select box for color theme

---

server/src/handlers/auth_handler.rs
server/src/handlers/chunk_handler.rs

docs: better error message for recommendations

---

clients/search-component/src/TrieveModal/index.css

Current:
Progress:
Current:
Progress:

feature: refactor css to remove border

---

clients/search-component/package.json
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/public/page.html

Adds all the props from the search component.
Also adds tooltips to the inputs.

feat: advanced controls for public page settings

---

clients/docusaurus-theme-search/package.json
clients/search-component/package.json
clients/trieve-fumadocs-adapter/package.json

fix: update version ranges to allow react 19

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs

bugfix: modify public page types to correct values

---

.github/workflows/push-clickhouse.yml
.github/workflows/push-clustering-script.yml
.github/workflows/push-collapse-query-script.yml
.github/workflows/push-frontends.yml
.github/workflows/push-server.yml
.github/workflows/workflow-release.yml

ops: switch to blacksmith push action

---

server/src/data/models.rs
server/src/handlers/invitation_handler.rs

bugfix: prevent duplicate users in orgs

---

frontends/dashboard/src/components/NewDatasetModal.tsx
frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx
frontends/shared/ui/SelectBox.tsx

styling: keep tooltips consistent in crawling settings

---

server/src/operators/email_operator.rs
server/src/operators/invitation_operator.rs

enhancement: improve organization email template

---

clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/index.css

styling: ecommerce mode

---

server/src/bin/crawl-worker.rs

Send chunks as you go so that the scrape feels snappier when using the Shopify crawling option

enhancement: speed up shopify scraping by pushing chunks into the queue as you go

---

clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/index.css

cleanup: reposition mode switch

---

clients/search-component/example/src/routes/ecommerce.tsx
clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/src/TrieveModal/Search/ProductGroupItem.tsx
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/types.ts

feature: deduplicate product variants for shopify component.

---

server/src/public/page.html

feature: open the search component by default

---

clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/__tests__/constants.ts
clients/ts-sdk/src/functions/index.ts
clients/ts-sdk/src/functions/user/index.ts
clients/ts-sdk/src/functions/user/user.test.ts
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/analytics/utils/schemas/autocomplete.ts
frontends/dashboard/src/components/ApiKeyGenerateModal.tsx
server/migrations/2024-11-13-003245_add_api_key_params_and_expiry/down.sql
server/migrations/2024-11-13-003245_add_api_key_params_and_expiry/up.sql
server/src/data/models.rs
server/src/data/schema.rs
server/src/handlers/user_handler.rs
server/src/lib.rs
server/src/middleware/auth_middleware.rs
server/src/operators/user_operator.rs

feature: add api key params and expiration

---

server/Dockerfile.bktree-worker
server/Dockerfile.bulk-ingest-worker
server/Dockerfile.clone-qdrant
server/Dockerfile.crawl-cron-job
server/Dockerfile.crawl-worker
server/Dockerfile.delete-worker
server/Dockerfile.dittofeed-sync-worker
server/Dockerfile.file-worker
server/Dockerfile.group-worker
server/Dockerfile.ingestion-worker
server/Dockerfile.pg-worker
server/Dockerfile.queue-bm25
server/Dockerfile.reindex-worker
server/Dockerfile.server
server/Dockerfile.sync-qdrant
server/Dockerfile.word-id-cronjob
server/Dockerfile.word-worker
server/src/lib.rs

bump: update rust version to 1.81

---

clients/search-component/README.md
clients/search-component/package.json
clients/search-component/scripts/build.js
clients/search-component/scripts/watch.js
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/index.ts
clients/search-component/src/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/tsconfig.json
yarn.lock

feat: smaller search component package

---

server/src/public/page.html

feat: fast load public page

---

clients/search-component/README.md
clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/public/page.html
yarn.lock

feature: add type + groupSearch as options to public page config

---

clients/search-component/src/utils/hooks/modal-context.tsx

feat: shortcut to toggle component modes

---

frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

feature: add open in new window button for public page

---

clients/search-component/src/utils/hooks/modal-context.tsx

fix: change shortcut to ctrl-tab

---

clients/search-component/README.md
clients/search-component/package.json
clients/search-component/scripts/build.js
clients/search-component/scripts/watch.js
clients/search-component/src/index.tsx
clients/search-component/src/styles.d.ts
clients/search-component/src/vanilla.tsx
clients/search-component/src/vanilla/index.tsx
server/src/public/page.html

feat: vanilla js + css styles package for search component

---

.gitignore
docker-compose.yml
file-chunker/ch_migrations/chm.toml
server/src/data/models.rs
server/src/handlers/group_handler.rs
server/src/operators/message_operator.rs
server/src/operators/qdrant_operator.rs
server/src/operators/search_operator.rs

SEARCH OVER GROUPS WILL NOT WORK WITH QDRANT < 12.1

feature: add sort to search over groups

---

server/src/public/page.html

docs: change style import example on public page

---

server/src/handlers/chunk_handler.rs

fix: mispelled "heading"

---

frontends/dashboard/src/analytics/api/analytics.ts
frontends/dashboard/src/analytics/components/charts/QueryCounts.tsx
frontends/dashboard/src/analytics/pages/AnalyticsOverviewPage.tsx

feat: custom date picker for analytics overview

---

server/src/operators/clickhouse_operator.rs

nit: skip logging error if Analytics is disabled

---

server/src/errors.rs
server/src/middleware/metrics_middleware.rs
server/src/middleware/timeout_middleware.rs
server/src/operators/clickhouse_operator.rs

- **nit: skip logging error if Analytics is disabled**
- **bugfix: make timeout error respond with json**
- **bugfix: log errors into prom metrics**

bugfix: make request timeouts respond with json, bugfix: make prom middleware report on Err and Ok response codes

---

pdf2md/cli/src/operators/create_task.rs
pdf2md/server/src/lib.rs
pdf2md/server/src/middleware/api_key_middleware.rs
pdf2md/server/src/routes/create_task.rs
pdf2md/server/src/routes/jinja_templates.rs
pdf2md/server/src/templates/demo-ui.html
pdf2md/server/src/templates/skeleton.html
pdf2md/server/static/output.css
pdf2md/server/static/pdf2md.js
pdf2md/server/tailwind.config.js

feature: skeleton upload form for pdf2md

---

pdf2md/server/static/pdf2md.js

feature: working API req on file form add

---

server/src/middleware/timeout_middleware.rs

ops: make emails a flag to turn off

---

pdf2md/server/ch_migrations/chm.toml
pdf2md/server/src/models.rs
pdf2md/server/src/operators/clickhouse.rs
pdf2md/server/src/operators/pdf_chunk.rs
pdf2md/server/src/workers/chunk-worker.rs
pdf2md/server/src/workers/supervisor-worker.rs

feature: add advanced options and usage metrics to each chunk

---

pdf2md/server/ch_migrations/1731971460_add_file_name_to_file_tasks/down.sql
pdf2md/server/ch_migrations/1731971460_add_file_name_to_file_tasks/up.sql
pdf2md/server/src/models.rs
pdf2md/server/src/routes/create_task.rs
pdf2md/server/src/templates/demo-ui.html
pdf2md/server/src/templates/skeleton.html
pdf2md/server/static/output.css
pdf2md/server/static/pdf2md.js

feature: add table for tracking tasks

---

pdf2md/server/src/models.rs
pdf2md/server/src/operators/clickhouse.rs
pdf2md/server/src/operators/s3.rs
pdf2md/server/src/routes/get_task.rs
pdf2md/server/src/workers/chunk-worker.rs
pdf2md/server/src/workers/supervisor-worker.rs
server/src/bin/file-worker.rs
server/src/handlers/file_handler.rs
server/src/operators/file_operator.rs

feature: get signed url for pdf

---

.github/workflows/push-pdf2md-server.yml
file-chunker/ch_migrations/chm.toml

ops/chore: fix broken CI action

---

pdf2md/server/src/lib.rs

bugfix: make pdf2md bind to host port

---

server/src/bin/file-worker.rs

feature: file-worker to poll and get all chunks

---

pdf2md/server/src/errors.rs
pdf2md/server/src/models.rs
pdf2md/server/src/operators/clickhouse.rs
pdf2md/server/src/operators/mod.rs
pdf2md/server/src/operators/pdf_chunk.rs
pdf2md/server/src/operators/webhook_template.rs
pdf2md/server/src/workers/supervisor-worker.rs

feature: add webhooks

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/Tags.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/chat-context.tsx

feature: include tags for rag

---

pdf2md/README.md
pdf2md/k8s/api.yaml
pdf2md/k8s/chunk-worker.yaml
pdf2md/k8s/configmap.yaml
pdf2md/k8s/ingress.yaml
pdf2md/k8s/supervisor-worker.yaml

docs(pdf2md): create k8s hosting

---

clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/functions/message/index.ts
clients/ts-sdk/src/types.gen.ts
server/src/handlers/message_handler.rs
server/src/handlers/topic_handler.rs
server/src/lib.rs
server/src/operators/message_operator.rs

feature: add route to get message by id

---

pdf2md/server/src/models.rs
pdf2md/server/src/templates/demo-ui.html
pdf2md/server/src/templates/skeleton.html
pdf2md/server/static/output.css
pdf2md/server/static/pdf2md.js

Other updates: 
- increase max width to `max-w-screen-2xl`
- add link to api reference
- make logo go back to home instead of trieve.ai

feature: include advanced options form for pdf2md

---

pdf2md/server/src/templates/demo-ui.html
pdf2md/server/static/pdf2md.js

feature: add token usage to pdf2md ui

---

pdf2md/server/Dockerfile.pdf2md-server
pdf2md/server/Dockerfile.supervisor-worker

feat(pdf2md): update all docker images to have poppler

---

pdf2md/server/src/workers/supervisor-worker.rs

bugfix: skip first page of rendered images

---

server/src/bin/file-worker.rs

feature: update fileworker to receive the correct response type

---

frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

feat: default to useGroupSearch for public page on shopify datasets

---

frontends/chat/src/components/ScoreChunk.tsx
frontends/chat/src/utils/apiTypes.ts
frontends/search/src/components/ScoreChunk.tsx

feature: rearrange images to display horizontally and make the section collapsable

---

frontends/dashboard/src/components/dataset-settings/LLMSettings.tsx

feature: dropdown menu for OpenAI/OpenRouter in LLM settings

---

server/src/bin/crawl-worker.rs

feature: make shopify scraping handle null valeus in products.json, fix links to not have 2 trailing slashes

---

server/src/bin/crawl-worker.rs
server/src/data/models.rs

enhancement: send an event that scraping has started

---

server/src/handlers/invitation_handler.rs
server/src/operators/invitation_operator.rs

feature: include organization url in invitation email to existing users

---

clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
frontends/chat/src/components/Atoms/AfMessage.tsx
frontends/chat/src/components/Layouts/MainLayout.tsx
server/src/data/models.rs
server/src/handlers/message_handler.rs
server/src/operators/message_operator.rs

feature: add fall back response if there is no chunks above the score threshold

---

frontends/dashboard/src/components/dataset-settings/LLMSettings.tsx

bugfix: typo in tooltip

---

server/Dockerfile.ingestion-worker
server/Dockerfile.server

bugfix: fix broken Dockerfile, update subtrace version

---

clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/functions/index.ts
clients/ts-sdk/src/functions/organization/index.ts
clients/ts-sdk/src/functions/organization/organization.test.ts
clients/ts-sdk/src/functions/user/index.ts
clients/ts-sdk/src/functions/user/user.test.ts
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/ApiKeyGenerateModal.tsx
frontends/dashboard/src/components/ApiKeys.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/Dockerfile.ingestion-worker
server/Dockerfile.server
server/migrations/2024-11-21-215958_organization_api_key/down.sql
server/migrations/2024-11-21-215958_organization_api_key/up.sql
server/src/bin/crawl-worker.rs
server/src/data/models.rs
server/src/data/schema.rs
server/src/handlers/organization_handler.rs
server/src/handlers/user_handler.rs
server/src/lib.rs
server/src/middleware/auth_middleware.rs
server/src/operators/organization_operator.rs
server/src/operators/user_operator.rs

- **feature: scope api keys to orgs**
- **bugfix: fix api key role not being set correctly**
- **bugfix: fix api key role not being set correctly**

feature: scope api keys to orgs instead of users

---

pdf2md/server/src/routes/create_task.rs

feat(pdf2md): make LLM provider be the default chunking provider

---

clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/HeroPatterns.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
pdf2md/server/static/output.css
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/lib.rs
server/src/public/page.html

feature: add hero pattern background to public page

---

frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/public/page.html

feat: add navbar to public page

---

clients/ts-sdk/src/__tests__/constants.ts
clients/ts-sdk/src/functions/organization/organization.test.ts
server/migrations/2024-11-28-041452_add_on_delete_cascade_for_org_api_key/down.sql
server/migrations/2024-11-28-041452_add_on_delete_cascade_for_org_api_key/up.sql
server/src/operators/organization_operator.rs

bugfix: fix tests and ensure that expires at functionality works correctly

---

frontends/dashboard/src/contexts/UserContext.tsx

feat: save org in query params on dashboard

---

frontends/search/src/components/ResultsPage.tsx
frontends/search/src/components/SearchForm.tsx
frontends/search/src/hooks/useSearch.ts
server/src/data/models.rs
server/src/handlers/message_handler.rs
server/src/lib.rs
server/src/operators/chunk_operator.rs
server/src/operators/message_operator.rs
server/src/operators/qdrant_operator.rs
server/src/operators/search_operator.rs

feature: add MMR support

---

clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
frontends/search/src/components/FilterModal.tsx
frontends/search/src/components/SearchForm.tsx
frontends/search/src/hooks/useSearch.ts
pdf2md/server/static/output.css
server/src/data/models.rs
server/src/handlers/chunk_handler.rs
server/src/operators/search_operator.rs

feat: add match_all to search playground filter options + remove jsonb_prefilter

---

frontends/search/src/components/BookmarkPopover.tsx
frontends/search/src/components/GroupPage.tsx
frontends/search/src/components/ResultsPage.tsx
frontends/search/src/components/SearchForm.tsx
frontends/search/src/utils/apiTypes.ts
server/src/data/models.rs
server/src/operators/search_operator.rs

- **feature: allow editing a group's tag_set and tracking_id via search playground**
- **cleanup: return 0 results when there are matching groups for a given set of tracking_id filters instead of erroring**

cleanup: group tracking_id filter system

---

server/src/bin/crawl-worker.rs
server/src/bin/ingestion-worker.rs
server/src/data/models.rs
server/src/handlers/chunk_handler.rs
server/src/handlers/webhook_handler.rs
server/src/operators/chunk_operator.rs
server/src/operators/file_operator.rs
server/src/operators/webhook_operator.rs

- **feature: skip creating groups in chunk_handler**
- **cleanup: remove ChunkDataWithEmbeddingText**
- **feature: upsert_group_tracking_id's in ingestion worker**

feature: create groups in ingestion worker instead of handler

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/index.css
server/src/public/page.html

Before: 
After: ![image](https://github.com/user-attachments/assets/7c15692c-fc07-4a3f-8ec8-8672a91488fa)

fix: safari component height

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/lib.rs
server/src/public/navbar.html
server/src/public/page.html
server/static/output.css

feat: open graph and alternate chat image for public page

---

server/Dockerfile.ingestion-worker
server/Dockerfile.server

feature: subtrace version bump

---

frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

fix: change text for brand logo link

---

helm/Chart.yaml
helm/templates/backend-configmap.yaml
helm/values.yaml

feature: add initCollections parameter to helm chart

---

.env.server
helm/templates/backend-configmap.yaml
helm/values.yaml
server/src/errors.rs
server/src/middleware/timeout_middleware.rs
server/src/operators/message_operator.rs

bugfix: timeout long standing or failed chat completions

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/index.css
server/src/public/page.html

bugfix: fix vertical scroll in search component

---

.github/workflows/push-server.yml
helm/templates/csv-jsonl-worker.yaml
helm/values.yaml

ci: CSV JSONL worker image named correctly, update helm chart to work with csv-jsonl-worker

---

server/Dockerfile.csv-jsonl-worker
server/src/bin/csv-jsonl-worker.rs

feautre: add subtrace to jsonl worker

---

hallucination-detection/Cargo.lock
hallucination-detection/Cargo.toml
hallucination-detection/README.md

cleanup: updated readme

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/dataset-settings/GeneralSettings.tsx
server/src/data/models.rs
server/src/handlers/chunk_handler.rs
server/src/handlers/group_handler.rs
server/src/operators/message_operator.rs

feature: disable analytics flag

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/icons.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/modal-context.tsx
server/src/public/page.html

- **cleanup: search-component copy now green + powered by trieve at bottom with empty tag row when no tags + ctrl+m to swap modes**
- **v0.2.9**

cleanup: lint public page powered by + keyboard shortcut fix

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Search/DocsItem.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/Dockerfile.server
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/public/page.html

feature: add openLinksInNewTab as a new parameter for the search component and public page

---

server/Dockerfile.server

ci: fix broken Dockerfile

---

.github/workflows/update-trieve-fern-adapter.yaml
clients/trieve-fern-adapter/.npmignore
clients/trieve-fern-adapter/LICENSE
clients/trieve-fern-adapter/README.md
clients/trieve-fern-adapter/package.json
clients/trieve-fern-adapter/src/index.ts
clients/trieve-fern-adapter/tsconfig.json
clients/trieve-fern-adapter/yarn.lock

@skeptrunedev 
CI Usage inside Vapi docs:
https://github.com/devflowinc/vapi-docs/pull/1

feat: adds cd for fern adapter

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/index.css
clients/trieve-fern-adapter/package.json
clients/trieve-fern-adapter/src/index.ts
server/src/public/page.html

- cleanup: add tracking_ids's to fern adapter chunk creation
- styling: search-component increased width and small lints on bottom row padding + loading animation

cleanup: add tracking_ids's to fern adapter chunk creation

---

frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

fix: public page tooltip text

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/trieve.ts
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/hooks/usePublicPageSettings.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/lib.rs
server/src/operators/dataset_operator.rs
server/src/public/navbar.html
server/src/public/page.html
server/static/output.css

- **v0.2.13**
- **v0.0.42**
- **v0.2.14**
- **v0.2.15**
- **feature: add score threshold, author, increase width, and other search component improvements**

feature: various search component improvements

---

server/src/operators/qdrant_operator.rs

bugfix: remove unwrap error parsing uuid

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/chat-context.tsx
server/src/handlers/chunk_handler.rs
server/src/public/page.html
server/src/public/product.html
server/src/public/tabs.html
server/static/output.css

- **bugfix: mobile tabs for demo page horizontally scroll now**
- **cleanup: scroll and missing user message**

bugfix: tabs scroll and missing user message

---

server/src/public/page.html
server/src/public/search-component-code.html

feature: update version on public page, modify instructions to createElement as the default

---

.github/workflows/push-server.yml
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/CrawlingSettings.tsx
helm/templates/video-worker-deployment.yaml
server/Cargo.lock
server/Cargo.toml
server/Dockerfile.video-worker
server/src/bin/video-worker.rs
server/src/data/models.rs
server/src/handlers/dataset_handler.rs
server/src/lib.rs
server/src/operators/crawl_operator.rs

feature: add video worker

---

clients/search-component/package.json
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts
clients/trieve-fern-adapter/src/index.ts
clients/ts-sdk/package.json
clients/ts-sdk/src/fetch-client.ts
clients/ts-sdk/src/functions/analytics/index.ts
clients/ts-sdk/src/functions/chunks/index.ts
clients/ts-sdk/src/functions/events/index.ts
clients/ts-sdk/src/functions/file/index.ts
clients/ts-sdk/src/functions/groups/index.ts
clients/ts-sdk/src/functions/message/index.ts
clients/ts-sdk/src/functions/topic/index.ts
clients/ts-sdk/src/sdk.ts
frontends/dashboard/src/utils/createCodeSnippets.tsx

- **feature: add video link field to public page settings + ts sdk**
- **feature: add video embed to public page template**
- **cleanup: fix ordering on public page + tooltip**
- **bugfix: ts-sdk default behavior with omitCredentials includes them**
- **v0.0.47**
- **v0.0.48**
- **v0.2.32**
- **cleanup: add omitCredentials option + make datasetId optional in ts-sdk**

bugfix: credentials include issue for dashboard

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/AIInitalMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/public/page.html
server/src/public/product.html

- **bugfix: ts-sdk default behavior with omitCredentials includes them**
- **cleanup: add omitCredentials option + make datasetId optional in ts-sdk**
- **v0.2.33**
- **v0.2.34**
- **styling: add rounded mode to eCommerce search and option to hide drawn text**

styling: add rounded mode to eCommerce search

---

server/Cargo.lock
server/Cargo.toml
server/src/bin/video-worker.rs
server/src/operators/crawl_operator.rs

cleanup: upgrade broccoli version

---

server/src/handlers/page_handler.rs

feature: change default SEARCH_COMPONENT_URL

---

helm/Chart.yaml
server/src/operators/invitation_operator.rs

- **feature: change default SEARCH_COMPONENT_URL**
- **bugfix: use to_lowercase for email validation**

bugfix: invite email validation to be case insensitive

---

frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

feature: replace the slider with an input

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/Carousel.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/FloatingSearchInput.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/hooks/useKeyboardNavigation.ts
clients/search-component/src/utils/hooks/useSuggestedQueries.ts
clients/search-component/src/utils/trieve.ts
clients/search-component/tsconfig.json
server/src/public/navbar.html
server/static/output.css
yarn.lock

- **v0.2.47**
- **v0.2.48**
- **v0.2.49**
- **cleanup: search component browser compat issues**
- **feature: make button enter when input is populated instead of clear**

cleanup: search component browser compat issues + enter button

---

server/src/bin/delete-worker.rs
server/src/operators/dataset_operator.rs

These queries  (mainly deleting `dataset_events`) causes a lot of stress on clickhouse, they are not important to keep, if the table grows to the point we have to deal with it that is a good problem to have

feat: dont delete tables from clickhouse on dataset delete

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/setClickTriggers.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/public/navbar.html
server/src/public/page.html
server/src/public/product.html
server/static/output.css

[Screencast from 12-27-2024 03:12:34 PM.webm](https://github.com/user-attachments/assets/6f1e1cfd-afa4-4f6a-ad6d-48b996c917ee)

feat: similar/different recs on demo page

---

.github/workflows/frontend-tests.yml
frontends/dashboard/src/components/dataset-settings/LLMSettings.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

cleanup: reset to default key when provider URL changes

---

clients/ts-sdk/src/functions/message/message.test.ts

fix: message edit tests

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/TrieveModal/index.css

feat: use placeholder for image loading

---

clients/search-component/src/TrieveModal/index.css
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/public/page.html

feature: add Testing mode for public page

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/useSuggestedQueries.ts

- **bugfix: fix suggested queries**
- **bugfix: fix window height bug**

bugfix: fix suggested queries, and fix window height bug

---

clients/search-component/src/TrieveModal/Chat/AIInitalMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/FollowupQueries.tsx
clients/search-component/src/TrieveModal/FloatingActionButton.tsx
clients/search-component/src/TrieveModal/ModeSwitch.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/icons.tsx
clients/search-component/src/TrieveModal/index.css
server/src/public/page.html

cleanup: replace wand with sparkles svg, increase rounding for ask AI and tab buttons

---

clients/mcp-server/.gitignore
clients/mcp-server/README.md
clients/mcp-server/package.json
clients/mcp-server/src/index.ts
clients/mcp-server/src/types.ts
clients/mcp-server/tsconfig.json
clients/mcp-server/vitest.config.ts
package.json
yarn.lock

https://github.com/user-attachments/assets/eea0de5f-d030-4bd2-99ac-dd4db104a8d8
This PR implements a Model Context Protocol (MCP) server for Trieve, enabling AI agents to use Trieve datasets as a retrieval source. The server provides a standardized interface for AI agents to search and interact with Trieve datasets through the MCP protocol.
- **Dataset Access**: List and access Trieve datasets from dashboard.trieve.ai
- **Search Integration**: Semantic, fulltext, hybrid, and BM25 search across datasets
- **Advanced Filtering**: Support for metadata filtering and tag-based search
- **Highlighting**: Configurable result highlighting with score thresholds
- **Environment Management**: Simple configuration via env vars or CLI args
- New TypeScript-based MCP server in `clients/mcp-server`
- …

feat(mcp-server): implement MCP server for Trieve API

---

server/src/bin/video-worker.rs

Seems like there is a deserialization error happening on a few YouTube videos. Not sure the true source, could be a content policy that YouTube or just that YouTube doesn't have a transcript for those videos. 
Best workaround now is to at least make sure it won't kill the whole job and that all transcribe-able videos are transcribed and ingested.

feature: don't quit video worker job if a single video fails

---

server/src/data/models.rs
server/src/handlers/chunk_handler.rs
server/src/handlers/group_handler.rs
server/src/handlers/message_handler.rs
server/src/lib.rs
server/src/operators/message_operator.rs
server/src/operators/search_operator.rs
server/src/operators/typo_operator.rs

feature: add image search

---

frontends/dashboard/src/contexts/UserContext.tsx
server/src/handlers/invitation_handler.rs
server/src/operators/invitation_operator.rs
server/src/public/user_email_invite.html
server/static/output.css

- Also updated the dashboard user context to set the organization based on url query parameters.

bugfix: invitation email redirects to correct organization on dashboard

---

frontends/dashboard/src/hooks/usePublicPageSettings.tsx
frontends/dashboard/src/pages/dataset/HeroPatterns.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

cleanup: use white as default demo page background color

---

.github/workflows/push-frontends.yml
.github/workflows/push-server.yml

ci: enable arm builds for Trieve

---

frontends/dashboard/src/components/OrgUpdateAlert.tsx
frontends/dashboard/src/components/OrganizationUsageOverview.tsx
frontends/dashboard/src/pages/orgs/OrganizationHomepage.tsx
frontends/dashboard/src/utils/fetchOrgUsage.tsx

feature: show alert when approaching usage limit on dashboard

---

frontends/search/src/components/ResultsPage.tsx

fix: group result chunks undefined

---

clients/search-component/example/vite.config.ts
clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/PdfView/ChatPdfItem.tsx
clients/search-component/src/TrieveModal/PdfView/PdfViewer.tsx
clients/search-component/src/TrieveModal/Search/PdfItem.tsx
clients/search-component/src/TrieveModal/icons.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/types.ts
clients/search-component/tailwind.config.js
yarn.lock

feat: full page pdf viewing

---

.github/workflows/push-frontends.yml
.github/workflows/push-server.yml

ci: add -arm suffix to arm builds

---

server/src/bin/file-worker.rs
server/src/handlers/file_handler.rs

bugfix: don't process file if create chunks is off

---

server/src/data/models.rs
server/src/operators/message_operator.rs
server/src/operators/search_operator.rs

feature: add prompt to image search

---

frontends/search/src/components/FilterModal.tsx

bugfix: ensure that tracking ids are filtering correctly

---

.github/workflows/push-server.yml

ci: add back sha for server CI action

---

frontends/search/src/components/ResultsPage.tsx

Reverts devflowinc/trieve#3065

Revert "fix: group result chunks undefined"

---

frontends/dashboard/src/pages/dataset/HeroPatterns.tsx

bugfix: fix dropdowns not working

---

server/src/operators/message_operator.rs

bugfix: don't append images if the array is empty

---

server/src/bin/crawl-worker.rs

bugfix: don't append Default Title to product names

---

frontends/search/src/components/SearchForm.tsx

bugfix: ensure that autocomplete can't be selected w/ group search

---

frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

feat: add pdf to public page

---

server/src/bin/etl-worker.rs

bugfix: ensure that groups don't get removed when using batch etl

---

server/src/bin/crawl-worker.rs

New Env var: PROXY_URL in the format of `<protocol>://<user>:<password>@<host>:port`

feature: add ability to use proxy for shopify

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts

feat(component): fixed mobile view for ecommerce popup mode

---

server/Cargo.lock
server/Cargo.toml

cleanup: rm unused deps

---

server/Cargo.lock
server/Cargo.toml
server/src/handlers/chunk_handler.rs
server/src/operators/message_operator.rs

feature: update openai dive

---

clients/search-component/src/TrieveModal/Chat/AIInitalMessage.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/index.css

bugfix: fix component for shopify-stores

---

frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

- **feature: add tv- prefix to tailwind styles**
- **feature: add inline to `search-component/example`, fix chat with group spacings**
- **bugfix: fix search type typo**

bugfix: fix search type typo

---

clients/search-component/example/src/routes/ecommerce.tsx
clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/package.json
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/vanilla/index.tsx
server/src/public/page.html

feature: auto load stable css if on vanilla js, overriding previous 0.2 css

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/useFollowupQuestions.ts
clients/search-component/src/utils/hooks/useSuggestedQuestions.ts
clients/search-component/src/utils/trieve.ts
frontends/dashboard/src/hooks/usePublicPageSettings.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/handlers/message_handler.rs
server/src/public/page.html
server/src/public/product.html
server/static/output.css

cleanup: small demo fixes

---

clients/search-component/src/TrieveModal/index.css

- **bugfix: overlay not showing on search component**

bugfix: overlay not showing on search component for shopify

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Search/DocsItem.tsx
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/useFollowupQuestions.ts
clients/search-component/src/utils/hooks/useSuggestedQuestions.ts
clients/search-component/src/utils/trieve.ts

- **v0.3.20**
- **feature: make query selectors more specific in case 2 components exist on the same page.**

feature: make query selectors more specific.

---

clients/search-component/example/src/routes/ecommerce.tsx
clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/Carousel.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
server/src/operators/analytics_operator.rs

cleanup: make carousel flashing better, clear input faster

---

server/src/middleware/timeout_middleware.rs

feature: flag to disable timeout middleware

---

clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/chat-context.tsx

cleanup: inline dark mode + bugfix chat with group completions

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Chat/FollowupQueries.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/Search/DocsItem.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/useFollowupQuestions.ts
clients/search-component/src/utils/styles.ts
clients/search-component/tailwind.config.js
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
yarn.lock

feat: begin smooth component

---

clients/search-component/src/TrieveModal/index.tsx

bugfix: follow up inline questions have ratings below the fold

---

server/src/handlers/page_handler.rs

feature: update beta url to use the bunny CDN

---

server/src/handlers/page_handler.rs
server/src/public/page.html

bugfix: fix search_component_url path

---

clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx

- **feat: add group tracking ids to csv upload system**
- **bugfix: modal not expanding to full height + inner scroll was too vertically long**

bugfix: modal not expanding to full height

---

clients/search-component/src/TrieveModal/Search/UploadImage.tsx

styling: adjust inline icon for picture upload on search mode

---

clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/index.css

styling: consistent example questions

---

clients/search-component/package.json

for reference: https://www.npmjs.com/package/tailwind

fix: remove random package "tailwind" (not "tailwindcss")

---

clients/search-component/src/utils/hooks/chat-context.tsx

fix: pdf chat

---

server/src/handlers/file_handler.rs

- **feature: make fullscreen selector more specific, fix full screen on mobile**
- **feature: upload pdf files as Content-Type application/pdf**

feature: upload pdf as application/pdf

---

server/src/bin/ingestion-worker.rs
server/src/handlers/chunk_handler.rs
yarn.lock

feature: move openai to seperate queue

---

clients/search-component/src/TrieveModal/index.css
yarn.lock

sanding: make max-width be 100% on inline mode

---

clients/search-component/package.json
yarn.lock

fix: pdf performance

---

clients/search-component/package.json
server/src/operators/file_operator.rs
server/src/operators/group_operator.rs

bugfix: delete group before deleting the file on DELETE /api/file, release search-component v0.4.0

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/index.css

feature: remove inline disclaimer, remove "Recommended Questions" text

---

helm/templates/server-deployment.yaml
server/Dockerfile.server

feature: update subtrace to b204

---

.github/workflows/push-server.yml
server/subtrace.yml

feature: add subtrace config, remove arm builds for ingest worker

---

clients/ts-sdk/src/__tests__/constants.ts
clients/ts-sdk/src/functions/file/index.ts

bugfix: include query params w/ queries

---

clients/search-component/package.json
clients/search-component/src/utils/hooks/useFollowupQuestions.ts
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/handlers/group_handler.rs

feature: get chunk_groups by tracking ids

---

.env.server
server/src/operators/search_operator.rs

feature: add a timeout to the highlight routes

---

clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/ts-sdk/package.json
clients/ts-sdk/src/functions/chunks/index.ts
clients/ts-sdk/src/functions/message/index.ts

- **v0.0.59**
- **bugfix: component streaming with newrelic fetch**

bugfix: component streaming with newrelic fetch

---

clients/search-component/README.md
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx

feature: hideOpenButton param

---

clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/FloatingSearchInput.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/Search/UploadAudio.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts
clients/search-component/src/utils/types.ts
clients/ts-sdk/openapi.json
clients/ts-sdk/src/fetch-client.ts
clients/ts-sdk/src/functions/chunks/index.ts
clients/ts-sdk/src/functions/groups/index.ts
clients/ts-sdk/src/functions/message/index.ts
clients/ts-sdk/src/types.gen.ts
frontends/search/src/components/Contexts/DatasetAndUserContext.tsx
frontends/search/src/components/ResultsPage.tsx
frontends/search/src/components/SearchForm.tsx
frontends/search/src/hooks/useSearch.ts
server/src/data/models.rs
server/src/handlers/chunk_handler.rs
server/src/handlers/group_handler.rs
server/src/handlers/message_handler.rs
server/src/operators/message_operator.rs
server/src/operators/search_operator.rs
server/src/public/page.html

https://github.com/user-attachments/assets/7b190cbc-825e-4d50-8d80-9e31caed9fa7
https://github.com/user-attachments/assets/27d9f8b4-e192-41ad-ab2e-3d6503f116eb

feature: audio input

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/ModeSwitch.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/Search/UploadAudio.tsx
clients/search-component/src/TrieveModal/Search/UploadImage.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
server/src/handlers/page_handler.rs
server/src/public/page.html
server/src/public/tabs.html
yarn.lock

Fixes overflow bugs and adds a shadow to indicate when there is more chat content to read.

styling: fix overflow bugs and add shadow

---

clients/search-component/src/TrieveModal/ModeSwitch.tsx
clients/search-component/src/TrieveModal/Search/UploadAudio.tsx
clients/search-component/src/TrieveModal/Search/UploadImage.tsx
clients/search-component/src/TrieveModal/index.css

- **bugfix: dark mode toggle in search-component**
- **bugfix: dark mode toggle in search-component**

bugfix: search component dark mode

---

clients/search-component/package.json
clients/search-component/prettier-config.mjs
yarn.lock

cleanup: add consistent prettier to search component

---

server/src/operators/search_operator.rs

bugfix: fix unwrap error if query is audio or image

---

clients/search-component/src/utils/hooks/chat-context.tsx

feat: buffer partial markdown links in search component chat

---

server/src/handlers/chunk_handler.rs
server/src/handlers/group_handler.rs
server/src/operators/message_operator.rs

bugfix: remove newlines from headers

---

server/src/operators/message_operator.rs

feature: use multiquery w/ images for llm

---

clients/search-component/README.md
server/src/operators/message_operator.rs
server/src/operators/parse_operator.rs

I used structured outputs and it actually seemed to make the model dumber, so I just appended a strict system prompt.
https://github.com/user-attachments/assets/24f762c3-ecf4-4d2c-be54-80bf5c4c58bf

feature: only return docs the llm used

---

clients/search-component/src/TrieveModal/index.css
server/src/operators/message_operator.rs

bugfixes: fix unwrap error on /api/message, patch spacing of inline component

---

clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/utils/hooks/modal-context.tsx

feat(component): add chatPlaceholder Modalprop

---

clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx

feat(component): add chatFilters property

---

clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/estimation.ts
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/useFollowupQuestions.ts
clients/search-component/src/utils/hooks/useSuggestedQuestions.ts
clients/search-component/src/utils/trieve.ts
frontends/dashboard/src/utils/createCodeSnippets.tsx
server/src/data/models.rs
server/src/handlers/message_handler.rs
server/src/operators/message_operator.rs

- **cleanup: fully remove suggestions + fix height on relead suggest button**
- **feature: add highlghts to ecommerce carousel**
-

feat: various chat component improvements

---

server/src/operators/chunk_operator.rs

bugfix: don't delelte chunk_group_bookmarks, and allow it to cascade delete to prevent timeouts

---

clients/search-component/src/TrieveModal/AddToCartButton.tsx
clients/search-component/src/TrieveModal/Chat/Carousel.tsx
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/TrieveModal/icons.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/tailwind.config.js

feat: shopping cart controls

---

clients/search-component/src/TrieveModal/Search/UploadAudio.tsx

bugfix: stop mic stream after audio input

---

clients/search-component/src/TrieveModal/Search/UploadAudio.tsx

bugfix: fix safari mic support

---

clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/modal-context.tsx

bugfix: show docs in search mode

---

clients/search-component/src/TrieveModal/Search/UploadAudio.tsx

feat: easier to press mic touchscreen button

---

server/src/handlers/chunk_handler.rs

bugfix: replaced openai_ingestion with premium ingestion

---

clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid

feat: more shopify variables

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/PlansTable.tsx
frontends/shared/types.ts
server/migrations/2025-01-29-050446_add-visibility-to-plans/down.sql
server/migrations/2025-01-29-050446_add-visibility-to-plans/up.sql
server/src/data/models.rs
server/src/data/schema.rs
server/src/operators/stripe_operator.rs

feature: add support for invisible stripe plans. (any new plans are automatically invisible)

---

frontends/dashboard/src/components/OrganizationUsageOverview.tsx

feature: add dataset count on billing tab

---

clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid

fix: syntax error on global component

---

server/src/bin/csv-jsonl-worker.rs
server/src/bin/file-worker.rs
server/src/bin/video-worker.rs
server/src/handlers/chunk_handler.rs

feature: specify priority for chunks

---

clients/trieve-shopify-extension/extensions/global-search/assets/cart-manager.js
clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid

feat: shopify add to cart

---

clients/search-component/README.md
clients/search-component/example/src/routes/ecommerce.tsx
clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Search/DocsItem.tsx
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/public/search-component-code.html

feature: make highlighted text in product and doc cards configurable 

---

clients/trieve-shopify-extension/package.json
clients/trieve-shopify-extension/vite.config.ts

fix: shopify vite setup

---

server/migrations/2025-01-31-195242_fix-datasets-deadlock/down.sql
server/migrations/2025-01-31-195242_fix-datasets-deadlock/up.sql

bugfix: combine update_dataset_usage trigger with organization_usage trigger for counting chunk_metadata

---

clients/search-component/src/utils/hooks/chat-context.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/chat/src/components/Layouts/MainLayout.tsx
server/src/data/models.rs
server/src/handlers/message_handler.rs
server/src/operators/message_operator.rs

feature: make returning only docs used in llm completions optional

---

server/migrations/2025-01-31-230518_dont-error-trigger-on-no-updates/down.sql
server/migrations/2025-01-31-230518_dont-error-trigger-on-no-updates/up.sql

bugfix: handle potential null in update chunk count trigger

---

clients/search-component/src/TrieveModal/Chat/Carousel.tsx
clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Search/DocsItem.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/Search/UploadAudio.tsx
clients/search-component/src/TrieveModal/icons.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/modal-context.tsx
server/src/public/product.html
server/static/output.css

enhancement: microphone input improvement 

---

clients/trieve-shopify-extension/app/routes/app._index.tsx

feat: add skeleton for shopify dataset list

---

frontends/dashboard/src/hooks/useDatasetPages.ts

fix: stream dashboard datasets instead of waiting

---

clients/trieve-shopify-extension/.gitignore
clients/trieve-shopify-extension/app/routes/_index/route.tsx
clients/trieve-shopify-extension/app/routes/_index/styles.module.css
clients/trieve-shopify-extension/package-lock.json
clients/trieve-shopify-extension/shopify.app.toml

cleanup: polish org selector page

---

clients/search-component/package.json

release(component): bump component to v0.4.9

---

server/Cargo.lock
server/Cargo.toml
server/src/bin/etl-worker.rs
server/src/bin/ingestion-worker.rs
server/src/handlers/chunk_handler.rs
server/src/handlers/etl_handler.rs
server/src/lib.rs
server/src/operators/crawl_operator.rs

feature: use broccoli fairness queue for ingestion

---

.github/workflows/ts-sdk-gh-pages.yml
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/CreateNewOrgModal.tsx
frontends/dashboard/src/pages/orgs/OrgSettings.tsx
server/migrations/2025-02-02-171310_add-org-partner-settings/down.sql
server/migrations/2025-02-02-171310_add-org-partner-settings/up.sql
server/src/data/models.rs
server/src/data/schema.rs
server/src/handlers/organization_handler.rs
server/src/handlers/page_handler.rs
server/src/lib.rs
server/src/operators/organization_operator.rs
server/src/operators/user_operator.rs
server/src/public/navbar.html
server/src/public/page.html

- **wip: with bugs**
- **wip: with bugs**

feature: add partner settings

---

clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/ImagePreview.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx

fix: image search/chat issues

---

server/Cargo.lock
server/Cargo.toml
server/src/bin/crawl-worker.rs
server/src/bin/csv-jsonl-worker.rs
server/src/bin/etl-worker.rs
server/src/bin/file-worker.rs
server/src/bin/ingestion-worker.rs
server/src/bin/update-worker.rs
server/src/bin/video-worker.rs
server/src/handlers/chunk_handler.rs
server/src/handlers/file_handler.rs
server/src/handlers/webhook_handler.rs
server/src/lib.rs
server/src/operators/crawl_operator.rs
server/src/operators/file_operator.rs
server/src/operators/webhook_operator.rs

bugfix: ensure all workers use broccoli to push to ingestion

---

server/src/operators/search_operator.rs

id filters have worked differently than most standard `filters`
Previously Correct filter
```nu
let body = {
query: "hi"
filters: {
must: [
{
"ids": ["55e4c068-55b8-4150-b9d3-21d84ff9ac65"]
}
]
}
search_type: "hybrid"
}
httppost $"($url)/api/chunk/search" $body
```
Typical mistyping of this filter.
```nu
let body = {
query: "hi"
filters: {
must: [
{
"field": "ids",
"match_any": ["55e4c068-55b8-4150-b9d3-21d84ff9ac65"]
}
]
}
search_type: "hybrid"
}
httppost $"($url)/api/chunk/search" $body
```
The only limitation for `ids` and `tracking_ids` filters is that they do not work with the `must_not` filter clause.
This Pull request allows **both** methods of filtering to work.

feature: allow `tracking_ids` and `ids` to work as `field_conditions` as well as the usual `HasIdCondition`

---

clients/trieve-shopify-extension/app/components/MustLoginPage.tsx
clients/trieve-shopify-extension/shopify.app.toml

feature: slight Loginpage enhahcement

---

frontends/search/src/components/UploadFile.tsx
server/src/bin/file-worker.rs
server/src/handlers/file_handler.rs

feature: include `group_id` if split_avg is used

---

server/src/operators/message_operator.rs

bugfix: ensure that chunks only get added once to rag message

---

clients/search-component/src/TrieveModal/Chat/ChatMessage.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/index.css

styling: questions over input

---

frontends/dashboard/src/components/DatasetOverview.tsx

fix: dataset pagination

---

server/Cargo.lock
server/Cargo.toml

bugfix: bump broccoli to make publishes atomic

---

docker/collapse-query-script/collapse_queries.py
server/ch_migrations/1738829154_drop_query_vector_row/down.sql
server/ch_migrations/1738829154_drop_query_vector_row/up.sql
server/migrations/2025-02-06-000209_add_crawl_type_to_crawl/down.sql
server/migrations/2025-02-06-000209_add_crawl_type_to_crawl/up.sql
server/src/operators/clickhouse_operator.rs

cleanup: remove query vector from clickhouse

---

docker/collapse-query-script/collapse_queries.py
server/ch_migrations/1738829154_drop_query_vector_row/down.sql
server/ch_migrations/1738829154_drop_query_vector_row/up.sql
server/migrations/2025-02-06-000209_add_crawl_type_to_crawl/down.sql
server/migrations/2025-02-06-000209_add_crawl_type_to_crawl/up.sql
server/src/operators/clickhouse_operator.rs

Reverts devflowinc/trieve#3326

Revert "cleanup: remove query vector from clickhouse"

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/useChatHeight.ts

includes:
fix: waits for animation on reset

feat: chat size never shrinks unless reset

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/index.css
frontends/dashboard/src/components/CreateNewOrgModal.tsx
frontends/dashboard/src/components/NewDatasetModal.tsx

styling: stop scrollbar jiggle

---

docker/collapse-query-script/collapse_queries.py

cleanup: don't force CH to optimize after collapse runs

---

server/src/operators/search_operator.rs

chore: add extra context to hybrid spans

---

.github/workflows/push-server.yml
frontends/chat/src/components/ScoreChunk.tsx
frontends/dashboard/src/components/NavbarOrgWidget.tsx
frontends/search/src/components/ChunkMetadataDisplay.tsx
frontends/search/src/components/ResultsPage.tsx
frontends/search/src/components/ScoreChunk.tsx
server/src/data/models.rs
server/src/handlers/chunk_handler.rs

- **bugfix: chunk recommendations are coming back without image urls**
- **cleanup: remove video-worker CI action from push-server.yml**

bugfix: chunk recommendations are coming back without image urls"

---

server/src/operators/crawl_operator.rs

bugfix: fix crawl issue for dashboard

---

clients/search-component/src/TrieveModal/Chat/Carousel.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/FloatingSearchIcon.tsx
clients/search-component/src/TrieveModal/ModeSwitch.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
server/src/public/page.html

Current progress:
Was able to create a category sidebar view that can open and close. When closed, the floating search icon appears where it came from. 
This as of right now only has the view from the right.
Things left to close this out:

feature: category sidebar parameter

---

clients/search-component/src/TrieveModal/index.tsx

feature(component): add trieve-open-modal EventListener to pop open the Trieve window

---

server/src/handlers/crawl_handler.rs
server/src/lib.rs

bugfix: move crawl endpoints to their own tag

---

clients/search-component/src/utils/hooks/chat-context.tsx

feature: add all user messages to getToolCall request

---

clients/search-component/README.md

docs: update search-component readme

---

server/src/bin/file-worker.rs
server/src/operators/file_operator.rs
server/src/operators/parse_operator.rs

- **bugfix: email invites with trailing space + add logs to file worker**
- **wip: bugfix file upload**

bugfix: file upload too man splits

---

frontends/search/src/components/CreateNewDocChunkForm.tsx

feature: add chunk to group with group tracking id

---

.github/workflows/push-shopify-server.yml
clients/trieve-shopify-extension/.dockerignore
clients/trieve-shopify-extension/docker-compose.yml

ci: shopify build and push action

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ChatInput.tsx
clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Chat/InlineChatHeader.tsx
clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/TrieveModal/Chat/UserMessage.tsx
clients/search-component/src/TrieveModal/Footer.tsx
clients/search-component/src/TrieveModal/ModalContainer.tsx
clients/search-component/src/TrieveModal/ModeSwitch.tsx
clients/search-component/src/TrieveModal/OpenModalButton.tsx
clients/search-component/src/TrieveModal/Search/DocsItem.tsx
clients/search-component/src/TrieveModal/Search/GoToChatPrompt.tsx
clients/search-component/src/TrieveModal/Search/PdfItem.tsx
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/TrieveModal/Search/SearchInput.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/TrieveModal/Search/SuggestedQueries.tsx
clients/search-component/src/TrieveModal/Search/UploadAudio.tsx
clients/search-component/src/TrieveModal/Search/UploadImage.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/useSizing.ts
clients/search-component/tailwind.config.js

styling: fix chat scroll popdown

---

server/src/operators/group_operator.rs

Attempt to prevent this without changing the API interface.

feature: attempt to make get_groups_for_dataset faster

---

clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/TrieveModal/Chat/UserMessage.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/chat-context.tsx

There were some endemic issues with retries being too short for audio and image search + loading not happening immediately. This fixes those issues and adds back some styling which got lost in the original ducking fix PR which was merged before.

bugfix(component): start loading immediatley and fix issues with stopGenerating and retries for toolcall/function

---

clients/search-component/src/TrieveModal/AddToCartButton.tsx
clients/search-component/src/TrieveModal/index.tsx

Small fixes needed for Flaviar component to work with AddToCart buttons
- addToCart button fix
- close modal even listener

feature: fix add to cart button to correctly display quantity. add close-modal event listener

---

server/src/operators/group_operator.rs

This was actually a lot worse, reverted back to 2 queries, maintainting the order by id

Revert "feature: attempt to make get_groups_for_dataset faster"

---

frontends/search/src/components/Atoms/AfMessage.tsx
frontends/search/src/components/BookmarkPopover.tsx
frontends/search/src/components/ChunkMetadataDisplay.tsx
frontends/search/src/components/GroupPage.tsx
frontends/search/src/components/OrgGroupPageView.tsx
frontends/search/src/components/ResultsPage.tsx
frontends/search/src/components/ScoreChunk.tsx
frontends/search/src/components/SingleChunkPage.tsx

feature(search-playground): only make request for groups in top level. Only paginate up to 100 groups

---

server/src/bin/clone-qdrant.rs

feature: add batch size param to clone-qdrant

---

frontends/dashboard/src/components/TrieveMaintenanceAlert.tsx
frontends/dashboard/src/pages/orgs/OrganizationHomepage.tsx

feature: add maintenance banner

---

pdf2md/server/src/models.rs
pdf2md/server/src/operators/chunkr.rs

Chunkr API has been updated, these changes reflect the new API references found here: https://docs.chunkr.ai/api-references/task/create-task

cleanup: update chunkr api to new version

---

clients/search-component/example/src/routes/index.lazy.tsx
clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
frontends/dashboard/src/analytics/components/charts/QueryCounts.tsx
frontends/shared/types.ts
server/ch_migrations/1740267077_migrate_rag_queries_to_replacing_merge_tree/down.sql
server/ch_migrations/1740267077_migrate_rag_queries_to_replacing_merge_tree/up.sql
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/operators/analytics_operator.rs
server/src/operators/clickhouse_operator.rs

feature: batch upvotes and downvotes

---

frontends/chat/src/components/ScoreChunk.tsx

- **feature(server): add retries to dense and sparse query embeddings**
- **bugfix: Chat playground chunks display**

bugfix: chat playground chunks display

---

server/src/bin/backfill-qdrant-from-pg.rs

feat(backfill): add the ability to specify a single dataset to migrate users to different qdrant instances

---

clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/hooks/setClickTriggers.ts
clients/ts-sdk/openapi.json
clients/ts-sdk/src/functions/analytics/index.ts
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/operators/analytics_operator.rs
server/src/operators/clickhouse_operator.rs

feature: track component clicks and chats by component name

---

clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx

feature: set `concat_user_messages = true` and flags to hide and show price / chunk_html

---

clients/trieve-shopify-extension/extensions/global-search/blocks/similar_products.liquid

feat: only show the recommended products if sold out

---

clients/search-component/example/src/routes/recs.tsx
clients/search-component/src/recommendations/Recommendations.tsx
clients/search-component/src/recommendations/use-recommendations.ts
clients/trieve-shopify-extension/app/processors/getProducts.ts

feature: disable group search and specify a filter

---

clients/search-component/src/utils/hooks/chat-context.tsx

feature: make chat filters a should instead of a must

---

clients/search-component/src/utils/trieve.ts

sanding: make the chunks sent to the model for suggestions smaller

---

clients/search-component/src/TrieveModal/index.css
clients/ts-sdk/openapi.json
clients/ts-sdk/src/__tests__/constants.ts
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/analytics/components/FilterBar.tsx
frontends/dashboard/src/analytics/components/RAGFilterBar.tsx
frontends/dashboard/src/analytics/pages/tablePages/EventsTablePage.tsx
frontends/dashboard/src/analytics/pages/tablePages/RecommendationsTablePage.tsx
frontends/dashboard/src/analytics/pages/tablePages/SearchTable.tsx
frontends/dashboard/src/analytics/utils/titleCase.ts
frontends/shared/types.ts
frontends/shared/ui/RangePicker.tsx
frontends/shared/ui/SelectBox.tsx
frontends/shared/ui/index.ts
server/src/data/models.rs
server/src/lib.rs
server/src/operators/message_operator.rs

https://github.com/user-attachments/assets/c41dae5f-d188-4e0c-b7ae-1f00fa74a081

feature: add query rating filters

---

clients/trieve-shopify-extension/app/components/CrawlSettings.tsx
clients/trieve-shopify-extension/app/processors/getProducts.ts
clients/trieve-shopify-extension/app/routes/_index/route.tsx
clients/trieve-shopify-extension/app/routes/app._index.tsx
clients/trieve-shopify-extension/app/routes/app.dataset.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.products.create.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.products.delete.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.products.update.tsx
clients/trieve-shopify-extension/app/types.ts
clients/trieve-shopify-extension/prisma/migrations/20250222142732_add_shop_to_api_key_table/migration.sql
clients/trieve-shopify-extension/prisma/migrations/20250222155102_save_crawl_settings/migration.sql
clients/trieve-shopify-extension/prisma/migrations/20250222155836_add_unique_constraint_on_dataset_id_and_shop/migration.sql
clients/trieve-shopify-extension/prisma/migrations/20250222162445_add_unique_constraint_to_api_key/migration.sql
clients/trieve-shopify-extension/prisma/schema.prisma
clients/trieve-shopify-extension/shopify.app.toml

- first migrate db `npx prisma migrate dev`
- run shopify app `yarn dev`
- deploy app for webhooks `npx shopify app deploy`
- Go to shopify app page and it will auto create a new dataset 
- run a crawl to save the settings
- Go to product and create/update a product and you should see the webhooks being called and that reflected in the search index

feature: listen to shopify product webhooks

---

clients/search-component/src/utils/trieve.ts

feature(component): disable shopify mode for follow up questions

---

clients/trieve-shopify-extension/app/components/DatasetSettings.tsx
clients/trieve-shopify-extension/app/routes/_index/route.tsx
clients/trieve-shopify-extension/app/routes/app._index.tsx
clients/trieve-shopify-extension/shopify.app.toml
frontends/dashboard/src/components/dataset-settings/LLMSettings.tsx
server/src/operators/message_operator.rs

feature: make onboarding less errorprone

---

clients/trieve-shopify-extension/app/routes/app._index.tsx
clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/similar_products.liquid
clients/trieve-shopify-extension/shopify.app.densumes-search-extension.toml

feature: auto add dataset id and api key

---

clients/trieve-shopify-extension/.gitignore
clients/trieve-shopify-extension/app/routes/app._index.tsx
clients/trieve-shopify-extension/shopify.app.densumes-search-extension.toml

feature: add deeplink for global component

---

clients/trieve-shopify-extension/.gitignore
server/src/operators/video_operator.rs

bugfix: fix youtube crawls

---

helm/templates/backend-configmap.yaml
helm/templates/etl-worker-deployment.yaml
helm/test-production/clickhouse/clickhouse-installation.yaml
helm/test-production/qdrant-values.yaml
helm/values.aws.yaml
helm/values.az.yaml
helm/values.gcp.yaml
helm/values.yaml
terraform/azure/main.tf

ops: update helm values to latest

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/chat/src/components/Layouts/MainLayout.tsx
server/src/data/models.rs
server/src/handlers/message_handler.rs
server/src/operators/message_operator.rs

feat: add use quote negated terms, remove stop words, and typo options to message routes

---

frontends/dashboard/index.html

cleanup: remove mintlify widget

---

server/subtrace.yml

ops: modify subtrace auth credentials to keep

---

server/src/operators/clickhouse_operator.rs

feature: variable CH queue length

---

server/src/operators/message_operator.rs

Tested by updating dataset config with the following nu script.
```nu
let url = "http://localhost:8090/api/dataset"
let headers = {
TR-Dataset: "my-dataset"
TR-Organization: "88428aa6-05bf-4482-8729-c47f88a642c2"
Authorization: "admin"
}
let body = {
tracking_id: "my-dataset"
server_configuration: {
LLM_BASE_URL: "http://localhost:4000",
LLM_API_KEY: "sk-****************************"
LLM_DEFAULT_MODEL: "o3-mini-2025-01-31"
PRESENCE_PENALTY: 0
FREQUENCY_PENALTY: 0
}
}
http put --content-type application/json $url $body --headers $headers -e
```

bugfix: make ALL llm calls use dataset_config for `frequency_penalty` and `presence_penalty`

---

clients/trieve-fern-adapter/package.json
clients/trieve-fern-adapter/src/index.ts
clients/trieve-fern-adapter/yarn.lock

- wait for chunks to clear before beginning to insert
- add a higher fulltext boost to API routes since those chunks are overly short token-wise
- remove duplicate chunk_htmls to clean up SERPs

bugfix(fern-adapter): duplicates and missing items

---

.github/workflows/release-helm.yaml

ci: release helm chart ci action

---

clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
frontends/dashboard/src/hooks/usePublicPageSettings.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx

feat: properly remove chat highlights with prop

---

clients/search-component/src/TrieveModal/ModeSwitch.tsx
clients/search-component/src/utils/hooks/useChatHeight.ts

fix: chat height

---

clients/trieve-shopify-extension/shopify.app.stark-trieve-search-extension.toml
server/src/handlers/auth_handler.rs
server/src/operators/clickhouse_operator.rs
server/src/public/page.html

- **feature: make showResultHighlights = false also hide chunkHtml**
- **feature: make CLICKHOUSE_QUEUE_LENGTH be an optional ENV, add full error message for OIDC actions**
- **feature: update trieve-shopify-extension toml for stark**

feature: a few misc fixes

---

clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts

bugfix: ensure correct component name is being passed for the component

---

clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/TrieveModal/Search/DocsItem.tsx
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/trieve.ts

bugfix: don't use hooks in non-React functions

---

server/ch_migrations/1741708207_add_topic_id_to_rag_queries/down.sql
server/ch_migrations/1741708207_add_topic_id_to_rag_queries/up.sql

bugfix: add back RAG CH migration that was removed

---

clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx

- **bugfix: allow users to delete crawls**
- **bugfix: checkout not triggering after add to cart**

bugfix: checkout analytics event not firing after item being added to cart replaces elem

---

clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts
clients/trieve-shopify-extension/app/auth.ts
clients/trieve-shopify-extension/app/components/analytics/AnalyticsChart.tsx
clients/trieve-shopify-extension/app/components/analytics/component/TotalUniqueVisitors.tsx
clients/trieve-shopify-extension/app/context/trieveContext.tsx
clients/trieve-shopify-extension/app/processors/getProducts.ts
clients/trieve-shopify-extension/app/queries/analytics/component.ts
clients/trieve-shopify-extension/app/routes/_index/route.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.component.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.tsx
clients/trieve-shopify-extension/app/routes/app.plans.tsx
clients/trieve-shopify-extension/app/routes/app.setup.tsx
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/functions/analytics/index.ts
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: get unique users of component

---

clients/trieve-shopify-extension/app/auth.ts
clients/trieve-shopify-extension/app/context/trieveContext.tsx
clients/trieve-shopify-extension/app/env.ts
clients/trieve-shopify-extension/app/processors/getProducts.ts
clients/trieve-shopify-extension/app/root.tsx
clients/trieve-shopify-extension/app/routes/_index/route.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.tsx
clients/trieve-shopify-extension/app/routes/app.plans.tsx
clients/trieve-shopify-extension/app/routes/app.setup.tsx

feat: use window for env variables

---

clients/trieve-shopify-extension/app/env.ts

fix: remove trailing slash for env file

---

clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts
clients/trieve-shopify-extension/app/components/analytics/AnalyticsChart.tsx
clients/trieve-shopify-extension/app/components/analytics/GraphComponent.tsx
clients/trieve-shopify-extension/app/components/analytics/TableComponent.tsx
clients/trieve-shopify-extension/app/components/analytics/component/TopPages.tsx
clients/trieve-shopify-extension/app/components/analytics/component/TotalUniqueVisitors.tsx
clients/trieve-shopify-extension/app/components/analytics/search/HeadQueriesTable.tsx
clients/trieve-shopify-extension/app/components/analytics/search/NoResultQueriesTable.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchUsageChart.tsx
clients/trieve-shopify-extension/app/queries/analytics/component.ts
clients/trieve-shopify-extension/app/queries/analytics/search.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.component.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.search.tsx
clients/trieve-shopify-extension/app/routes/app.setup.tsx
clients/trieve-shopify-extension/package.json
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/ch_migrations/1741813247_add_location_to_event/down.sql
server/ch_migrations/1741813247_add_location_to_event/up.sql
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: table for top pages, feature: added generic table and graph components for unified style system

---

clients/trieve-shopify-extension/app/auth.ts
clients/trieve-shopify-extension/app/context/trieveContext.tsx
clients/trieve-shopify-extension/app/context/useEnvs.tsx
clients/trieve-shopify-extension/app/env.server.ts
clients/trieve-shopify-extension/app/env.ts
clients/trieve-shopify-extension/app/processors/getProducts.ts
clients/trieve-shopify-extension/app/root.tsx
clients/trieve-shopify-extension/app/routes/_index/route.tsx
clients/trieve-shopify-extension/app/routes/app.plans.tsx
clients/trieve-shopify-extension/app/routes/app.setup.tsx

feat: fix envs

---

clients/trieve-shopify-extension/app/components/analytics/component/TopComponents.tsx
clients/trieve-shopify-extension/app/queries/analytics/component.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.component.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: add top components card

---

clients/trieve-shopify-extension/app/components/analytics/ComponentNameSelect.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchFilterBar.tsx
clients/trieve-shopify-extension/app/queries/analytics/component.ts
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feat: add component names to analytics filter bar

---

clients/trieve-shopify-extension/app/components/analytics/AnalyticsChart.tsx
clients/trieve-shopify-extension/app/components/analytics/GraphComponent.tsx
clients/trieve-shopify-extension/app/components/analytics/chat/TopicsGraph.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchFilterBar.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchUsageChart.tsx
clients/trieve-shopify-extension/app/queries/analytics/chat.ts
clients/trieve-shopify-extension/app/queries/analytics/formatting.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.chat.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.tsx
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/operators/analytics_operator.rs

feature: add topics usage chart

---

clients/trieve-shopify-extension/app/components/analytics/recommendations/RecommendationsUsageChart.tsx
clients/trieve-shopify-extension/app/queries/analytics/recommendation.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.recommendations.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: add recs over time

---

clients/trieve-shopify-extension/app/components/analytics/recommendations/RecommendationsPerUser.tsx
clients/trieve-shopify-extension/app/queries/analytics/recommendation.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.recommendations.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: add recs per user

---

server/Dockerfile.server

ops: bump subtrace to b270

---

clients/trieve-shopify-extension/app/components/analytics/search/SearchCTR.tsx

cleanup: fix minor linting issues

---

clients/trieve-shopify-extension/app/components/analytics/AdvancedTableComponent.tsx
clients/trieve-shopify-extension/app/components/analytics/recommendations/AllRecommendationsTable.tsx
clients/trieve-shopify-extension/app/queries/analytics/recommendation.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.recommendations.tsx
clients/trieve-shopify-extension/package.json
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: recommendation analytics table

---

clients/trieve-shopify-extension/app/components/analytics/AnalyticsChart.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchConversionRate.tsx
clients/trieve-shopify-extension/app/queries/analytics/search.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.search.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs
yarn.lock

feat(shopify): conversion rate from search

---

clients/trieve-shopify-extension/app/components/analytics/DateRangePicker.tsx

styling: make date range selector match component name

---

clients/search-component/src/TrieveModal/Chat/ChatMode.tsx

cleanup: remove console log spam for chat search component

---

.dockerignore
clients/search-component/package.json
clients/ts-sdk/package.json
clients/ts-sdk/src/functions/message/message.test.ts
frontends/chat/Dockerfile
frontends/chat/src/components/Atoms/AfMessage.tsx
frontends/chat/src/components/Atoms/MessageVoting.tsx
frontends/dashboard/Dockerfile
frontends/search/.dockerignore
frontends/search/Dockerfile
frontends/search/package.json
package.json
server/src/operators/message_operator.rs
yarn.lock

- **bugfix(ts-sdk): move to legacy/fetch client**
- **bugfix(chat): build with makePersisted primitive**

bugfix: chat build with makePersisted

---

clients/trieve-shopify-extension/app/components/analytics/GraphComponent.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchesPerUser.tsx
clients/trieve-shopify-extension/app/queries/analytics/search.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.search.tsx
clients/trieve-shopify-extension/app/utils/formatting.ts
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: add searches per user

---

clients/trieve-shopify-extension/app/components/analytics/chat/ChatAverageRating.tsx
clients/trieve-shopify-extension/app/queries/analytics/chat.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.chat.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.recommendations.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.search.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: add average chat rating

---

clients/trieve-shopify-extension/app/components/analytics/search/SearchAverageRating.tsx
clients/trieve-shopify-extension/app/queries/analytics/search.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.search.tsx
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs
yarn.lock

feature: add average search rating graph

---

clients/trieve-shopify-extension/app/components/analytics/chat/ChatConversionRate.tsx
clients/trieve-shopify-extension/app/components/analytics/recommendations/RecommendationConversionRate.tsx
clients/trieve-shopify-extension/app/queries/analytics/chat.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.chat.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.recommendations.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: add chat converstion rate graph

---

clients/search-component/example/src/routeTree.gen.ts
clients/search-component/example/yarn.lock
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/trieve-shopify-extension/app/components/analytics/AnalyticsChart.tsx
clients/trieve-shopify-extension/app/components/analytics/GraphComponent.tsx
clients/trieve-shopify-extension/app/components/analytics/component/AverageInteractionTime.tsx
clients/trieve-shopify-extension/app/queries/analytics/component.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.component.tsx
clients/trieve-shopify-extension/app/utils/formatting.ts
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: add avg interaction time

---

clients/trieve-shopify-extension/app/dehydrate.ts
clients/trieve-shopify-extension/app/loaders/clientLoader.ts
clients/trieve-shopify-extension/app/loaders/index.ts
clients/trieve-shopify-extension/app/loaders/serverLoader.ts
clients/trieve-shopify-extension/app/processors/getProducts.ts
clients/trieve-shopify-extension/app/queries/onboarding.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.test.tsx
clients/trieve-shopify-extension/app/routes/app.setup.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.products.create.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.products.delete.tsx
clients/trieve-shopify-extension/app/utils/onboarding.ts
clients/trieve-shopify-extension/shopify.app.toml

feat: shopify onboarding

---

clients/trieve-shopify-extension/app/routes/webhooks.app.products.delete.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.products.update.tsx

fix: webhook params

---

.github/workflows/push-shopify-server.yml
clients/trieve-shopify-extension/.dockerignore
clients/trieve-shopify-extension/.gitignore
clients/trieve-shopify-extension/Dockerfile
clients/trieve-shopify-extension/docker-compose.yml
clients/trieve-shopify-extension/package.json
clients/trieve-shopify-extension/vite.config.ts
clients/trieve-shopify-extension/yarn.lock

ci(shopify): fix broken vite config for build

---

clients/trieve-shopify-extension/app/processors/getProducts.ts

Feature: fix webhook crashing

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/OnboardingSteps.tsx
frontends/dashboard/src/components/OrganizationUsageOverview.tsx
frontends/dashboard/src/utils/fetchOrgUsage.tsx
server/src/handlers/organization_handler.rs
server/src/operators/organization_operator.rs

hotfix: swap back to v1 organization usage for the Billing tab

---

clients/trieve-shopify-extension/app/components/analytics/AnalyticsChart.tsx
clients/trieve-shopify-extension/app/components/analytics/GraphComponent.tsx
clients/trieve-shopify-extension/app/components/analytics/chat/ChatRevenue.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchAverageRating.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchCTR.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchConversionRate.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchRevenue.tsx
clients/trieve-shopify-extension/app/queries/analytics/chat.ts
clients/trieve-shopify-extension/app/queries/analytics/search.ts
clients/trieve-shopify-extension/package.json
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: add search and chat revenue graphs

---

clients/trieve-shopify-extension/app/components/analytics/chat/ChatRevenue.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchRevenue.tsx

bugfix: fix the chat and search revenue graphs

---

README.md
server/src/operators/model_operator.rs

1. Normalized AIMon reranker scores to be in the range [0,1]
2. Updated the README.md
This PR is related to [Issue #3441](https://github.com/devflowinc/trieve/issues/3441).

Normalized AIMon reranker scores to be in the range [0,1]

---

clients/trieve-shopify-extension/package.json

ci: set trieve-ts-sdk to "*" to fix broken shopify builds

---

server/src/operators/model_operator.rs

One of our `ureq` requests in the reranker was not using the `AgentBuilder`.
This refactors some of the logic so that it hopefully won't happen any more for future requests.
```rs
ureq::AgentBuilder::new()
.tls_connector(Arc::new(native_tls::TlsConnector::new().map_err(|_| {
ServiceError::InternalServerError("Failed to acquire tls connection".to_string())
})?))
```

bugfix: add ureq tls agent to all reranker ureq requests

---

clients/trieve-shopify-extension/app/processors/getProducts.ts

feature(shopify-app): add product status to shopify-component scraper.

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/index.tsx
clients/trieve-shopify-extension/app/components/analytics/EventPathSelector.tsx
clients/trieve-shopify-extension/app/components/analytics/chat/ChatRevenue.tsx
clients/trieve-shopify-extension/app/queries/analytics/chat.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.chat.tsx
clients/trieve-shopify-extension/app/utils/formatting.ts
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/operators/analytics_operator.rs
yarn.lock

feature: add direct and indirect chat revenue charts

---

server/src/operators/analytics_operator.rs

bugfix: fix the filter for chat revenue

---

clients/trieve-shopify-extension/app/components/analytics/chat/ChatRevenue.tsx
server/src/data/models.rs
server/src/operators/analytics_operator.rs

feature: make revenue summed and not average

---

clients/trieve-shopify-extension/app/components/analytics/DateRangePicker.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.chat.tsx
server/src/operators/analytics_operator.rs

cleanup: chart nits

---

README.md
frontends/shared/types.ts
server/src/operators/model_operator.rs

Modified the AIMon reranking API endpoint, the payload (AIMonRequestBody) and response body (AIMonResponseBody).

refactor: restructured the AIMon reranker

---

clients/trieve-shopify-extension/app/components/analytics/chat/ChatAverageRating.tsx
clients/trieve-shopify-extension/app/components/analytics/chat/ChatRevenue.tsx
clients/trieve-shopify-extension/app/components/analytics/chat/PopularChatsTable.tsx
clients/trieve-shopify-extension/app/components/analytics/chat/TopicCTRRate.tsx
clients/trieve-shopify-extension/app/queries/analytics/chat.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.chat.tsx
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feature: added popular chats

---

clients/search-component/package.json
clients/search-component/scripts/build.js
clients/ts-sdk/package.json

bugfix: remove __dirname from trieve-search-component dist/

---

clients/trieve-shopify-extension/app/utils/formatting.ts

cleanup: make conversation -> chat

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/operators/analytics_operator.rs

bugfix: fix chat revenue filtering

---

clients/trieve-shopify-extension/app/components/analytics/AdvancedTableComponent.tsx

bugfix(shopify): fix text wrapping on Chat Sessions view

---

clients/trieve-shopify-extension/app/components/analytics/FilterBar.tsx
clients/trieve-shopify-extension/app/components/analytics/component/TopComponents.tsx
clients/trieve-shopify-extension/app/queries/analytics/component.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.component.tsx

refactor: move components table above separate from per-component analytics

---

server/Dockerfile.server

ci(server): speed up "No ocr" server image docker builds

---

clients/trieve-shopify-extension/app/components/onboarding/AddComponentOnboarding.tsx
clients/trieve-shopify-extension/app/components/onboarding/DoChatOnboarding.tsx
clients/trieve-shopify-extension/app/components/onboarding/Onboarding.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard._index.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.search.tsx
clients/trieve-shopify-extension/app/utils/onboarding.tsx
clients/trieve-shopify-extension/app/utils/useShopName.tsx

feat: more onboarding steps

---

clients/trieve-shopify-extension/app/components/analytics/EventPathSelector.tsx
clients/trieve-shopify-extension/app/components/analytics/chat/ChatUserJourneyFunnel.tsx
clients/trieve-shopify-extension/app/components/analytics/recommendations/RecommendationUserJourneyFunnel.tsx
clients/trieve-shopify-extension/app/components/analytics/search/SearchUserJourneyFunnel.tsx

feat: add back funnel select

---

clients/search-component/src/utils/hooks/chat-context.tsx

bugfix(component): modify tool function prompt to be "slightly like" a product name instead. Yielded better results

---

clients/trieve-shopify-extension/app/components/analytics/component/TopComponents.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.component.tsx
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/operators/analytics_operator.rs
yarn.lock

- **v0.0.71**
- **feature(shopify): add add to carts and checkout stats to components table**

feature(shopify): add add to carts and checkouts to components table

---

clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/trieve.ts

feature: attribution data in add-to-cart and checkouts

---

clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
yarn.lock

feature: use shopify cart.js to get cart data

---

clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/utils/trieve.ts
clients/trieve-shopify-extension/app/components/chat/MessageEventTimeline.tsx
clients/trieve-shopify-extension/app/loaders/clientLoader.ts
clients/trieve-shopify-extension/app/loaders/index.ts
clients/trieve-shopify-extension/app/loaders/serverLoader.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.chatview.$topic.tsx
clients/trieve-shopify-extension/app/utils/formatting.ts
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/lib.rs
server/src/operators/analytics_operator.rs

feat: shopify single chat events timeline

---

frontends/dashboard/src/utils/fetchOrgUsage.tsx

feature: move frontend to v2 usage

---

frontends/dashboard/src/components/OrganizationUsageOverview.tsx

bugfix: make file storage be formatted properly

---

frontends/dashboard/src/components/OrganizationUsageOverview.tsx
server/migrations/2025-03-31-190548_file_storage_to_mb/down.sql
server/migrations/2025-03-31-190548_file_storage_to_mb/up.sql
server/src/data/models.rs
server/src/data/schema.rs
server/src/handlers/file_handler.rs
server/src/operators/organization_operator.rs

feature: migrate file_storage from bytes to mb

---

frontends/dashboard/src/components/PlansTable.tsx
frontends/dashboard/src/components/UsagePlansTable.tsx
server/src/data/models.rs
server/src/handlers/stripe_handler.rs
server/src/operators/stripe_operator.rs

bugfix: Shopify resubscribe and cancel UI + backend fixes

---

clients/trieve-shopify-extension/app/components/DatasetSettings.tsx
clients/trieve-shopify-extension/app/loaders/serverLoader.ts
clients/trieve-shopify-extension/app/processors/getProducts.ts
clients/trieve-shopify-extension/app/routes/_index/route.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/trieve-shopify-extension/app/routes/app.setup.tsx
clients/trieve-shopify-extension/vite.config.ts
server/src/data/models.rs

bugfix: make jina default embedding model, feature: auto log in if only 1 org

---

server/src/operators/message_operator.rs

feature: include num_value in the context window for rag

---

server/migrations/2025-03-31-190548_file_storage_to_mb/up.sql
server/src/data/models.rs
server/src/data/schema.rs
server/src/handlers/stripe_handler.rs
server/src/lib.rs
server/src/operators/stripe_operator.rs

feat(server): add price estimation route

---

server/src/operators/search_operator.rs

feat(server): include qdrant timing header into hybrid search

---

server/src/data/models.rs
server/src/handlers/stripe_handler.rs
server/src/lib.rs
server/src/operators/stripe_operator.rs

feature: make price estimation pull from stripe data

---

server/src/operators/stripe_operator.rs

fix: convert money to proper decimal places for get_bill_from_range

---

clients/trieve-shopify-extension/app/components/onboarding/Onboarding.tsx
clients/trieve-shopify-extension/app/queries/onboarding.ts
clients/trieve-shopify-extension/app/utils/onboarding.tsx

feat: collapse all onboarding steps, one open at a time

---

frontends/dashboard/src/utils/formatNumbers.ts
server/src/operators/chunk_operator.rs
server/src/operators/organization_operator.rs

bugfix: adjust event counts to the sum of rag and search events

---

clients/trieve-shopify-extension/app/components/onboarding/WelcomeOnboarding.tsx
clients/trieve-shopify-extension/app/processors/getProducts.ts
clients/trieve-shopify-extension/app/queries/onboarding.ts
clients/trieve-shopify-extension/app/routes/app.setup.tsx

fix: more consistent product onboard ingest

---

clients/trieve-shopify-extension/app/components/onboarding/AddComponentOnboarding.tsx
clients/trieve-shopify-extension/app/components/onboarding/DoChatOnboarding.tsx
clients/trieve-shopify-extension/app/components/onboarding/Onboarding.tsx
clients/trieve-shopify-extension/app/components/onboarding/ThemeSelect.tsx
clients/trieve-shopify-extension/app/components/onboarding/WelcomeOnboarding.tsx
clients/trieve-shopify-extension/app/queries/analytics/chat.ts

fix: onboarding small issues

---

frontends/dashboard/src/utils/formatNumbers.ts

fix(dashboard): make MB conversion acurate

---

clients/search-component/src/TrieveModal/Chat/FollowupQueries.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx

bugfix: send analytics event after the message has been sent

---

server/src/operators/stripe_operator.rs

feat(cloud): allow promo codes for shopify

---

frontends/dashboard/src/utils/formatNumbers.ts
server/src/operators/stripe_operator.rs

feature: prevent extra creations of reqwest::Client

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/PlansTable.tsx
server/migrations/2025-04-04-005913_add-platform-fee/down.sql
server/migrations/2025-04-04-005913_add-platform-fee/up.sql
server/src/data/models.rs
server/src/data/schema.rs
server/src/operators/stripe_operator.rs

feature: add base platform charge

---

server/src/handlers/stripe_handler.rs
server/src/operators/stripe_operator.rs

bugfix(estimate route): don't down cast to i64.

---

clients/trieve-shopify-extension/shopify.app.flaviar-trieve-chat-extension.toml
clients/trieve-shopify-extension/shopify.app.stark-trieve-search-extension.toml
frontends/search/src/components/GroupPage.tsx
frontends/search/src/components/OrgGroupPageView.tsx
frontends/search/src/components/ResultsPage.tsx
frontends/search/src/components/SingleChunkPage.tsx
frontends/search/src/utils/apiTypes.ts

enhancement(search-playground): make group search page faster using the cursor based method

---

frontends/dashboard/src/components/OrganizationUsageOverview.tsx
frontends/dashboard/src/components/PricingTable.tsx
server/src/handlers/stripe_handler.rs
server/src/operators/stripe_operator.rs

fix(estimate route): subtraction underflow fix

---

clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid

feat(trieve-shopify-extension): add default search mode and default search filters for global and inline component

---

clients/search-component/src/TrieveModal/Chat/ChatMode.tsx
clients/search-component/src/TrieveModal/Chat/FollowupQueries.tsx
clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/TrieveModal/Search/UploadImage.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx

feature(search-component): add highlted item when in previewTopicId mode

---

clients/search-component/package.json
clients/trieve-shopify-extension/package.json
clients/trieve-shopify-extension/yarn.lock

feature: shopify bump search-component version to 0.4.54

---

server/src/bin/reindex-worker.rs

- **feature: modify reindex-worker to brpoplpush**
- **feature: update reindex worker to make a copy of all data for easier retries**

feature: reindex worker copy data to diff redis

---

pdf2md/server/static/output.css

fix: add output.css

---

clients/trieve-shopify-extension/app/components/PlanView.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard._index.tsx
clients/trieve-shopify-extension/package.json
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
server/migrations/2025-04-10-191301_rename-component-loads-to-messages-per-month/down.sql
server/migrations/2025-04-10-191301_rename-component-loads-to-messages-per-month/up.sql
server/src/data/models.rs
server/src/data/schema.rs

- **v0.0.84**
- **refactor(server+shopify) rename component_loads to messages_per_month in schema and related files**

refactor: shopify billing plans display

---

clients/trieve-shopify-extension/app/components/onboarding/AddComponentOnboarding.tsx
clients/trieve-shopify-extension/app/components/onboarding/DoChatOnboarding.tsx
clients/trieve-shopify-extension/app/components/onboarding/SetPromptsOnboarding.tsx
clients/trieve-shopify-extension/app/components/onboarding/WelcomeOnboarding.tsx
clients/trieve-shopify-extension/app/context/trieveContext.tsx
clients/trieve-shopify-extension/app/queries/analytics/chat.ts
clients/trieve-shopify-extension/app/queries/usage.ts
clients/trieve-shopify-extension/app/routes/app._dashboard._index.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.tsx
clients/trieve-shopify-extension/app/routes/app.setup.tsx
clients/trieve-shopify-extension/app/utils/onboarding.tsx
clients/trieve-shopify-extension/app/utils/suspense.tsx

feat(shopify): set prompt onboarding

---

clients/trieve-shopify-extension/app/components/PlanView.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard._index.tsx
clients/trieve-shopify-extension/app/routes/app.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.app_subscriptions.update.tsx
clients/trieve-shopify-extension/app/utils/onboarding.tsx
server/src/data/models.rs
server/src/handlers/payment_handler.rs

- **refactor(shopify): reorder chat links for improved navigation**
- **bugfix(shopify): only set shopify current_period_end on cancel**
- **feat(shopify): enhance PlanView with plan details display and improve onboarding flow**

bugfix(shopify): modify checkout sessions to have no expired ats + cleanup(shopify): improve onboarding flow and namings"

---

clients/trieve-shopify-extension/app/components/DatasetSettings.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid

feature: add settings item for setting the checkout selector

---

clients/trieve-shopify-extension/app/routes/_index/route.tsx

feat(shopify): add health check route

---

clients/trieve-shopify-extension/app/routes/webhooks.app.products.create.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.products.delete.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.products.update.tsx

bugfix: fix webhooks to get the correct apiKey

---

server/src/handlers/auth_handler.rs

feature: make subscription stripe_id be a unique random uuid for shopify free plans

---

clients/trieve-shopify-extension/app/components/onboarding/AddComponentOnboarding.tsx

bugfix: mark globalComplete based on the extension name instead of the domain name

---

clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/similar_products.liquid

feature: load css from component instead of as a link tag

---

clients/search-component/src/vanilla/index.tsx

bugfix: fix link for css styling

---

clients/search-component/src/vanilla/index.tsx
clients/trieve-shopify-extension/app/queries/analytics/chat.ts

bugfix: chat sessions not applying filter

---

clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid

bugfix: don't use group search in inline mode

---

clients/trieve-shopify-extension/app/components/ResetSettings.tsx
clients/trieve-shopify-extension/app/routes/_index/tailwind.css
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/trieve-shopify-extension/app/utils/productMetafields.ts

feat: delete app metafields in settings

---

clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/trieve-shopify-extension/app/components/onboarding/AddComponentOnboarding.tsx
clients/trieve-shopify-extension/extensions/trieve-checkout-web-pixel/README.md
clients/trieve-shopify-extension/extensions/trieve-checkout-web-pixel/package.json
clients/trieve-shopify-extension/extensions/trieve-checkout-web-pixel/shopify.extension.toml
clients/trieve-shopify-extension/extensions/trieve-checkout-web-pixel/src/index.ts
clients/trieve-shopify-extension/shopify.app.toml.dist

feature: use shopify app pixel to track add to carts and purchase automatically

---

clients/trieve-shopify-extension/app/components/DatasetSettings.tsx
clients/trieve-shopify-extension/app/components/ResetSettings.tsx

feature: make reset button only reset onboarding steps

---

frontends/search/src/components/BookmarkPopover.tsx
frontends/search/src/components/EditChunkPageForm.tsx
frontends/search/src/components/ResultsPage.tsx
server/src/bin/backfill-qdrant-from-pg.rs
server/src/bin/crawl-worker.rs
server/src/bin/csv-jsonl-worker.rs
server/src/bin/file-worker.rs
server/src/bin/ingestion-worker.rs
server/src/data/models.rs
server/src/handlers/chunk_handler.rs
server/src/operators/chunk_operator.rs

- feat: add fulltext_content field to ChunkReqPayload and related structures
- cleanup(search): add validation to prevent fetching bookmarks without chunk metadata and dataset

feat: add fulltext_content field to ChunkReqPayload and related structures

---

clients/trieve-shopify-extension/app/components/DatasetSettings.tsx
clients/trieve-shopify-extension/app/components/onboarding/AddComponentOnboarding.tsx
clients/trieve-shopify-extension/app/queries/webPixel.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.tsx

feature: add pixel on load and add button to manually add pixel in settings

---

clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid

bugfix: fix inline chat add back defaultAIquestions

---

clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts
clients/trieve-shopify-extension/extensions/trieve-checkout-web-pixel/src/index.ts

bugfix: try/catch all localstorage calls

---

clients/trieve-shopify-extension/README.md
clients/trieve-shopify-extension/app/auth.ts
clients/trieve-shopify-extension/app/components/JudgeMeSetup.tsx
clients/trieve-shopify-extension/app/routes/api.judgeme.info.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard._index.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/trieve-shopify-extension/app/routes/auth.judgeme.callback.tsx
clients/trieve-shopify-extension/app/routes/auth.judgeme.login.tsx
clients/trieve-shopify-extension/package.json
clients/trieve-shopify-extension/prisma/migrations/20250416234424_judgeme/migration.sql
clients/trieve-shopify-extension/prisma/schema.prisma
clients/trieve-shopify-extension/yarn.lock

feat: connect shopify app with judge.me

---

clients/trieve-shopify-extension/app/queries/webPixel.ts

bugfix: pixel install check

---

clients/trieve-shopify-extension/app/routes/webhooks.app.customer-data.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.redact-customer.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.redact-shop.tsx
clients/trieve-shopify-extension/shopify.app.toml.dist

feature: add compliance webhooks for redacting shop data

---

clients/trieve-shopify-extension/app/routes/webhooks.app.customer-data.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.redact-customer.tsx
clients/trieve-shopify-extension/app/routes/webhooks.app.redact-shop.tsx

feature: authenticate compliance webhooks

---

clients/trieve-shopify-extension/app/components/analytics/EventPathSelector.tsx
clients/trieve-shopify-extension/app/components/analytics/chat/ChatEventsFilter.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.chats.tsx
clients/trieve-shopify-extension/app/utils/formatting.ts
clients/trieve-shopify-extension/package.json
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/operators/analytics_operator.rs

feature: use checkout end events for purchase

---

clients/search-component/src/TrieveModal/FilterSidebarComponents.tsx
clients/search-component/src/TrieveModal/Search/SuggestedQueries.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/trieve.ts

- [feat: implement retry logic for operations and enhance error handling in suggested queries](https://github.com/devflowinc/trieve/pull/3792/commits/5e7e52ee22b5a82aac7fa3e334d253fe11db664e)

feat: implement retry logic for operations and enhance error handling in suggested queries

---

clients/trieve-shopify-extension/app/auth.ts

bugfix: use actual email during setup

---

clients/trieve-shopify-extension/.env.dist
clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid

feature: add custom_css block in theme editor for components

---

clients/search-component/src/TrieveModal/Chat/ChatInput.tsx
clients/search-component/src/TrieveModal/Footer.tsx

cleanup: remove background tailwind background colors from css. Let it inherit from above

---

clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid

feature: make refresh button optionally hidden

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/FloatingActionButton.tsx
clients/search-component/src/TrieveModal/FloatingSearchIcon.tsx
clients/search-component/src/TrieveModal/FloatingSearchInput.tsx
clients/search-component/src/TrieveModal/ModalContainer.tsx
clients/search-component/src/TrieveModal/index.tsx

- bugfix(search-component): ensure zIndex values do not exceed maximum limit across modal components
- feat(search-component): release v0.4.63

bugfix: z-index should never exceed max for search component

---

clients/trieve-shopify-extension/extensions/admin-block-pdp-questions/src/BlockExtension.tsx
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid

feature: use app metafields for pdp questions

---

clients/trieve-shopify-extension/app/routes/webhooks.app.redact-shop.tsx

feature: add more handling for webhook failures

---

clients/trieve-shopify-extension/app/components/HomepageSyncStatus.tsx
clients/trieve-shopify-extension/app/components/PlanView.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard._index.tsx

BEFORE:
https://github.com/user-attachments/assets/e9a60b6d-3476-457f-8f4e-45625a2014a9
AFTER: 
https://github.com/user-attachments/assets/879d09c5-6ddb-448b-91fa-d276c400dfd5

styling: shopify sidebar wrap

---

server/src/bin/clone-qdrant-from-offset.rs

bugfix(clone-qdrant-from-offset): stop early if there are no points to upsert

---

clients/trieve-shopify-extension/app/components/PlanView.tsx
clients/trieve-shopify-extension/app/context/trieveContext.tsx
clients/trieve-shopify-extension/app/queries/shopDataset.ts

feature: refetch organization details on client

---

clients/trieve-shopify-extension/app/components/onboarding/AddComponentOnboarding.tsx
clients/trieve-shopify-extension/app/components/onboarding/TutorialVideo.tsx
clients/trieve-shopify-extension/app/hooks/add-component-onboard.tsx
clients/trieve-shopify-extension/app/queries/onboarding.ts
clients/trieve-shopify-extension/app/routes/app._dashboard._index.tsx

feat: "update" component on theme & make checks more self-explanatory

---

server/Cargo.lock
server/Cargo.toml
server/src/lib.rs

https://github.com/user-attachments/assets/8014e7fc-afbc-4364-886b-4ae19652f7b3

feature: req-reply cache for get tool function params

---

clients/trieve-shopify-extension/app/api/judgeMe.ts
clients/trieve-shopify-extension/app/processors/getProducts.ts

This adds a lot more context when the llm parses through the review chunks. The rest can be modified through the llm rag prompt

enhacement(shopify): Add more context to the chunk_html of product reviews. + bugfix: don't index title in the tagset

---

server/src/operators/analytics_operator.rs

bugfix: left join rag_queries_query on events. Sometimes the events don't get registered due to firewall blocking. We still should display results

---

clients/search-component/example/src/routeTree.gen.ts
clients/search-component/example/src/routes/inline.tsx
clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/TrieveModal/index.css
yarn.lock

feature: add markdown table rendering ability

---

clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
server/src/data/models.rs
server/src/handlers/analytics_handler.rs
server/src/operators/analytics_operator.rs

feature: add ability to filter out collapsed queries for count queries

---

clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid

feature: add allowRefreshSuggestedQueries to shopify global_component

---

docker/collapse-query-script/collapse_queries.go

bugfix: ensure that all the fields are being inserted

---

server/src/data/models.rs
server/src/operators/model_operator.rs

bugfix: set default RERANKER_BASE_URL to always be the same

---

clients/trieve-shopify-extension/shopify.app.flaviar-trieve-chat-extension.toml
clients/trieve-shopify-extension/shopify.app.mac-case-extension.toml
clients/trieve-shopify-extension/shopify.app.stark-dev-trieve-extension.toml
clients/trieve-shopify-extension/shopify.app.stark-trieve-search-extension.toml
clients/ts-sdk/openapi.json
clients/ts-sdk/src/functions/message/index.ts
clients/ts-sdk/src/types.gen.ts
server/Cargo.lock
server/Cargo.toml
server/src/data/models.rs
server/src/handlers/message_handler.rs
server/src/lib.rs
server/src/middleware/timeout_middleware.rs
server/src/operators/message_operator.rs
yarn.lock

Added route to wrap openai's image_edit route

feature: image_edit route

---

server/src/bin/ingestion-worker.rs
server/src/operators/chunk_operator.rs

chore: add extra logs to ingestion to find more potential bottlenecks

---

clients/trieve-shopify-extension/app/auth.ts
clients/trieve-shopify-extension/extensions/enrich-content-block/README.md
clients/trieve-shopify-extension/extensions/enrich-content-block/locales/en.default.json
clients/trieve-shopify-extension/extensions/enrich-content-block/locales/fr.json
clients/trieve-shopify-extension/extensions/enrich-content-block/package.json
clients/trieve-shopify-extension/extensions/enrich-content-block/shopify.extension.toml
clients/trieve-shopify-extension/extensions/enrich-content-block/src/ActionExtension.tsx
clients/trieve-shopify-extension/extensions/enrich-content-block/src/BlockExtension.tsx
clients/trieve-shopify-extension/extensions/enrich-content-block/src/TrieveProvider.tsx
clients/trieve-shopify-extension/extensions/enrich-content-block/src/useChunkExtraContent.ts
clients/trieve-shopify-extension/yarn.lock

feat: enrich product information block

---

.github/workflows/push-server.yml
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/DatasetOverview.tsx
server/Cargo.lock
server/Cargo.toml
server/Dockerfile.clone-dataset-worker
server/src/bin/clone-dataset-worker.rs
server/src/bin/crawl-worker.rs
server/src/bin/etl-worker.rs
server/src/bin/file-worker.rs
server/src/bin/ingestion-worker.rs
server/src/bin/update-worker.rs
server/src/data/models.rs
server/src/handlers/auth_handler.rs
server/src/handlers/dataset_handler.rs
server/src/handlers/file_handler.rs
server/src/handlers/group_handler.rs
server/src/lib.rs
server/src/operators/chunk_operator.rs
server/src/operators/group_operator.rs

feature: added ability to clone datasets

---

clients/search-component/example/src/routes/inline.tsx
clients/search-component/src/vanilla/index.tsx
clients/trieve-shopify-extension/app/components/DatasetSettings.tsx
clients/trieve-shopify-extension/app/queries/metafield.ts
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/similar_products.liquid

feature: added ability to easily switch to dev mode in settings

---

clients/search-component/src/TrieveModal/Footer.tsx
clients/search-component/src/TrieveModal/ModalContainer.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/utils/hooks/useSizing.ts
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/search_page.liquid
clients/trieve-shopify-extension/extensions/global-search/blocks/similar_products.liquid

feature: added search page for shopify

---

clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
frontends/search/src/components/ResultsPage.tsx
frontends/search/src/components/SearchForm.tsx
server/src/data/models.rs
server/src/handlers/group_handler.rs
server/src/lib.rs
server/src/operators/qdrant_operator.rs
server/src/operators/search_operator.rs

feature: add autocomplete search over groups

---

clients/search-component/src/TrieveModal/Search/SearchMode.tsx

bugfix: fix search page with filter bar

---

frontends/dashboard/package.json
frontends/dashboard/src/components/ApiKeys.tsx
frontends/dashboard/src/components/DatasetOverview.tsx
frontends/dashboard/src/index.tsx
server/src/handlers/organization_handler.rs
server/src/lib.rs
server/src/operators/organization_operator.rs
server/static/output.css

- **feat: add fulltext_content field to ChunkReqPayload and related structures**
- **cleanup: filter out collapsed queries for query counts**
- **hack: hard swap reranker url if it matches to the k8s dns name. it should instead use the environment variable just in case the k8s dns name gets changed**
- **feature: add autocomplete search over groups**
- **feature: add autocomplete search over groups to the frontend**
- **feature: add api key pagination**

feature: add api key pagination

---

clients/ts-sdk/openapi.json
server/src/handlers/group_handler.rs
yarn.lock

nit: rename tag for autocomplete over groups

---

clients/search-component/README.md
clients/search-component/package.json
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/ts-sdk/package.json
clients/ts-sdk/src/functions/message/index.ts

bugfix: make fetch override opt-in only via prop

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/TrieveModal/index.css
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/hooks/usePublicPageSettings.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/lib.rs

- **feature(server+dashboard+component): add component prop for PriceTool parameters + necessary server and dashboard code for allowing it to be set on demo page**
- **bugfix(search-component): enable horizontal scroll on tables within the component**

bugfix: table scroll issues + feature: allow for setting params of price tool call

---

clients/search-component/README.md
clients/search-component/src/TrieveModal/Search/SearchInput.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/hooks/setClickTriggers.ts

feature: add search bar integration

---

clients/search-component/package.json
clients/search-component/src/utils/hooks/chat-context.tsx

- **bugfix(search-component): use both search and getChunks for the inline PDP chat so we always get chunks**
- **feat(search-component): v0.4.74**

bugfix: search component pdp fulltext search does not always get results

---

clients/search-component/package.json
clients/search-component/src/TrieveModal/FilterSidebarComponents.tsx
clients/search-component/src/TrieveModal/Search/SearchMode.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/trieve-shopify-extension/extensions/global-search/blocks/search_page.liquid
yarn.lock

feature: add price range slider

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/CloneDatasetModal.tsx
frontends/dashboard/src/components/DatasetOverview.tsx
server/src/handlers/dataset_handler.rs

feature: option to clone dataset settings without cloning chunks

---

clients/search-component/src/TrieveModal/FilterSidebarComponents.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/trieve-shopify-extension/app/components/FIlterBlock.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.filters.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/FilterSidebarBuilder.tsx
server/src/handlers/page_handler.rs

feature: add ai filter bar

---

clients/trieve-shopify-extension/app/components/ResetSettings.tsx
clients/trieve-shopify-extension/app/processors/getProducts.ts

bugfix: fix shopify app build

---

clients/trieve-shopify-extension/package.json
clients/trieve-shopify-extension/yarn.lock
clients/ts-sdk/package.json

bugfix: fix shopify image build

---

clients/search-component/src/utils/hooks/chat-context.tsx

- **feature: search route finalized**
- **feature: add get_tool_call function**
- **bugfix: fix createMessageFilters to continue to respect the default filtering logic**

bugfix: fix createMessageFilters to continue to respect the default

---

clients/search-component/package.json
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/trieve-shopify-extension/app/components/DatasetSettings.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/trieve-shopify-extension/extensions/global-search/blocks/inline_component.liquid
clients/ts-sdk/package.json

feature: added seperate system and pdp system prompts

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/handlers/page_handler.rs
server/src/public/page.html

bugfix: fix the demo page w/ serp

---

clients/trieve-shopify-extension/app/queries/onboarding.ts

bugfix: modify onboarding query to get as many themes as possible

---

server/src/data/models.rs
server/src/handlers/message_handler.rs
server/src/operators/message_operator.rs

feat(server): rag_context field for adding better context

---

clients/trieve-shopify-extension/app/routes/app._dashboard.experiments.tsx

bugfix: fix the Response.json error

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/handlers/page_handler.rs
server/src/public/page.html

feature: add pdp prompt to the demo page

---

clients/search-component/example/package.json
clients/search-component/example/yarn.lock
clients/search-component/package.json
clients/search-component/src/utils/hooks/useSizing.ts
yarn.lock

bugfix: fix the max height for the modal

---

clients/search-component/src/TrieveModal/Chat/FollowupQueries.tsx
clients/search-component/src/TrieveModal/Chat/ResponseMessage.tsx
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/Search/DocsItem.tsx
clients/search-component/src/TrieveModal/Search/ProductItem.tsx
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/trieve.ts

feature: pass ab treatment w/ metadata on analytics

---

clients/search-component/package.json
clients/search-component/src/utils/hooks/modal-context.tsx
clients/trieve-shopify-extension/extensions/trieve-checkout-web-pixel/src/index.ts

feature: add ab treatment to the web pixel

---

clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx

- **feature: tool to determine if a search should be conducted or not**
- **saving changes: added more logic to guarantee that consistency**
- **refactor: change should search to skip search**

refactor: change should search to skip search

---

server/src/operators/model_operator.rs

bugfix: retry reranker calls if one fails

---

clients/trieve-shopify-extension/app/components/settings/PresetQuestions.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.experimentview.$experimentId.tsx

bugfix: remove the filter on the searched products, bugfix: close modal after creating question

---

clients/search-component/src/utils/hooks/chat-context.tsx

bugfix: don't apply filters if there are group ids provided

---

clients/search-component/example/src/routes/ecommerce.tsx
clients/search-component/package.json
clients/search-component/src/TrieveModal/Chat/SuggestedQuestions.tsx
clients/search-component/src/TrieveModal/Search/SuggestedQueries.tsx
clients/search-component/src/TrieveModal/index.tsx
clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/search-component/src/utils/hooks/useFollowupQuestions.ts
clients/search-component/src/utils/hooks/useSuggestedQuestions.ts
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/handlers/message_handler.rs
server/src/handlers/page_handler.rs
server/src/lib.rs
server/src/public/page.html
yarn.lock

feature: allow for image upload with default questions

---

clients/search-component/src/utils/hooks/chat-context.tsx

feature: followup uses groups ids in group mode

---

clients/trieve-shopify-extension/app/components/onboarding/WelcomeOnboarding.tsx
clients/trieve-shopify-extension/app/components/settings/DatasetSettings.tsx
clients/trieve-shopify-extension/app/components/settings/PolicySettings.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/trieve-shopify-extension/extensions/global-search/blocks/global_component.liquid

bugfix(shopify): have shopify policies refresh, make loading spinner stop after 90% of products are ingested, let policies get fed into the search

---

clients/search-component/src/utils/hooks/chat-context.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
frontends/shared/ui/MultiStringInput.tsx
server/src/handlers/page_handler.rs

feature: pdp image upload and generation

---

clients/search-component/src/utils/hooks/chat-context.tsx
clients/search-component/src/utils/hooks/modal-context.tsx
clients/trieve-shopify-extension/app/components/settings/LLMSettings.tsx
clients/trieve-shopify-extension/app/routes/app._dashboard.settings.tsx
clients/ts-sdk/openapi.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/hooks/usePublicPageSettings.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/data/models.rs
server/src/handlers/page_handler.rs
server/src/lib.rs

refactor: fix must_not search filters

---

clients/search-component/src/utils/hooks/chat-context.tsx

fix: only use three reference images for editing

---

clients/ts-sdk/openapi.json
clients/ts-sdk/src/functions/message/index.ts
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
server/src/handlers/message_handler.rs
server/src/handlers/page_handler.rs
server/src/lib.rs
yarn.lock

feature: auto configure most common tag filters

---

server/src/data/models.rs
server/src/handlers/message_handler.rs
server/src/lib.rs
server/src/operators/message_operator.rs

feature: add back clickhouse and other create message settings to agentic search

---

clients/ts-sdk/openapi.json
clients/ts-sdk/package.json
clients/ts-sdk/src/types.gen.ts
frontends/dashboard/src/components/dataset-settings/LLMSettings.tsx
frontends/dashboard/src/pages/dataset/PublicPageSettings.tsx
yarn.lock

feature: add tool configuration to dashboard

---

server/src/operators/message_operator.rs

fix: prevent double delimiter in JSON stringification for agentic search

---

terraform/aws/trieve-aws/main.tf
terraform/aws/trieve-aws/variables.tf
terraform/aws/trieve.tf

feature(terraform/aws): add option to disable `gpu_taints`

---

server/src/data/models.rs
server/src/middleware/auth_middleware.rs
server/src/operators/search_operator.rs

feature: dedup autocomplete by group and add api key filtering for that route

---

server/Dockerfile.server

fix(deps): update subtrace to b314

---

server/Cargo.lock
server/Cargo.toml

feature: update openid-connect to patch that allows for authentication through auth0 domains

---

docker-compose.yml

feature: add health checks in docker-compose
